### ISSUE TITLE
CTL-997: Some unit tests depends on each other

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1000]
Jira issue originally created by user szogun1987:

There are couple of unit tests that passes if they are executed in test bundle but fails if they are run separately. I will prepare list of tests.

**Comment by GeertvanHorrik** [comment]
@szogun1987 Do you have a list? If so, we will fix this for v5. Note that we are moving quite some components from Catel to separate repositories to make it easier to maintain both Catel and these components.

**Comment by szogun1987** [comment]
Hi. Sorry for late response. I haven't worked at Catel for a couple of months, and I don't know when I will be able to. Please lower priority of this issue (running all tests is good enough workaround for now).

**Comment by GeertvanHorrik** [comment]
I'll put 5.1 milestone on this. If you can provide a list of tests, then we can fix them. Thanks!
