### ISSUE TITLE
CTL-999: DoubleClickToCommand cause memory leaks

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1002]
Jira issue originally created by user szogun1987:

If Window is closed and all references to it are detached it still occupies memory if it uses DoubleClickToCommand and view-model that contains command it still reachable. I propose to use WeakEventHandler inside of it.

**Comment by GeertvanHorrik** [comment]
@szogun1987 Pinging you. If you don't have time, please let me know.

**Comment by szogun1987** [comment]
I will check if OnDetaching detaches this event. This bug may appear in mine app because I use version of MahApps controls that causes OnDetachind to be not called.

**Comment by GeertvanHorrik** [comment]
Thanks. I'm trying to close as much issues as possible for Catel v5 this week. Maybe we'll just release a v5 without waiting for net standard (that will be 6.0 then).

**Comment by GeertvanHorrik** [comment]
Moving this towards 5.1, this shouldn't be a breaking hange.

**Comment by GeertvanHorrik** [comment]
We believe this has been fixed by #142

**Comment by GeertvanHorrik** [comment]
@szogun1987 we will release a new unstable build with the major changes for Catel v5 tonight. Could you please check if this has been fixed?

**Comment by szogun1987** [comment]
I have checked with older version on simple app without MahApps it seems to work fine. Please close with "Not reproducible status"

**Comment by GeertvanHorrik** [comment]
Thanks for the feedback, closing.
