### ISSUE TITLE
Migrate xaml uri from catel.codeplex.com => catelproject.com

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1003]
1. Update the code
2. Update the upgrade guide

**Comment by GeertvanHorrik** [comment]
We need to check if this is a breaking change on the xml serialization. Let's see if beta users report this issue.

**Comment by advapiIT** [comment]
I can do testing if you want

**Comment by GeertvanHorrik** [comment]
That would be nice. I am building backwards compatibility into this so we remap the namespace (xml deserialization).

**Comment by GeertvanHorrik** [comment]
Namespace has been changed to schemas.catelproject.com. Will deploy a new version today to MyGet.
