### ISSUE TITLE
IsDirty is true at creating Viewmodel (Constructor)

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1007]
If viewmodel is created the flag IsDirty ist already set to true.
I set the IsDirty manualy to false, and ask the property again in a canexecute method. The IsDirty is true again.

**Comment by GeertvanHorrik** [comment]
We are considering to remove this property from the ModelBase (and thus ViewModelBase) in the future. We want to simplify the ModelBase to decrease its footprint.

**Comment by MattiasEppler** [comment]
So I have to create my own IsDirty Flag?

**Comment by GeertvanHorrik** [comment]
In v5, we are considering it. This also allows you to have more control over how the property should behave.

**Comment by MattiasEppler** [comment]
Is this issue pointing to same problem:
https://catelproject.atlassian.net/browse/CTL-930
Do validation listen to IsDirty?

**Comment by GeertvanHorrik** [comment]
Please refer to the new GitHub issues, in this case #932

**Comment by GeertvanHorrik** [comment]
I think validation listens do property changes, it does not check the IsDirty property.

**Comment by GeertvanHorrik** [comment]
Validation ignores IsDirty (and some other properties).

**Comment by GeertvanHorrik** [comment]
Written unit tests to ensure that IsDirty does not trigger a validation. It's also possible to override the  `ShouldPropertyChangeUpdateIsDirty` method

**Comment by GeertvanHorrik** [comment]
Covered by unit tests, closing.
