### ISSUE TITLE
Drop PleaseWaitHelper and use busy indicator instead for WPF

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1010]
Allows lots of code removal.

**Comment by henrik-m** [comment]
I've stumbled upon this when updating Catel to 5.2.0. Previously, an overlay with the given message was shown in my WPF app. According to the [docs](https://catelproject.atlassian.net/wiki/spaces/CTL/pages/1409211/PleaseWaitService) that has not changed.  But now I only get a blank white page with a WaitCursor, which is not useful at all.

Is there another recommended solution to get the overlay back? Am I missing a required setup step? I could not find anything regarding this in the docs.

**Comment by GeertvanHorrik** [comment]
You can either copy/paste the code into your own project and implement your own PleaseWaitService impleemntation (you'll see why we removed it ;-)). Another one to use is the one we deliver using Orchestra, it's a very neat progress bar (including progress support at the bottom of the screen).
