### ISSUE TITLE
Move Catel.Extensions.Prism5 to Orc.Prism5

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1012]
@alexfdezsauco You want write access to these repositories?

**Comment by alexfdezsauco** [comment]
Yes

**Comment by GeertvanHorrik** [comment]
Prepared the component:

github.com/wildgums/orc.prism

**Comment by GeertvanHorrik** [comment]
All code has been migrated and the first unstable version has been deployed to NuGet. Only the docs left.

**Comment by GeertvanHorrik** [comment]
Docs have been migrated as well.
