### ISSUE TITLE
XML Serialization: Creating multiple instances of the same reference

### ISSUE THREAD

**Issue by samirem** [Catel/Catel#1020]
### Steps to reproduce
Run the repro provided

### Expected behaviour
When serializing/deserializing, I want references to the same instance to be kept.

To clarify: In my repro example I expect that the "garage.Vehicles[0]" and "garage.VehicleGroups[0].Vehicles[0]" should both hold a reference to the same instance of 'car1', since they do that before serialization/deserialization.

### Actual behaviour
See repro

[SerializationRepro.gz](https://github.com/Catel/Catel/files/1001156/SerializationRepro.gz)

**Comment by GeertvanHorrik** [comment]
We are trying to make all the breaking changes ASAP for v5. I'll put this on the list for 5.1 which will be the first maintenance release of the v5 branch.

**Comment by GeertvanHorrik** [comment]
This is probably caused because the collection is serialized by the internal DataContractSerializer. I'll check what I can do to enforce graphid to be added to the elements.

**Comment by GeertvanHorrik** [comment]
Moving this to up-for-grabs since we don't need this functionality ourselves in the near future.
