### ISSUE TITLE
Updated Template files for VS2017

### ISSUE THREAD

**Issue by advapiIT** [Catel/Catel#1022]
*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

As we talked on gitther, here're the update files 
Consider that 

# templates.zip contains the project's templates for C# and VB.NET as we talked
[templates.zip](https://github.com/Catel/Catel/files/1010236/templates.zip)

# src.zip contains the solution files under src\Catel.Templates updated for VS2017
[src.zip](https://github.com/Catel/Catel/files/1010238/src.zip)

HTH

**Comment by GeertvanHorrik** [comment]
Fixed for 5.2, released to Visual Studio Gallery.
