### ISSUE TITLE
Allow configuration service to choose path format

### ISSUE THREAD

**Issue by ttustonic** [Catel/Catel#1027]
### Feature description

Allow ConfigurationService to choose a path format between:
`<Profile Directory>\<Company Name>\<App Name>\<Version>\user.config`
and
`<Profile Directory>\<Company Name>\<App Name>_<Evidence Type>_<Evidence Hash>\<Version>\user.config
`
or make it easier to change _localConfigFilePath and _roamingConfigFilePath without rewriting the whole ConfigurationService.

WPF user settings use the second version, and using both WPF settings mechanism and ConfigurationService puts configuration files all over the place.

**Comment by GeertvanHorrik** [comment]
Thanks for the feature request. We'll look into it, but we always write settings to the %appdata%\[company]\[product]\settings.xml. Being able to customize the path is already a good idea. Interested in doing a PR?

**Comment by ttustonic** [comment]
I am, but I'm quite busy with two projects, both slightly late, so perhaps later.
