### ISSUE TITLE
Some global styles don't work in DataWindow, work in Window

### ISSUE THREAD

**Issue by ttustonic** [Catel/Catel#1028]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Modify MainWindow.xaml in Catel.Examples.WPF.PersonApplication
2. Add following:

        <catel:DataWindow.Resources>
        <Style TargetType="{x:Type StackPanel}">
            <Setter Property="Background" Value="LightGreen" />
        </Style>
        <Style TargetType="{x:Type GroupBox}">
            <Setter Property="Background" Value="LightBlue" />
        </Style>
        </catel:DataWindow.Resources>

3. 

Platform:
.NET version: 4.5, 4.6.2

### Expected behaviour

StackPanel should be light green, GroupBox should be light blue.

### Actual behaviour
GroupBox background color is not changed.
If I replace Mainwindow.xaml from catel:DataWindow to Window, everything is fine.

Can you also include a screen shot?

![datawindow](https://cloud.githubusercontent.com/assets/5532089/26427004/3e4eab72-40db-11e7-98e1-38593259e31b.gif)
![window](https://cloud.githubusercontent.com/assets/5532089/26427009/4273a586-40db-11e7-8875-82000ce30a32.gif)
[MainWindow.zip](https://github.com/Catel/Catel/files/1027339/MainWindow.zip)

**Comment by GeertvanHorrik** [comment]
Thanks for adding a repro, that makes stuff much easier to investigate.

**Comment by GeertvanHorrik** [comment]
Seems to work fine in 5.1 / 5.2:

![image](https://user-images.githubusercontent.com/1246444/30453929-da8e8eae-999a-11e7-9b16-41cb05c65532.png)
