### ISSUE TITLE
CommandManagerBinding not working with EventToCommand

### ISSUE THREAD

**Issue by HumpaLumpa007** [Catel/Catel#1057]
### Steps to reproduce

1. clone this repo: https://github.com/HumpaLumpa007/EventToCommand.CommandManagerBinding
2. build and execute project
3. right click on a item on the right site and execute "add". This should add the item to the other list.
4. click the button "add" on the top. should add the item to the list on the right
5. double click an item in the right list. MessageBox should appear, but no item will be moved. 

Platform: Windows 10 x64 Enterprise
.NET version: 4.5.2

### Expected behaviour

On double clicking an item on the right site it should be added to the list on the right site

### Actual behaviour

Nothing is happening if a Command is bound via CommandManagerBinding to a EventToCommand. If the Command is in the ViewModel and bound "normally" it's working fine. see this: https://stackoverflow.com/questions/44669964/eventtocommand-and-commandmanagerbinding-not-working

**Comment by GeertvanHorrik** [comment]
Testing with Catel v5.

**Comment by GeertvanHorrik** [comment]
I made 2 changes:

1. I *create* the command at startup:

```
            var commandManager = ServiceLocator.Default.ResolveType<ICommandManager>();
            commandManager.CreateCommand("AddToCollectionCommand");
```

Then I register an action for the command inside the VM:

```
      commandManager.RegisterCommand("AddToCollectionCommand", AddToCollectionCommand, this);
```

2. You have to bind the command first, then the command parameter in xaml (order matters, although it shouldn't, but that's a xaml parsing issue we can't fix):

```
          <!--not working!-->
          <catel:EventToCommand 
                                      Command="{catel:CommandManagerBinding AddToCollectionCommand}" 
                                      CommandParameter="{Binding SelectedDataItem}"
                                      DisableAssociatedObjectOnCannotExecute="False" />
```

**Comment by GeertvanHorrik** [comment]
Closing the ticket. Feel free to re-open if it's not solved for you.
