### ISSUE TITLE
Possible bug in FastObservableCollection

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1066]
This code:

```
                var searchResultGroups = SearchResultGroups;
                using (searchResultGroups.SuspendChangeNotifications())
                {
                    foreach (var searchCategory in searchCategories)
                    {
                        foreach (var searchCategoryItem in searchCategory.Items)
                        {
                            searchResultGroups.Add(new SearchResultGroup(searchCategoryItem.Id, searchCategoryItem));
                        }
                    }
                }
```

Results in the UI showing only the *first* `searchResultGroup`, while it should show 3 in my case. Could this be related to the changes we made to the mixed mode? 

Will investigate a bit more in the meantime.

**Comment by GeertvanHorrik** [comment]
No, it looks like I am having the same issue when using a List<T>.

**Comment by GeertvanHorrik** [comment]
Just reverted back to 5.0.0-unstable0324 and it starts working again. Definitely a problem in the latest version.

**Comment by GeertvanHorrik** [comment]
.333 still works.

**Comment by GeertvanHorrik** [comment]
Even .346 works, so it's definitely introduced with the latest collection changes.

**Comment by GeertvanHorrik** [comment]
I think it's the removal of the .Reset which was used before in case of SuspensionMode == None.

**Comment by GeertvanHorrik** [comment]
Hmmm, looks like UWP (and maybe other platforms) can't really deal with single add events. When I change the code to this:

```
                        for (var i = 0; i < suspensionContext.Count; i++)
                        {
                            eventArgsList.Add(CreateEventArgs(NotifyCollectionChangedAction.Add, suspensionContext.NewItems[i], suspensionContext.NewItemIndices[i]));
                        }
```

It starts working again. But this breaks the whole point of using the FastObservableCollection.

**Comment by GeertvanHorrik** [comment]
Implementing this as .Reset now with the right added and/or removed items. This way the end-developer still will receive a single change call *and* has access to the modified items. I think this is the best it can become for now.

**Comment by DanielKuehner** [comment]
You really killed the add and remove events so that all are reset now?
Do you know what now happens to UIs having massive data shown?
Our whole application will now freeze every time we remove or add single items...

**Comment by DanielKuehner** [comment]
What do you mean with "single add events"? One add event with multiple items?
Yes, no UI can deal with it. Because this is not supported be .NET even.
But I told you this. We have a special proxy class which splits up this merged event to multiple single events so the ui can deal with it.

**Comment by GeertvanHorrik** [comment]
For a full description & bug report, see https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/19851862-potential-bug-in-observablecollection-when-adding

**Comment by GeertvanHorrik** [comment]
@DanielKuehner It was always a reset before. For Catel v5, we have optimized the collection and only raise what has really changed (with the right items, etc). This is all covered by unit tests, but the UI doesn't correctly deal with e.NewItems when the count > 1 & action == Add.

To make sure that the collection *at least* shows the right data, we will still raise a *single* event but in case of .Add, we use the .Reset action (just like before).

We could "optimize" this by only forcing a .Reset when the suspension mode is none.

**Comment by GeertvanHorrik** [comment]
This way the user can workaround this bug (which exists in UWP and maybe in WPF as well) by passing in SuspensionMode = none. It will still raise single events when using explicit suspension modes.

**Comment by DanielKuehner** [comment]
I have not followed Catel for a long time and especially the changes in the FOC.
But your last commit removed the add and remove args and changed it to reset.
So the only events the UI now gets is a reset event - netherless what you are doing ... or am I wrong?
If this is correct - ok I have to test it before - I have to stop using your FOC version and must use my old version.

Take a look at my first comment: https://catelproject.atlassian.net/browse/CTL-856

**Comment by DanielKuehner** [comment]
With _my_ FOC as I provided you, you _cannot_ use the FOC anymore directly in the UI!

**Comment by DanielKuehner** [comment]
Here the working link: http://referencesource.microsoft.com/#PresentationFramework/Framework/System/Windows/Data/CollectionView.cs,8d94ad9a5c0898c5

Multi item events are not supported by the WPF UIs!
They can be validly raised with the NotifyCollectionChangedEventArgs but they do not work in the UI.

You _must_ split them up again for the UI.
But this way is much better for the non-UI functionality because there you can iterate over the multiple items per event.

**Comment by GeertvanHorrik** [comment]
Just committed some more changes. Now we have suspension mode:

1. None => default, reset event with both added & removed items
2. Add => single .Add event with added items
3. Remove => single .Remove event with removed items
4. Mixed => single .Add (if added) and single .Remove (if removed) events

So if you don't specify a mode explicitly, it will result in a single .Reset event (existing behavior). But the rest will keep working as is, with .Mixed as a new feature introduced in v5.

**Comment by GeertvanHorrik** [comment]
So in non-ui cases, you can easily use 2, 3 or 4 (which you are probably already doing). For UI cases, you can use 1.

**Comment by DanielKuehner** [comment]
You have missed to remove the old comments ;)

I hope all will be aware of this (new) behavior. But I do not have a good feeling :) perhaps because I don't know so much about the latest changes and imho I believe in most cases you cannot choose the mode because it comes from somewhere else.

I will look into this as a have time to take preview with Catel v5 in my project.

**Comment by GeertvanHorrik** [comment]
Thanks for the note about the comments. I've checked the previous implementation of FOC. As you can see, we already used the .Reset if you didn't explicitly specify the SuspensionMode, so we haven't changed the existing behavior. We only improved and expanded it.

https://github.com/Catel/Catel/blob/master/src/Catel.MVVM/Catel.MVVM.Shared/Collections/FastObservableCollection.cs#L448

**Comment by DanielKuehner** [comment]
Ok. I hope I will find the space in the next time to take a look at v5.

**Comment by GeertvanHorrik** [comment]
Closing issue as it all seems fixed.
