### ISSUE TITLE
v 5.0.0. Catel - based app crashes on start

### ISSUE THREAD

**Issue by szogun1987** [Catel/Catel#1067]
### Steps to reproduce

1. Just start application that uses IUIVisualizerService (read any)

Platform:
.NET version: 4.5 
Catel: dev-version: that bases on commit 67c8b22cd768ec9335340d67fd8a310922ac8bf1
I use Catel for wpf

### Expected behaviour
Application shouldn't crash

### Actual behaviour
Application crashes:
ShowWindowAsync method calls HandleCloseSubscription it invokes SubscribeToWeakEvent method with handler of type Action. In the end SubscribeToWeakEventWithExplicitSourceType is called and reports error with message:
Only handlers of type 'PropertyChangedEventHandler', 'NotifyCollectionChangedEventHandler' or 'EventHandler<TEventArgs' are supported. 'Action' does not belong to these supported types

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, this is probably caused by #974

**Comment by GeertvanHorrik** [comment]
Can you next time upload the repro as well? I'll create one myself now.

**Comment by GeertvanHorrik** [comment]
Implementing support for action handlers in WeakEventListener.

**Comment by GeertvanHorrik** [comment]
The nice thing is that WeakEventListener now supports actions (even ones in a display class), so actually a good thing that we hit this issue.

**Comment by szogun1987** [comment]
I have checked it on version built today. It doesn't crash. When do you plan to deliver version 5.0? We would like to use it in our product (one IoC fixture is applied in it).

**Comment by GeertvanHorrik** [comment]
The idea is to go into beta asap (we believe it's all feature-complete now). Beta versions will be published to NuGet so used by more people (and we will use it in our tooling as well).

**Comment by szogun1987** [comment]
If you notify me about Beta Release mine company can perform regression tests on our app that uses it quite intensively (we have 700+ types registered in IoC container, application runs on multiple threads, It happens that we creating couple of thousands  objects in short period of time using type factory).
We have only one requirement. API will not be changed after beta release and none bahavior-breaking change will be introduced.

**Comment by GeertvanHorrik** [comment]
I recommend that you subscribe to the RSS feed of Catel:

http://catelproject.com/2017/07/14/catel-5-into-beta/

**Comment by GeertvanHorrik** [comment]
>> We have only one requirement. API will not be changed after beta release and none bahavior-breaking change will be introduced.

We think that this won't be the case, but if we really have to, we will do it.
