### ISSUE TITLE
Create static array types for empty arrays

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1068]
Array.Empty<T> is only supported in .NET 4.6, but could be made available in lower versions as well.

See https://twitter.com/davkean/status/885344193375125504

**Comment by GeertvanHorrik** [comment]
We could create an ArrayShim (like we did with TaskShim). Then we can use this everywhere.

**Comment by GeertvanHorrik** [comment]
ArrayShim has been created. @alexfdezsauco , can you find the implementations that can be replaced to minimize allocations and create a PR?

**Comment by alexfdezsauco** [comment]
Replacements are required in the following files:

	src/Catel.Core/Catel.Core.Shared/IO/Extensions/StreamExtensions.cs
	src/Catel.Core/Catel.Core.Shared/IoC/CatelDependencyResolver.cs
	src/Catel.Core/Catel.Core.Shared/IoC/TypeRequestPath.cs
	src/Catel.Core/Catel.Core.Shared/Runtime/Serialization/XmlSerialization/DataContractSerializerFactory.cs
	src/Catel.MVVM/Catel.MVVM.Shared/MVVM/Converters/MethodToValueConverter.cs
	src/Catel.MVVM/Catel.MVVM.Shared/MVVM/Helpers/ViewHelper.cs
	src/Catel.Test/Catel.Test.Shared/Runtime/Serialization/GenericSerializationFacts.collections.cs

The changes will be available at `feature/1068-MinimizeAllocByUsingArrayShim` branch.
