### ISSUE TITLE
Catel.Fody on myget

### ISSUE THREAD

**Issue by mennodeij** [Catel/Catel#1069]
Hi,

I've tried leaving a comment on the thread catelproject.com/2017/06/27/catel-5-nearing-feature-complete-state/ but it does not seem to stick, so I write to you here.

It seems that the current stable version of Catel.Fody does not work with the alpha version of Catel.Core, so could you please also release an accompanying Catel.Fody on myget.org to go with the alpha versions of Catel.Core? 

Thx!

**Comment by GeertvanHorrik** [comment]
Weird, we built 2.17 to make sure it works with Catel v5. Do you have a repro?

**Comment by mennodeij** [comment]
Attached is a simple repro which works with Catel.Core v4.5.4 and I get the following error with the latest 5.0.0 version.
    
    1>MSBUILD : error : Fody: Expected to find method 'WriteWithData(Exception, String, Object, LogEvent)' on type 'Catel.Logging.ILog'.

Maybe this is problematic because the `WriteWithData` method is an extension method? 
[CatelFodyTest.zip](https://github.com/Catel/Catel/files/1147703/CatelFodyTest.zip)

**Comment by GeertvanHorrik** [comment]
I think that's Anotar, not Catel being the issue?

**Comment by mennodeij** [comment]
Yeah, you're right of course. Sorry for the confusion. Is there anything that can be done about Anotar?

**Comment by GeertvanHorrik** [comment]
We should patch it and make it Catel 5 compatible as well, but I don't see any time for that in the near future. For now I recommend to use regular logging instead.

**Comment by mennodeij** [comment]
Will do, thanks for your quick replies :smile:

**Comment by tpluscode** [comment]
HI @GeertvanHorrik. I'm trying to address this issue as reported in Anotar. I see that the method used previously to log exceptions was `ILog#WriteWithData(Exception, String, Object, LogEvent)`. 

Now that this method is gone what is the right way? Guess I should rather be using the methods from `LogExtensions`?

**Comment by tpluscode** [comment]
Ok, I found the extension method which replaces the old instance method.

Weirdly however, I see that the `TypeFactory` calls `Log.Debug("Cleared type constructor cache")`. It interferes with some test where I inspect what got logged to `DEBUG`. During that test I get this log message 3 times. Is that expected?

**Comment by GeertvanHorrik** [comment]
I think the type constructor cache gets reset whenever new types are registered in the service locator (meaning it *could* result in the TypeFactory being able to use a better constructor at this stage).

Also make sure that the old version (Catel 4.x) keeps working. You can do that by using specific version checks.

**Comment by GeertvanHorrik** [comment]
For details, see:

https://github.com/Catel/Catel.Fody/blob/develop/src/Catel.Fody/Extensions/CecilExtensions.cs#L19
