### ISSUE TITLE
TypeFactory.CreateInstanceWithParameters does not use most specialized constructor, dependent on order in file

### ISSUE THREAD

**Issue by mennodeij** [Catel/Catel#1070]
*IF BUG, INCLUDE THIS PART:*

The problem is reproduced with the following code:

    class Program
    {
        static void Main(string[] args)
        {
            LogManager.AddListener(new ConsoleLogListener());

            ClassA a = new ClassA();
            ClassB b = new ClassB(a);

            // the following will use the IInterface constructor of B, even when a more 
            // specialized constructor is available. 
            ClassB b2 = TypeFactory.Default.CreateInstanceWithParameters(typeof (ClassB), b) as ClassB;
            
        }
    }

    public interface IInterface
    {    }

    public class ClassA : IInterface
    {    }

    public class ClassB : IInterface
    {
        private ILog _log = LogManager.GetLogger(typeof (ClassB));
        
        public ClassB(IInterface i)
        {
            _log.Write(LogEvent.Info, "ClassB.ctor(IInterface)");
        }

        public ClassB(ClassB b)
        {
            _log.Write(LogEvent.Info, "ClassB.ctor(ClassB)");
        }
    }

Platform: Windows 7, Catel 5.0-unstable0362
.NET version: 4.5

### Expected behaviour

The most specialized constructor should always be used, ClassB(ClassB). 

### Actual behaviour

Instead, the other constructor is used ClassB(IInterface). What's even more counter-intuitive is that if the order of the constructors is changed in the ClassB code file, the program _will_ take the ClassB(ClassB) constructor.

**Comment by GeertvanHorrik** [comment]
This behavior is like this from the beginning. To fix this, instead of checking whether a constructor is compatible, we should look for multiple compatible constructors (create an order of list, because we also need to take into account whether dependencies should be resolved). Need to think about this before making any changes.

**Comment by GeertvanHorrik** [comment]
I think the best thing to do for now is to postpone this one until 5.1 (so we can test this thoroughly without haste).
