### ISSUE TITLE
Mono 5.0.x, stops Catel.Core (TypeCache) from working

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1071]
Originally reported by @mennodeij via Twitter:

Solved in Mono master. For more details, see https://bugzilla.xamarin.com/show_bug.cgi?id=57744

Possible workaround:

Check for null entries in the TypeLoadException.LoaderExceptions array when logging errors in AssemblyHelper.GetAllTypesSafely()

**Comment by mennodeij** [comment]
I did not think that this would warrant an issue here, as it is a problem that will be solved in upcoming Mono release, plus must people using Catel won't be using Mono. Having said that, if you change AssemblyHelper.cs:169 from 

    Log.Warning("  " + error.Message);

to 

    Log.Warning("  " + (error?.Message ?? string.Empty));

I think it will work.

**Comment by GeertvanHorrik** [comment]
Thanks for the additional detail. If we can make life easier for someone with such an easy fix, then we are happy to provide :)

**Comment by GeertvanHorrik** [comment]
Fixed, thanks for reporting.
