### ISSUE TITLE
ServiceLocator.ResolveTypes and ServiceLocator.ResolveAllTypes are confusing

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1075]
I think ResolveAllTypes should have a different name. We can use ObsoleteEx to mark as change and remove in 6.0.

**Comment by alexfdezsauco** [comment]
Agree

**Comment by DanielKuehner** [comment]
If it is just a new method name and redirect the old to the new one. Maybe I can do this. Do you have a new name for this method?

**Comment by GeertvanHorrik** [comment]
The idea is to rename the "ResolveAllTypes" to "ResolveMultiple", which should better reflect what the method does.

**Comment by GeertvanHorrik** [comment]
Done.
