### ISSUE TITLE
Wrong ViewModel created when registering custom View

### ISSUE THREAD

**Issue by advapiIT** [Catel/Catel#1077]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1.Execute the project
2.Click on the B button
3. You'll see that the Viewmodel of AViewModel is initialized

Platform:
.NET version: any

### Expected behaviour

The BViewModel should be initialized

### Actual behaviour

The AViewModel is  initialized

### Description

I try to register a single view for two different Viewmodel, I expected that calling the uiVisualizerService.Show/ShowDialog should call initialize the correct viewmodel instead the last one registered take the advantage. As far I've seen it's seems to be a View first approach instead of ViewModel First

[WPFApplication1.zip](https://github.com/Catel/Catel/files/1177114/WPFApplication1.zip)

**Comment by GreenKn1ght** [comment]
Looks like i faced with similar behavior. 
I registered SecondViewModel and FirstView through IUIVisualizerService.Register<MySecondViewModel, MyFirstView>(), then called IUIVisualizerService.ShowDialogAsync<SecondViewModel>(). It created view, but also created FirstViewModel and set it as DataContext.
It can be resolved by adding to FirstView's constructor parameter IViewModel (or overload), but it wrong behavior as I think.
[Example](https://github.com/Catel/Catel/files/1190597/MyApp.zip)

If you think that this situation is different from this, I'll create a separate issue.

**Comment by advapiIT** [comment]
Yes, it's the same behavior as I've ... really intresting the fact that having a parameterfilled constructor it works... wait for @GeertvanHorrik feedback

**Comment by GreenKn1ght** [comment]
My example also works when View has attribute PreventViewModelCreation set to True. 
I tried set it to your SomeAwesomeView: DataContextChanged was fired (changed to BViewModel), but SomeAwesomeView.ViewModel still null and TextBlock's Text is empty too.

**Comment by GeertvanHorrik** [comment]
I see you are using these 3 packages:

  <package id="Catel.Core" version="5.0.0" targetFramework="net46" />
  <package id="Catel.Extensions.Controls" version="4.5.4" targetFramework="net46" />
  <package id="Catel.MVVM" version="5.0.0" targetFramework="net46" />

We no longer support Catel.Extensions.Controls.

**Comment by GeertvanHorrik** [comment]
The correct VM B is being created and set as DataContext. However, the window itself checks whether the viewmodel can be used using the ViewModelLocator. There the view => view model registration has been overwritten by VM A. 

To "solve" this issue, Catel should allow multiple view models to be registered for a single view. I am not very enthusiastic to enforce this because:

1. It could be a breaking change
2. In the 7 years we've been using Catel, we never encountered his before (so is Catel broken or is your use-case broken?)

**Comment by GeertvanHorrik** [comment]
One of the issues I foresee is what to do when we register multiple view models for a view. If the view needs to resolve, should we use the latest? So basically you want to register multiple (allowed) view models for a view. But at the same time we can only let the view construct 1 vm. This *could* be solved by allowing a list of vm's to be registered, but when resolving, it should always default to the last registered one.

**Comment by GeertvanHorrik** [comment]
Trying a quick implementation as described in the last comment.

**Comment by GeertvanHorrik** [comment]
*if* this works, then this will only work for injected data context objects (injected vm's). Otherwise it will keep using the old behavior and instantiate the last registered VM type, then this can be introduced without breaking changes.

**Comment by GeertvanHorrik** [comment]
Code seems to work in the example app, will also write some unit tests.

**Comment by GeertvanHorrik** [comment]
Done.
