### ISSUE TITLE
Remove the private set; in the documentation

### ISSUE THREAD

**Issue by advapiIT** [Catel/Catel#1078]
### Since with C#6 the private set; became useless, and Catel is build upon latest C# version I suggest that this setter can be removed from doc and from code as well

For example in t[h](http://docs.catelproject.com/vnext/catel-mvvm/commands-events/application-wide-commands/)is link

**Comment by GeertvanHorrik** [comment]
Thanks for the ticket. Since I agree that it's now possible to write properties like this, I don't see any added value in pro-actively removing the private setters (it doesn't actually change behavior). But we can modify the classes once we hit them.

**Comment by GeertvanHorrik** [comment]
Closing as we think this is not very important for the docs.
