### ISSUE TITLE
Exstensions.Controls how to use?

### ISSUE THREAD

**Issue by iHimiko** [Catel/Catel#1079]
Hey guys, tell me, can I use the 5 Catel.MVVM and Catel.Core version with "Extensions.Controls"? Or should I wait for the new version to be implemented? And will it even be?
Thanks a lot!

**Comment by GeertvanHorrik** [comment]
We no longer support Catel.Extensions.Controls. To make it easier to deploy controls with Catel, we've moved the implementations to [Orc.Controls](https://github.com/wildgums/orc.controls) and [Orchestra](https://github.com/wildgums/orchestra) (easier to deploy).
