### ISSUE TITLE
How to get the functionality of two ModelBase splits?

### ISSUE THREAD

**Issue by DanielKuehner** [Catel/Catel#1083]
Great thing with splitting up the ModelBase, but the earlier trick was that with "DisableEventSubscriptionsOfChildValues = false;" the validation of "parent" entities were triggered if "child" entities changed. This is (or was) one of our mayor features. But now I cannot provide it anymore because I cannot derive from both ValidatableModelBase and ChildAwareModelBase at the same time to combine these features.

What were your thoughts about splitting these features? For what else should one use the ChildAwareModelBase?

How shall I know accomplish this once again without copying the code from ChildAwareModelBase?

----

The beta went too fast to release - only two weeks instead of four as you told - so this will be the first ticket of many more. Sry, we could not have get planed it earlier.

**Comment by DanielKuehner** [comment]
My current ideas:
- Merge both classes and disable event subscriptions per default
- Derive ChildAwareModelBase from ValidatableModelBase instead from ModelBase
- I am writting my own ChildAwareModelBase
- I am writting my own thing with parent-child-relations for validations to propagate/trigger the parents validation
-- This was an idea some long time ago because ChildAwareModelBase is too costly
-- The site effect would be to manually connect/register the child properties with the parent
-- But I do not have any fancy ideas to make this pratical for now

**Comment by GeertvanHorrik** [comment]
> The beta went too fast to release - only two weeks instead of four as you told - so this will be the first ticket of many more. Sry, we could not have get planed it earlier.

Yes, it's always an issue. People don't like to use stuff that's alpha, but we had to move on for our components and apps needed a stable release in July. Since we heavily tested it in our apps (and Catel is now smaller so we can create releases faster) we decided to decrease the time for beta.

**Comment by GeertvanHorrik** [comment]
The reason we moved this logic into separate classes is to make them easier maintainable and have a smaller (memory & performance) footprint.

For now I think 1 or 2 are the best options. You normally only need parent/child relations when you want validation as well. It is a breaking change but I don't think a lot of people use the ChildAwareModelBase to be honest (we even considered completely removing it).

**Comment by DanielKuehner** [comment]
> Yes, it's always an issue. People don't like to use stuff that's alpha, but we had to move on for our components and apps needed a stable release in July. Since we heavily tested it in our apps (and Catel is now smaller so we can create releases faster) we decided to decrease the time for beta.

I did not have the time or better I did rely on your words. Never mind - we have to work it off now.

**Comment by DanielKuehner** [comment]
> For now I think 1 or 2 are the best options. You normally only need parent/child relations when you want validation as well. It is a breaking change but I don't think a lot of people use the ChildAwareModelBase to be honest (we even considered completely removing it).

I thought about it and I am of the optinion that I will get rid off ChildAwareModelBase because it is too heavy and generic.

So this would be my path:
1. One of two which will be a temporary state for me:
1.1. If we change Catel than Derive ChildAwareModelBase from ValidatableModelBase to not pollute ValidatableModelBase and we can just remove ChildAwareModelBase in the future
1.2. If we do not change Catel I will write my ChildAwareModelBase to integrate with my code
2. I will write my own parent/child relations code to work with validations. Perhaps and if you want it I can try to integrate this into Catel otherwise it will stay at my code.
3. After this ChildAwareModelBase can be removed.

What do you think about this? But "2." will not be done before autumn or so therefore not in the next time.

**Comment by GeertvanHorrik** [comment]
If we remove it, it will be for 6.0 anyway, so if we do 1 for 5.1, then the rest can wait for 6.0 (end of the year / next year).

**Comment by DanielKuehner** [comment]
So what can I do know? Because I do not know anymore for what "1" stands in the end?
Here are the choices (one more to avoid breaking change):
A. Derive ChildAwareModelBase from ValidatableModelBase (breaking change!)
B. Integreate ChildAwareModelBase into ValidatableModelBase
C. Create new class ValidatableChildAwareModelBase and derive from ValidatableModelBase

Then I will create a pull request.

**Comment by GeertvanHorrik** [comment]
A is "fairly safe". I know it's a breaking change, but we can do things formally and you'll have to wait for a year or we can "cheat". Again, not a lot of people use ChildAwareModelBase so I am happy to make that change.

**Comment by DanielKuehner** [comment]
Done. Or should I already add some ObsoleteEx at this point of time?

**Comment by GeertvanHorrik** [comment]
Nah, we can leave it as-is for now.

**Comment by DanielKuehner** [comment]
Ok.
