### ISSUE TITLE
Make IDataErrorInfo/IDataWarningInfo methods customizable in ValidatableModelBase - again

### ISSUE THREAD

**Issue by DanielKuehner** [Catel/Catel#1084]
As with https://catelproject.atlassian.net/browse/CTL-479 I needed to customize the error message because you only provided the first error instead of all. I did could override the methods to append all errors to one string separated with a new line. But now you have moved the methods to the IValidatableExtensions so I cannot override them anymore as in Catel v4.5.4. This breaks a mayor feature: showing all errors to the user with the standard .NET interfaces.

You can start here with the four functions: https://github.com/Catel/Catel/blob/4.5.4/src/Catel.Core/Catel.Core.Shared/Data/ModelBase.validation.cs#L1137

How can I get back the old behavior respectively the old customizability?

**Comment by DanielKuehner** [comment]
See https://github.com/Catel/Catel/commit/b201a8ee12c440113a40680cb9ce232932b8e110

**Comment by DanielKuehner** [comment]
At the moment I would suggest moving the four methods back to the ValidatableModelBase?

**Comment by GeertvanHorrik** [comment]
I double checked and indeed see that you cannot override the IDataErrorInfo since that's implemented explicitly. I will review this PR soon.

**Comment by DanielKuehner** [comment]
I thought I could this do (see https://catelproject.atlassian.net/browse/CTL-479) but than I would have to copy/hack and maintain your code inside of my override. That is not really a solution.

So to keep the logic at your side the methods allow people to customize the returned string.
