### ISSUE TITLE
Issues with FastObservableCollection especially with SuspensionMode.Mixed

### ISSUE THREAD

**Issue by DanielKuehner** [Catel/Catel#1088]
In this ticket I will address some issues which I have found while inspecting the changes made to FastObservableCollection (FOC) from Catel v4.5.4 to v5.0.0. These are on the one hand optimizations and on the other hand bugs. I will extend the list when I find other things and I will also provide a repo with the changes and unit tests.

### Optimizations

1. Some SuspensionMode.Mixed code is runned while SuspensionMode.None which is unnecessary
2. FOC and NotifyRangedCollectionChangedEventArgs have some unused methods

### (Possible) Bugs

1. SuspensionMode.Mixed: There are cases where the event args are wrong
2. SuspensionMode.None: Does not fire event for moving items (old/new is empty)
3. SuspensionMode.Mixed: Fires incorrect event(s) for moving items
4. SuspensionMode.Mixed: Discards events in special cases

**Comment by DanielKuehner** [comment]
This commit removes unnused methods introduced in #1066.

**Comment by DanielKuehner** [comment]
This commits normalized the usage of field _suspensionContext which was sometimes copied to a local variable and sometimes not.

**Comment by DanielKuehner** [comment]
This commits excludes SuspensionMode.None from remembering old and new items/indices because they are not passed to the event args.

**But** I have changed one minimal behaviour: if only the same items were added and removed the FOC will still fire an reset event. Imho the reduction of processed code for SuspensionMode.None is higher than one special case. So all code changed by this commit is just for this special case - an overhead in my opinion.

Do you agree? @GeertvanHorrik

**Comment by DanielKuehner** [comment]
This commit fixes one missed spot for above thing and adds two unit tests for clearing the collection.

**Comment by DanielKuehner** [comment]
This commit simplifies the reading of the code for the special behaviour for SuspensionMode.Mixed.

**Comment by DanielKuehner** [comment]
This commit adds two unit tests:
1. First based on the New-/OldItems => succeeds
2. Second based on the Indices => fails

The idea behind this is that you have a collection class "target" which contains a second sub collection "source". The target collections adds a collection changed handler on the source collection. With every fired event the target collection synchronizes itself with the source collection. Being basing upon only the items, this is to simple because of movements within the collection or inserts at a concrete index. So the correct way is to use the indices. And this fails.

The failing unit tests starts with a source collection of { 1, 2, 3, 4, 5 }, adds and removes some items and ends up with { 1, 2, 6, 7, 3 }. Now the target collection tries to synchronize itselfs but it fails with { 1, 2, 5, 7, 6 }. And it fails double with not having the correct items and even being at the right position.

Maybe I have something wrong in mind, maybe the unit test is not correct implemented or maybe I am expecting another behaviour as you have inteded.
**But** this is a real work use case. We have different collection classes with a sub collection which have to be synchronized.
**And** this is the reason I always sneaked out of this topic and postponed it - no offence

**Comment by alexfdezsauco** [comment]
I will take a look into this tomorrow.

**Comment by DanielKuehner** [comment]
This commit adds unit tests for SuspensionMode.None while moving items.

> But I have changed one minimal behaviour: if only the same items were added and removed the FOC will still fire an reset event. Imho the reduction of processed code for SuspensionMode.None is higher than one special case. So all code changed by this commit is just for this special case - an overhead in my opinion.

So I must revise my opinion: I have found a general case wit moving items which must fire an event although in the end no item were added or removed.

**Comment by DanielKuehner** [comment]
This commit adds addtional failing tests for SuspensionMode.Mixed for moving items.

The first tries to synchronize the collection but failes.

The second expects the correct event counts and actions. In my opinion this should be a single reset event. But for now you get first an add than an remove. Which might be wrong. Switching the creation of the event args to create first the remove and than the add event args might break so much more...

**Comment by DanielKuehner** [comment]
Yeah, I made one big mistake with the moving unit tests because I have mixed up .Move and the simulated moving with .Remove and .Insert. I will fix this. But I think an old bug of mine will come up oO

**Comment by DanielKuehner** [comment]
I have splitted the move unit tests into real move and simulated move with add/remove - they all fail.
The thing with .Move is not an old bug of mine. Perhaps we have to split up .Move in SuspensionMode.Mixed ... let me think about it. Netherless for .Move it should fire at least one reset event.

**Comment by DanielKuehner** [comment]
This commit fixes the case for SuspendingMode.Mixed to raise one single reset event for .Move.
This also simplifies NotifyChanges in general - based on the fact that New-/OldItems are empty for SuspendingMode.None.
Hint: NotifyChanges is only called if the collection is changed. For this it is now always created a reset event if New-/OldItems is empty.

**Comment by DanielKuehner** [comment]
Ok, I will stop working on this now.

Can you please review the made changes?
I still have no idea how to correctly implement the mixed mode. You? What will we do now with the mixed mode?

Shall I create a pull request?

**Comment by alexfdezsauco** [comment]
I think, I found a better approach. 

@DanielKühner your synchronization scenario tests just give me a better idea about how deal with this. 

The solution is about keep the list immutable if SuspensionContext.Mode is Mixed and wait at the end in order to execute the synchronization.

Just like a command's queue. 

The solution and tests will be available at the feature/1088 branch this morning also including modifications at FastBindingList

**Comment by DanielKuehner** [comment]
Great, I am looking foreward to see your new appraoch!

But yes, the queue idea was also my initial idea last year but I was afraid of doing this.
Primary because imho you have to keep a combined list and cannot split it afterwards into old and new items - you do not know which item to "execute" first and so on.
Except we could introduce another event args derivation which holds this combined list?
This would be possible as the action would be Reset and nobody would expect the old/new items attributes to have any value.
I would also give this a try ... but I will wait until your @alexfdezsauco approach, ok?

I hope all my other changes are okay and can be taken over.

**Comment by GeertvanHorrik** [comment]
@DanielKuehner is this the only issue left that's blocking the 5.x upgrade?

**Comment by DanielKuehner** [comment]
@GeertvanHorrik as I am not working with the Mixed mode this is not blocking me. But it would be nice if the changes I have made here concerning SuspensionMode.None would make it into v5.1 because imho the current state produces a little overhead to the previous implementation.

For now I am fully upgraded to v5.0 in a test branch. Next step is to get the new benefits working (i.e. moving some models to ModelBase instead of ChildAwareModelBase) and finally in one week our test manager is back and will perform our performance tests. Then I will fully see what happend to our application.

**Comment by DanielKuehner** [comment]
I hope you like it and accept the pull request. I am looking forward to this.
