### ISSUE TITLE
Command.Execute does not forward aysnc exceptions

### ISSUE THREAD

**Issue by DanielKuehner** [Catel/Catel#1093]
### Steps to reproduce

1. Create a command with an Execute method that just throws an exception
`new Command(() => { throw new Exception(); }, () => true);`
2. Execute that command
3. No exception is thrown or is catchable

Platform: Windows 7 x64
.NET version: 4.6

### Expected behaviour

The exception should be thrown so either the application crashes or I can catch it.

### Actual behaviour

With Catel v4.5.4 the exception was thrown and was chatchable.
But wit v5. and with ExecuteAsync the exception is "absorbed".

---

I am not really familiar with async relative to the standard behaviour to be expected - or what Catel wants to do in such cases. But with the current behaviour even Visual Studio does not show me the exception. Thus it work will get very hard while programming new features that way. So I expect that exceptions are thrown and are not absorbed like when using "using".

I will provide some unit tests to show the expected behaviour. Perhaps I can also "fix" this issue if it is not against Catel way if using async.

**Comment by GeertvanHorrik** [comment]
I thought we actually changed the behavior (so they can be caught now). Will look into this.

**Comment by DanielKuehner** [comment]
I do not know why anymore but I had an unit test for exact this behaviour and now the unit test fails.

I think this may be caused upon the WeakFunc.Execute method. There the DynamicInvoke absorbs the exception. If you try catch it as TargetInvocationException than you can rethrow it with its InnerExcpetion. But than inside the ExecuteAsync Method you also have to rethrow it. Than in Execute you have to .Wait() and also have a try catch ... so far as I believe it ^^ but that is really ugly. So I am really unsure if this is correct.

**Comment by DanielKuehner** [comment]
But with v4.5.4 I was already able to catch themt! Why changing?

**Comment by DanielKuehner** [comment]
uh ... the over stuff was to much. I will provide the PR.

**Comment by DanielKuehner** [comment]
Done. Can you please check if the modifications of WeakFunc may not have other side effects?
