### ISSUE TITLE
Introduce new MixedBash mode for FastObservableCollection

### ISSUE THREAD

**Issue by DanielKuehner** [Catel/Catel#1095]
### Feature description

Instead of raising one single Reset event in Mixed mode introduce the new mode MixedBash which populates multiply "ranged" Add and Remove events as the following example demonstrates:
`using (list.SuspendChangeNotifications(SuspensionMode.MixedBash))`
`    {`
`        list.Add(1)`
`        list.Add(2)`
`        list.Add(3)`
`        list.Remove(3)`
`        list.Remove(2)`
`        list.Add(2)`
`    }`

Will raise these events:
1. Add; NewItems = {1,2,3}
2. Action = Remove; OldItems = {3,2}
3. Action = Add; NewItems = {2}

**Comment by DanielKuehner** [comment]
Some implementation details dicussed with @GeertvanHorrik and @alexfdezsauco:
- This mode does not collect any more data or does process data while the suspension is active
- When the suspension is ended the collected data of the Mixed mode are used to produce the new events
- This post processing is placed within an extension

**Comment by DanielKuehner** [comment]
Chat discussion starts here: https://gitter.im/Catel/Catel?at=59919e82bc46472974802f9d

**Comment by DanielKuehner** [comment]
Ok, this was a fast one and everything worked as expected :-)

As I have merged from PR 1092 I am afraid to push my code to my branch.

@GeertvanHorrik 
Or can I push it to my brunch and create a PR that will be ok than?
Or should I wait and rebranch from catel:develop after the PR 1092 is accepted?

**Comment by GeertvanHorrik** [comment]
I would wait. Is #1092 ready?

**Comment by DanielKuehner** [comment]
Yes, you both can review it.

Am 14.08.2017 7:34 nachm. schrieb "Geert van Horrik" <
notifications@github.com>:

I would wait. Is #1092 <https://github.com/Catel/Catel/pull/1092> ready?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Catel/Catel/issues/1095#issuecomment-322255632>, or mute
the thread

**Comment by DanielKuehner** [comment]
@GeertvanHorrik  and @alexfdezsauco you can start reviewing it.
