### ISSUE TITLE
Documentation problems with links

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1102]
In generel the documentation has problems related to "Up Next" sections. An example is this one:

Actual link -> not working:
[http://docs.catelproject.com/5.0/getting-started/wpf/creating-the-project/creating-the-models.htm](http://docs.catelproject.com/5.0/getting-started/wpf/creating-the-project/creating-the-models.htm)

The correct link I believe
[http://docs.catelproject.com/5.0/getting-started/wpf/creating-the-models/](http://docs.catelproject.com/5.0/getting-started/wpf/creating-the-models/)

**Comment by GeertvanHorrik** [comment]
Fixed, thanks for reporting.
