### ISSUE TITLE
Unit test fails for SuspensionMode.Mixed

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1105]
This is the unit test (located in ChangeNotificationWrapperFacts::TheCollectionChangesLogic::HandlesCollectionChangesCorrectlyInSuspesionModeMixed)

```
public void HandlesCollectionChangesCorrectlyInSuspensionModeMixed()
{
    var collection = new FastObservableCollection<TestModel>();
    var wrapper = new ChangeNotificationWrapper(collection);

    var itemsReset = false;
    var itemsAdded = false;
    var itemsRemoved = false;

    var model = new TestModel();
    collection.Add(model);

    wrapper.CollectionChanged += (sender, e) =>
    {
        if (e.OldItems != null)
        {
            itemsRemoved = true;
        }

        if (e.Action == NotifyCollectionChangedAction.Reset)
        {
            itemsReset = true;
        }

        if (e.NewItems != null)
        {
            itemsAdded = true;
        }
    };

    using (collection.SuspendChangeNotifications(SuspensionMode.Mixed))
    {
        ((ICollection<TestModel>)collection).ReplaceRange(new [] { new TestModel() });
    }

    Assert.IsTrue(itemsAdded);
    Assert.IsTrue(itemsRemoved);
    Assert.IsFalse(itemsReset);
}
```

Actual values:

- itemsAdded = false
- itemsRemoved = false
- itemsReset = true

So is the test wrong or the code wrong?

**Comment by GeertvanHorrik** [comment]
Pinging @DanielKuehner & @alexfdezsauco

**Comment by DanielKuehner** [comment]
Uh, I have missed that unit test: the test is wrong expecting the old Mixed mode which is now MixedConsolidate.

Now this happens with the three mixed modes:
- Mixed: Reset
- MixedBash: Remove, Add
- MixedConsolidate: Remove, Add - I believe

Just adapt the test to one of three.

**Comment by GeertvanHorrik** [comment]
@alexfdezsauco can you fix this?

**Comment by alexfdezsauco** [comment]
Looks like a wrong implementation of the test in mixed mode. The expected
result is for SuspensionMode.MixedConsolidate
