### ISSUE TITLE
IDataErrorInfo model validation on view models are not mapped at the right time

### ISSUE THREAD

**Issue by lipchev** [Catel/Catel#1108]
There seems to be an error with the validation of a model implementing IDataErrorInfo between version 4.5.4 and 5.0. I have created a simple example demonstrating the issue.

### Steps to reproduce

1. Create model with IDataErrorInfo
2. Create a view model exposing the model using [Model] and [ViewModelToModel] attributes
3. Create a view with a InfoBarMessageControl & CreateWarningAndErrorValidatorForViewModel
4. Bindings ValidatesOnDataErrors=True, NotifyOnValidationError=True, UpdateSourceTrigger=PropertyChanged 

Platform:
.NET version:
4.5

### Expected behaviour

Validation on the model occurs after the property has been updated.

### Actual behaviour

Validation is performed before the new value is updated 

![image](https://user-images.githubusercontent.com/5253184/29468064-0e6352d6-8443-11e7-8534-52f69fc7cdea.png)
[ValidationTest.zip](https://github.com/Catel/Catel/files/1234980/ValidationTest.zip)

**Comment by lipchev** [comment]
Ok I had the line that fixes the problem in the posted example commented out without realizing it: AutomaticallyValidateOnPropertyChanged = false;
What is the expected behavior when updating a model property with this option set? If validation is performed inside the view model I guess it wouldn't matter as the property is already set (although not on the model itself)- but otherwise shouldn't the first validation be skipped for model properties?

**Comment by GeertvanHorrik** [comment]
We changed the default value of `SuspendValidationUntilFirstSave` to `true` instead of `false` for Catel 5.0. Probably that's what's hitting you?

**Comment by lipchev** [comment]
Yes I saw that- but no- I had it enabled both times- and maybe it isn't clear from the single screenshot but if I were to continue typing in the validation error would disappear (after the second keystroke validates with the previous value- i.e. '1')- and you can see from the log that it validates before updating the model property- contrary to what the previous version did.

**Comment by GeertvanHorrik** [comment]
Thanks for providing both the repro + detailed explanation. We were able to address this issue for 5.2
