### ISSUE TITLE
Error when Implementing IDatawindow interface with Radwindow

### ISSUE THREAD

**Issue by halbustami** [Catel/Catel#1109]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Follow the documentation listed in http://docs.catelproject.com/vnext/catel-mvvm/views/xaml/external-controls/using-custom-window/
2. Attempt to use UIVisualizerService to show a window

Platform:
.NET version: 4.6.1

### Expected behaviour
No exception should occur. Review https://stackoverflow.com/questions/45765561/radwindow-after-catel-update-to-5-0 for full stack trace exception

### Actual behaviour
Error probably due to weak event listener

**Comment by GeertvanHorrik** [comment]
Thanks for reporting @halbustami ! Can you create a small repro (without 3rd party libs!) so we can easily take a look at the issue?

**Comment by halbustami** [comment]
I'll get one out to you this weekend.

**Comment by halbustami** [comment]
Geert, I'm attaching the zip but you'll notice that this thing will not error out. I attempted to recreate the issue from a brand new project and it worked. So now I guess I'm sort of clueless as to why such an error occurred in my app. The attached project resembles how my app work except that I am using the bootstrapper from Orchestra where the shell is created without a startup uri but I don't think this will make a difference. 
[WPFApplication1.zip](https://github.com/Catel/Catel/files/1253819/WPFApplication1.zip)

**Comment by advapiIT** [comment]
@halbustami can I share with you on gitter some issues with Catel & Telerik? (excuse me if I junked the post)

**Comment by halbustami** [comment]
Geert,

I'm aware that what I attached was a working example actually. I posted this so it can be used by others. I actually reverted back to Catel 4.5.1 for now until all issue with version 5 are ironed out then you'll probably be hearing from me again.

I've been working on a shell app with visual studio look alike control from Telerik. I borrowed heavily from Orchestra and am using Catel as the base for just about everything. 

I am having major pains trying to get validation to work so I may actually require some help. How can we go about doing that?

**Comment by halbustami** [comment]
advapiIT , yes you may share with me.

**Comment by advapiIT** [comment]
can you please contact me at paolo[ . ] ponzano [ @ ] gmail [.] com

**Comment by GeertvanHorrik** [comment]
@halbustami if the bugs are reproducible, you can post them in the issue tracker. Otherwise please contact us via the contact form on the official website. But again, private support is not for free.

**Comment by GeertvanHorrik** [comment]
@halbustami are you able to reproduce this? Or maybe the help of @advapiIT was sufficient to fix it? I'll close the ticket for now, feel free to re-open if it hasn't been solved yet.
