### ISSUE TITLE
Problems debugging Catel

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1110]
Hi.

I want to step into code/debug Catel using Nuget packages but can't seem to get it working. I have followed the description in the documention. Could it be broken?

[http://docs.catelproject.com/5.0/setup-deployment/stepping-through-the-code/](http://docs.catelproject.com/5.0/setup-deployment/stepping-through-the-code/l)

I am using newest version 5.0.0

**Comment by GeertvanHorrik** [comment]
I think this should be fixed with the latest version. Feel free to re-open if this is not the case.
