### ISSUE TITLE
ChildAwareModelBase should revalidate when child validation changes

### ISSUE THREAD

**Issue by DanielKuehner** [Catel/Catel#1114]
### Steps to reproduce

1. Have "parent" class derrived from ChildAwareModelBase which has a reference/property to a "child" class derrived from ValidatableModelBase
2. Child model gets validated after property change and creates business/field error 
3. Parent model does not get validated

Platform: Win7 x64
.NET version: 4.6.1

### Expected behaviour

The parent model should get validated too to be able to process the child model errors.

### Actual behaviour

With Catel v4.5.4 the parent model does got validated but with v5.1 not anymore.

----

Our QM just found it. I will provide more information and unit tests until next week.
But perhaps you have already any idea what went wrong while dividing the model base class.

**Comment by GeertvanHorrik** [comment]
Out of my head, the parent is responsible for re-spawning the validation if a child gets invalidated. Once you have (failing) unit tests, this should easily be fixed (just a call to Validate(true) in the ChildAwareModelBase when a child model changes / gets validated).

**Comment by DanielKuehner** [comment]
Delayed until end of week or next week.

**Comment by DanielKuehner** [comment]
I am starting now. Out of my head how the code and the old code looked: I cannot remember the parent triggering it's own validation on child model changes. But I will now start to look into v4.5.4 how it worked there and what other call stacks are now in v5.1.

**Comment by DanielKuehner** [comment]
I have attached a simple repo to demonstrate the differences.
This is the simple code:
```
var c = new ChildViewModel();
var p = new ParentViewModel();
p.Child = c;
c.Name = string.Empty;
c.Name = "Funny";
```
And this happens:
```
This is Catel v4.5.4

Action: Created child
Child errors: No errors
[CatelIssue1114_v1.zip](https://github.com/Catel/Catel/files/1270019/CatelIssue1114_v1.zip)

-------------------------------------
Action: Created parent
Parent errors: No errors
-------------------------------------
Action: Attached child to parent
Child errors: No errors
Parent errors: No errors
-------------------------------------
Action: Set childs name to string.Empty
Child errors: Found the following errors in 'ChildViewModel'
* F: There is no name
* B: There is no name
Parent errors: Found the following errors in 'ParentViewModel'
* Found the following errors in 'ChildViewModel'
* F: There is no name
* B: There is no name
-------------------------------------
Action: Set childs name to funny
Child errors: No errors
Parent errors: No errors
-------------------------------------
```
And now it is:
```
This is Catel v5.1.0

Action: Created child
Child errors: No errors
-------------------------------------
Action: Created parent
Parent errors: No errors
-------------------------------------
Action: Attached child to parent
Child errors: No errors
Parent errors: No errors
-------------------------------------
Action: Set childs name to string.Empty
Child errors: Found the following errors in 'ChildViewModel'
* F: There is no name
* B: There is no name
Parent errors: No errors <--- That is wrong!!! 
-------------------------------------
Action: Set childs name to funny
Child errors: No errors
Parent errors: No errors
-------------------------------------
```

**Comment by DanielKuehner** [comment]
No I will investigate the stacks what is different here.

**Comment by DanielKuehner** [comment]
https://github.com/Catel/Catel/commit/b201a8ee12c440113a40680cb9ce232932b8e110#diff-6d3d646b5f3e961cfe6385e09af41605L1053

This is the line which in v4.5.4 lets the parent validate itself, in v5.1.0 this isn't anymore.

**Comment by GeertvanHorrik** [comment]
Thanks for the research. In this case we could override the OnPropertyChanged or RaisePropertyChanged in the ValidatableModelBase and still kick in the validation. The only thing we need to figure out is how to make sure we aren't calling it too often (e.g. while we are in validation, we should skip triggering yet another validation).

**Comment by DanielKuehner** [comment]
You did and this is the problem trying to solve it this way. Give me some minutes, than I will explain.

**Comment by DanielKuehner** [comment]
In v4.5.4 `Validate()` got called through [SetDirtyAndAutomaticallyValidate()](https://github.com/Catel/Catel/blob/4.5.4/src/Catel.Core/Catel.Core.Shared/Data/ModelBase.cs#L1073) - but it always got called.

With v5.1.0 `Validate()` gets called through [OnPropertyChanged](https://github.com/Catel/Catel/blob/develop/src/Catel.Core/Catel.Core.Shared/Data/ValidatableModelBase.cs#L490) - but this is only triggered through [base.RaisePropertyChanged(this, eventArgs);](https://github.com/Catel/Catel/blob/5.1.0/src/Catel.Core/Catel.Core.Shared/Data/ModelBase.cs#L481) which depends on [if (ReferenceEquals(this, sender))](https://github.com/Catel/Catel/blob/5.1.0/src/Catel.Core/Catel.Core.Shared/Data/ModelBase.cs#L440). But in this case `this` is the parent and `sender` is the child. So the chain never gets triggered.

**Comment by DanielKuehner** [comment]
Just one side note. I have overridden the `OnPropertyObjectPropertyChanged` in the parent view model and printed the property names. This it how it looks when setting `c.Name = string.Empty`:

```
This is Catel v4.5.4

P: prop changed - 'Shared.ChildViewModel' with 'Name'
P: prop changed - 'Shared.ChildViewModel' with 'IsDirty'
P: prop changed - 'Shared.ChildViewModel' with 'NameProperty'
P: prop changed - 'Shared.ChildViewModel' with 'IDataErrorInfo.Error'
P: prop changed - 'Shared.ChildViewModel' with 'INotifyDataErrorInfo.HasErrors'
```
```
This is Catel v5.1.0

P: prop changed - 'Shared.ChildViewModel' with 'Name'
P: prop changed - 'Shared.ChildViewModel' with 'NameProperty'
P: prop changed - 'Shared.ChildViewModel' with 'IDataErrorInfo.Error'
P: prop changed - 'Shared.ChildViewModel' with 'HasErrors'
P: prop changed - 'Shared.ChildViewModel' with 'HasErrors'
P: prop changed - 'Shared.ChildViewModel' with 'IsDirty'
```

**Comment by DanielKuehner** [comment]
I will now create the unit tests and provide them to you through a pull request.

**Comment by DanielKuehner** [comment]
@GeertvanHorrik shall I create a pull request or is this ok so?

I would like to fix this issue but at the moment I do not have any idea for this. If you one I would try to fix it according to your suggestion.

**Comment by DanielKuehner** [comment]
What do you think about this: moving the code from `ValidatableModelBase.OnPropertyChanged` to `ValidatableModelBase.RaisePropertyChanged`?

I will at least try this.

**Comment by DanielKuehner** [comment]
I did something: I have tried to call `Validate()` in the same cases as in v4.5.4.

I am really unsure about it. I do not like it. I do not know what this may cause (all unit tests succeed). I do not know how to name the new boolean return value. I do not know how someone else would interpret and work with the return value. But it tries to aim to old way.

Take it as an idea. Take it as a way perhaps not to go ;-)
Because I think now `Validate()` gets called less times - but maybe as often as in v4.5.4.

Have a nice weekend, until next week.

**Comment by DanielKuehner** [comment]
> With v5.1.0 Validate() gets called through OnPropertyChanged - but this is only triggered through base.RaisePropertyChanged(this, eventArgs); which depends on if (ReferenceEquals(this, sender)). And in this case this is the parent and sender is the child. So the chain never gets triggered.

I think this is the reason why I think with v5.1.0 `Validate()` might get called more often because it is called through `OnPropertyChanged` called through the other calls to `base.RaisePropertyChanged(...)`.

**Comment by GeertvanHorrik** [comment]
Thanks for the investigation. It provides some points that we can use to fix this. I can use the repro, maybe we can even convert it into unit tests.

**Comment by DanielKuehner** [comment]
You'r welcome. Sure, use it and if I can help, let me know. I am really interested in your solution. And we really need this feature back to work.

**Comment by GeertvanHorrik** [comment]
I just investigated this and converted your repro into a unit test. Now it all seems green.

**Comment by GeertvanHorrik** [comment]
Please check whether this fix works for you. See https://github.com/Catel/Catel/commit/44955fd3101122bd2f63872b09fe43b1ed062a7d for the details of the commit.

**Comment by DanielKuehner** [comment]
I'am back from some days off of office. Thank you, I will check this until end of week.

**Comment by DanielKuehner** [comment]
Looks pretty good. But I have to extend the unit tests to check if it covers also the two other cases with collection change and collection item property change.

**Comment by DanielKuehner** [comment]
The both do not work. I will try to adapt the fix - perhaps I have a solution.

**Comment by DanielKuehner** [comment]
@GeertvanHorrik what do you think about these changes? Feel free to use all of it if you accept it.

**Comment by DanielKuehner** [comment]
Please ignore the last three commits as they belong to a custom Catel build of mine with only this fix.

**Comment by GeertvanHorrik** [comment]
Will investigate now.

**Comment by GeertvanHorrik** [comment]
Done. going to release a prerelease now, please test Build - 5.2.0-unstable.37.

**Comment by DanielKuehner** [comment]
You will get a feedback within a week, see Gitter.

**Comment by DanielKuehner** [comment]
Our QM is back and found two more issues. It will take me much time to identify the concrete problems at our side and to create failing unit tests. The data structures are very complex but the business errors are not propagated to the parents any more.

I am starting to believe that the breakup into this two classes is the main problem of all because you are not able to reimplement the old behaviour with class derivation.

**Comment by DanielKuehner** [comment]
First results: The issues were made by me but get fixed. Now afterwards new ones came up:
1. Parents are not getting validated after child created new errors - no properties were changed in the child
2. UI is not up to date concerning business errors. Selecting the item forces validation and error is shown.

What I think at the moment:
1. As you now filter error property changes to not trigger `Validate()` this is another behaviour than to v4.5.4 and causes the issue
2. When the error properties change, `_isValidated` gets `false`. So when the UI ask for a value but now the validation gets triggered through `EnsureValidationIsUpToDate()`

So 2. is a consecutive fault for me.

**Comment by DanielKuehner** [comment]
Ok, it as wired as I a bucket full of worms ... or what ever.

After all I think I was totally fooled for "years" by the UI which triggered through `HasError` my validation so all them time all seems to be working. But now not anymore. Perhaps Catel v5.x really changed something but only showed up this missbehaviour or one of the DevExpress updates. In the end only the selected items were validated and before all shown. And only in the model chain one model is the one causing the problems.

To summerize it up:
- I am off the opinion that the current Catel code base is correct
- I believe we based our validations upon the UI triggering so we thought it was correct - what in the end only was an illusion

Thank you, you can close the ticket. Sry, for the confusions und wrong blamings - I still do not know where to look and how to fix this. I think will require a complete recoding lasting many many days ... hurray!

**Comment by GeertvanHorrik** [comment]
Thanks for the detailed explanation. I'll close this ticket and we can always re-open / create a new one if new issues arise.
