### ISSUE TITLE
ViewModelManager holds empty List<object> for closed ViewModel

### ISSUE THREAD

**Issue by GreenKn1ght** [Catel/Catel#1115]
### Steps to reproduce

1. Create ViewModel derrived from Catel.MVVM.ViewModelBase.
2. Close this ViewModel.
3. Check ViewModelManager._viewModelModels.

Platform: WPF
.NET version: 4.5.2

### Expected behaviour

When ViewModel closed, this list should be removed. Seems like ViewModelManager.UnregisterAllModels() is good place for it.

### Actual behaviour

ViewModelManager holds empty List<object> for every closed ViewModel even when them was collected by GC.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. Interested in doing a PR?

**Comment by GreenKn1ght** [comment]
Yes, im Interested.
