### ISSUE TITLE
Issue with CloseViewModelAsync on non-ui thread

### ISSUE THREAD

**Issue by ThrasherWork** [Catel/Catel#1116]
### Steps to reproduce

1. Show SubWindow from Window with ShowDialogAsync(viewModel)
2. In SubWindow bind button to TaskCommand (important! Command works fine) 
3. In SubWindow in TaskCommand handler call CloseViewModelAsync(bool)
4. Here we go: SubWindow not closed. And can not be closed, because IsClosed is true and further Closing calls will cause no effect

If CloseViewModelAsync(bool) called with dispatcherService.Invoke(...) everything works fine.

Platform: WPF
.NET version: 4.5

### Expected behaviour
Maybe exception should be thrown when CloseViewModelAsync called from non-ui thread? 
Or maybe Window shold close normally (i prefer this option)?

**Comment by GeertvanHorrik** [comment]
This is expected behavior. Dispatching and awaiting the result could end up in deadlocks, therefore we don't auto-dispatch calls like this.

**Comment by GeertvanHorrik** [comment]
For now we think the best solution is to dispatch from your VM, that's the recommended approach. I am closing this ticket. Feel free to comment or re-open if something is still not working.
