### ISSUE TITLE
Problems using IUIVisualizerService in UWP and Page type

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1117]
I was trying to implement a loginPage as a Page type in UWP, and then Show it using IUIVisualizerService but failed to get it working. The ViewModelLocator resolving is working fine, but the view never poped up. After looking in the code I found out the the view is handled as a ContentDialog in respect to UWP. After changing the LoginPage to a ContentDialog it works but I can't figure out if it has to be a ContentDialog to work or should it be possible to use Page also, by implementing an Interface or similar?

If ContentDialog is needed I think this should be stated in the documentation.

**Comment by GeertvanHorrik** [comment]
You should use UIVisualizerService for windows (content dialogs), and the navigation service for pages.

**Comment by GeertvanHorrik** [comment]
Closing the ticket assuming the answer is sufficient. If not, feel free to re-open.
