### ISSUE TITLE
Navigation in UWP

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1119]
HI. I don't see if there is a bug or just me not getting it right.

### Steps to reproduce

In my ModuleInitializer I try to register two views like this:

```csharp
private static void InitializeNavigation()
{
  var serviceLocator = ServiceLocator.Default;
  var navigationService = serviceLocator.ResolveType<INavigationService>();
  navigationService.Register(typeof(MainViewModel), new Uri("ms-appx:///MainPage.xaml"));
  navigationService.Register(typeof(SecondViewModel), new Uri("ms-appx:///SecondPage.xaml"));
}
```
Platform: UWP
.NET version: Anniversary update
Catel: 5.1.0

### Actual behaviour

I have tried 3 different ways to to navigate from MainPage -> SecondPage like:

1. NavigationService.Navigate(typeof(SecondViewModel)); -> Gives an NullReferenceException
2. NavigationService.Navigate(new Uri("ms-appx:///SecondPage.xaml")); -> Gives an Catel.NotSupportedInPlatformException
3. NavigationService.Navigate(typeof(SecondPage)); -> > Gives an NullReferenceException

Please note that Page is of type Catel.Page and ViewModels inherit from NavigationViewModelBase/ViewModelBase.

I believe that approach 1 should work or am I missing something

**Comment by GeertvanHorrik** [comment]
Note you need to use the view model as navigation target. However, there could be 2 things happening here:

1. Can the VM resolve the View?
2. Make sure the NavigationRootService returns a valid frame:

https://github.com/Catel/Catel/blob/develop/src/Catel.MVVM/Catel.MVVM.Shared/Services/NavigationRootService.xaml.cs

There you can return *any* frame and use that as navigation container. By default Catel searches for the main window and uses the first frame it can find.

**Comment by byrialsen** [comment]
Hi

I got my tiny isolated Navigation Test project to work. The issue for me was that both Views and ViewModels were places in the root of the project just for simple testing. After moving these to folders 'Views' and 'ViewModels' they could be resolved correctly, by the default naming conversion.

In my real project though the situation is more complex and I was planning to use this [API](http://docs.catelproject.com/5.0/catel-mvvm/services/navigation-service/#registering-custom-views) to register a custom view, but I believe this is not available anymore. At least not in UWP? 

Futhermore I have created my own `CustomNavigationRoot` like:

```csharp
public class CustomRootNavigationService : NavigationRootService
    {
        protected override Frame GetApplicationRootFrame()
        {
            return base.GetApplicationRootFrame();
        }

        public override object GetNavigationRoot()
        {
            return base.GetNavigationRoot();
        }
    }
```  
It works and I am able to implement my own logic to GetNavigationRoot, but I was hoping to be able to implement the navigation system a bit like the way MVVMCross and Prism does, where additional regions/frames can be defined and work as NavigationRoot when navigation is called. I was hoping that `GetNavigationRoot` method was able to support such but it has no params so I don't see an obvious way to do it. Is there a trick or is it just not meant to work that way?

**Comment by GeertvanHorrik** [comment]
We probably need to update the docs. The NavigationService uses the ViewLocator to resolve the views. So you can simply register your own stuff in the ViewLocator (and if you want it vice versa, also in the ViewModelLocator).

**Comment by byrialsen** [comment]
Ok thanks :-)

What about navigation in different region/frames. Is it possible or?

**Comment by GeertvanHorrik** [comment]
Docs are updated (so reflect in 15 minutes or so). Yes, you can navigate in different frames, just return the right frame in GetApplicationRootFrame.

**Comment by byrialsen** [comment]
I understand that I can om theory return "any" frames , but does it suit well if I want to have a shell root window with multiple  regions/frames (like main toolbar, sub toolbar, content) and i want to navigate to each of them with different viewmodels/views throughout the lifetime of the application.
I can see that GetNavigationRoot can easily return the main frame but as an example, how should it return the correct MainToolbar frame when it tries to navigate to MainToolbarViewModel. The GetNavigationRoot doesn't know which ViewModel it is navigating to, when called or am I missing something.

**Comment by GeertvanHorrik** [comment]
A navigation should occur when you are moving to a new page. *if* you move to a new page, you have 2 options:

1. This new page also contains the toolbar, etc (where you re-use the toolbars using user controls)
2. You have a subframe and the toolbars automatically adjust to the current state (because they don't need to be recreated on a navigation, they will be re-used).

I would not choose for a solution where I have multiple navigation frames floating around, it would make things too complicated (with or without Catel). It *is* possible, you can register any service again with a different tag in Catel. But again, I wouldn't go there.
