### ISSUE TITLE
SaveFileService & OpenFileService should support Windows file filters in UWP

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1123]
### Steps to reproduce

Call:  _saveFileService.DetermineFileAsync() in a UWP project.

Platform:
UWP 14393 (Anniversary Update)

### Actual behaviour

An exception is raised.

To my investigation it seems like that UWP Control `FileSavePicker` should have set at least one `FileTypeChoices` to work. Like this code:

```csharp
 FileSavePicker savePicker = new FileSavePicker();
 savePicker.FileTypeChoices.Add("Plain Text", new List<string>() { ".txt" });
```

Maybe `OpenFileService` has  similar problems?

**Comment by GeertvanHorrik** [comment]
Yes, `OpenFileService` will probably have the same issues. Thanks for reporting, we'll put it on the release vNext.

**Comment by GeertvanHorrik** [comment]
Can you please create a small repro so we can easily test the fixes?

**Comment by byrialsen** [comment]
Sounds good, and offcourse I will do that. I will try to do it during this weekend.

And let me also say. As this is a very well written piece of framework it was easy to override the `DetermineFileAsync` to temporary handle the problem

```csharp
public async override Task<StorageFile> DetermineFileAsync()
{
  // init
  var saveFileDialog = new FileSavePicker();
  saveFileDialog.SuggestedFileName = FileName;

  // handle FileTypeChoices from Filters like "Log files|*.txt"
  try
  {
     string[] filterParts = Filter.Split(new char[] { '|' }, 2);
     if (filterParts.Length == 2)
     {
       List<string> extensions = new List<string>();
       foreach (string extension in filterParts[1].Split(new char[] { '|' }))
       {
         extensions.Add(extension.TrimStart(new char[] { '*', ' ' }));
       }

       saveFileDialog.FileTypeChoices.Add(filterParts[0], extensions);
     }
  }
  catch (Exception ex)
  {
    log.Debug(ex);
   }
}

**Comment by byrialsen** [comment]
Hope this small sample will help you testing a fix:

[SaveAndOpenFileService.zip](https://github.com/Catel/Catel/files/1346705/SaveAndOpenFileService.zip)

**Comment by GeertvanHorrik** [comment]
The issue was the services need a different way of passing in file filters. We've made the service compatible with full Windows file filters, they will now automatically be converted to UWP file filters.
