### ISSUE TITLE
Error Unit Tests with Catel 5.2

### ISSUE THREAD

**Issue by SergeyIlyin** [Catel/Catel#1128]
I can't test classes that implements ModelBase using net.Framework

Exception:
Сообщение: System.TypeLoadException : Тип "Catel.Data.ModelBase" сборки "Catel.Core, Version=5.2.0.0, Culture=neutral, PublicKeyToken=null" имеет метод "OnDeserialized" с неправильной сигнатурой для атрибута сериализации.
Translated:
Message: System.TypeLoadException: The "Catel.Data.ModelBase" assembly type "Catel.Core, Version = 5.2.0.0, Culture = neutral, PublicKeyToken = null" has the "OnDeserialized" method with an invalid signature for the serialization attribute.

There ara no errors with Catel 5.1
Also no errors if application with catel used netstandard2.0

```
        public class Person : ModelBase
        {   }

        [Fact]
        public void CreateTest()
        {
            var p = new Person();
            Assert.NotNull(p);
        }
```
Or using Catel 5.2,  I must to move Models and ViewModels to  separate dll to testing?

**Comment by GeertvanHorrik** [comment]
I can't recall making any changes to this. Did you change target platforms?

**Comment by SergeyIlyin** [comment]
https://github.com/SergeyIlyin/CatelCoreTest
I created test solution,

**Comment by GeertvanHorrik** [comment]
Thanks, I'll look into this as soon as I can.

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/32043724-def66c2a-ba3b-11e7-969c-326e3edd24d5.png)

**Comment by GeertvanHorrik** [comment]
Also works in release mode.

**Comment by SergeyIlyin** [comment]
I don't undastand any.
![image](https://user-images.githubusercontent.com/10351041/32051729-3b7b23c2-ba6f-11e7-8d79-aa82e3bb8b5a.png)
I created not one test. Maby it is VS 2017 bug?
tested in  VS 2015 15.4.1
I will search more.

**Comment by GeertvanHorrik** [comment]
Weird, I am using VS 2017 (15.4). Make sure to install all updates to windows / .net framework as well.

**Comment by SergeyIlyin** [comment]
Solved on other PC after repair VS. Before repair was only Core52Core.Test succesed.

I think that the reason (first PC) in the cache, where was my build Core5.2 under net.standard
