### ISSUE TITLE
CloseViewModelAsync is closing all opened views

### ISSUE THREAD

**Issue by sarul84** [Catel/Catel#1130]
1. All my views are DataWindow types and view models inherited from viewmodelbase
2. Used UIVisualizer to show window.
3. Auto closing window is opened as modeless window, another view is modal window
4. My application is WPF application (MVVM)
5. Catel framework version : 4.4.0, Windows 7, WPF, VS2013

Platform:
.NET version: 4.5

### Actual behaviour

I opened two views simultaneously from Main Window. One view would be closed automatically after the work done on that view and another view would be used for getting user inputs. The issue here is that the auto closing of one view closes another view as well. I am using CloseViewModelAsync to close view from view model.

This is happening only when I move my focus from application to another application (for example, move focus to visual studio) while the operation is progressing.

The auto closing of first view is not affecting the view in which user works if the user continues to work on the application.

**Comment by GeertvanHorrik** [comment]
Probably the first one is considered the "main window" of the app. As soon as that closes, all windows will close and the app will exit. You can change the shutdown mode of the app manually.

If this is not the case, we need a repro because I can't really extract sufficient info from this report.

**Comment by GeertvanHorrik** [comment]
Closing since we have no repro.
