### ISSUE TITLE
Code snippets are missing some parts

### ISSUE THREAD

**Issue by Loreno10** [Catel/Catel#1132]
I'm just learning Catel and already I noticed that some snippets are wrong. I did a Pull Request for 'model' snippet, because this one was clearly wrong - i was quite surprised since this is probably the most fundamental snippet. 
Since I'm very new to all this I'm adding this Issue, so that some more advanced user could check the snippets. I think that 'vm' is also wrong, but, as I stated, I'm new to everything MVVM, so I didn't really start too look closely into it.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We'll look into the PR soon.

**Comment by GeertvanHorrik** [comment]
Just merged, thanks for fixing. What do you think is wrong about the VM snippet?

**Comment by GeertvanHorrik** [comment]
Closing this ticket. If you have any questions, feel free to re-open.
