### ISSUE TITLE
Add Silent mode to FastObservableCollection<T>

### ISSUE THREAD

**Issue by advapiIT** [Catel/Catel#1133]
It would be great to have the possibility to add some items in a silent mode, so no CollectionChanged event is fired at all. Standing at @DanielKuehner, it would be quite simple

**Comment by DanielKuehner** [comment]
I will do my best!

**Comment by DanielKuehner** [comment]
Short summary what have to be done:
- Add `Silent` as new mode to `SuspensionMode`
- Add new entry to `EventsGeneratorsRegistry` with a method which returns an empty list
- Add unit tests

I hope this will be all to be done.

@GeertvanHorrik you can assign this to me, thanks.

**Comment by GeertvanHorrik** [comment]
Somehow I can't assign tasks to you, probably because you did not raise the ticket / are part of the team.

**Comment by DanielKuehner** [comment]
Funny thing. I will do it anyway :-) The PR will than be assigned to me.

**Comment by DanielKuehner** [comment]
@advapiIT: Here is the requested Catel v4.5.4 adoption of the Silent mode:
https://github.com/DanielKuehner/Catel/tree/feature/1133_v454
