### ISSUE TITLE
Change navigation methods in INavigationService to async

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1145]
Xamarin.Forms requires async methods. I don't see any issues at this point to migrate them to async methods.

**Comment by GreenKn1ght** [comment]
I would like to implement this for 5.11. Perhaps we can avoid breaking changes? For example, we can introduce a new iface to replace the old one.

**Comment by GreenKn1ght** [comment]
Xamarin.Forms navigation via NavigationPage already implements TAP, WPF navigation via Frame implements EAP, which can be easily converted to TAP using TaskCompletionSource. I didn't faced UWP's frame, but looks like it works like WPF's one.

**Comment by GeertvanHorrik** [comment]
@GreenKn1ght correct, UWP is nearly the same as WPF. We can work "without" breaking changes by marking the non-async as obsolete (using ObsoleteEx) and steering people towards the async impleemntations (on the same iface). Then we can remove the non-async from 6.x
