### ISSUE TITLE
Reuse identifiers in UniqueIdentifierHelper

### ISSUE THREAD

**Issue by GreenKn1ght** [Catel/Catel#1146]
### Feature description

Current implementation can lead to overflow problem. I know that int.Max (x2 with negative) is large number, but for 24/7 apps will be better to reuse identifiers of unlinked (dead) instances. 
ViewModelBase uses it in ctor so I cant override it by myself.

I think would be nice to have some generation strategies for UniqueIdentifierHelper with ability to register it for specific types.

**Comment by GeertvanHorrik** [comment]
I am not sure whether re-using is a good idea. What if we migrate to using ulong instead of int?

**Comment by GreenKn1ght** [comment]
For me its looks like semi-solution or even not solution at all. We haven't faced with this problem yet, but due to the fact that the application life time isn't deterministic, it can't be said that the limit won't be reached. And if it happens, we don't even know what kind of behavior to expect.
Since UniqueIdentifierHelper is public, I think its a good idea to improve it.

What are the disadvantages in re-using you see?

**Comment by GeertvanHorrik** [comment]
The idea is to create an ObjectIdGenerator (implementing IObjectIdGenerator) class which will solve #1141 as well. Then we could make it injectable / replaceable.

Re-using will result in the same objects reusing the same unique ids, making them no longer unique. This could be very confusing when going through the logs, etc.

**Comment by GreenKn1ght** [comment]
If the order isn't important, can we use Guid?

**Comment by GreenKn1ght** [comment]
Miss click.

**Comment by GreenKn1ght** [comment]
May be i just make a mountain out of a molehill. Probably ulong "long" enough.

**Comment by GeertvanHorrik** [comment]
Guids will be crap to read, making it much harder to find easy unique identifiers. But again, what if we turn the unique identifier into a string and the user can choose whether to return int, long or guid?

**Comment by GreenKn1ght** [comment]
It make sense.

**Comment by GeertvanHorrik** [comment]
For this to be a non-breaking change, we'll need to introduce a new class name. My suggestion is ObjectIdGenerator (I believe .NET also used this name for once of their own classes, so it makes sense). The only thing I am not sure about yet is whether we should make it static (easy to use, but hard to customize for end-users) or instance (are we going to resolve by interface?).

**Comment by GreenKn1ght** [comment]
If UniqueIdentifierHelper was an instance with interface, I would not even create this issue :)

**Comment by GreenKn1ght** [comment]
But I'm not sure that registering the implementation of this interface at the same time for the Catel-types and user-types is a good solution. Perhaps we should somehow split them.

**Comment by GeertvanHorrik** [comment]
We are planning to implement this for 5.3, and we hope to release that before the end of the month. We will try to look into this ticket soon.
