### ISSUE TITLE
Changes are lost after attempt to close the main window

### ISSUE THREAD

**Issue by GreenKn1ght** [Catel/Catel#1150]
I want to give the user an option to cancel the window closing if there are unsaved changes.

### Necessary conditions ###

Main window is a DataWindow. It has nested UserControl whose VM has registered model.

### Steps to reproduce

1. Start the repro.
2. Change the text.
3. Close the application. It will show you MessageBox. If you press "No", application won't be terminated.

Platform:
.NET version: 4.5.2
Catel 4.5.4, 5.2.0

### Expected behaviour

The user has not lost any changes, so he is very happy :)

### Actual behaviour

Text lost, model uninitialized.

[MyApp.zip](https://github.com/Catel/Catel/files/1647250/MyApp.zip)

**Comment by GeertvanHorrik** [comment]
See http://docs.catelproject.com/vnext/introduction/mvvm/introduction-to-nested-user-controls-problem/ for the explanation of how Catel deals with the nested user controls problem. Especially the section of validation will be interested since you can see the deepest child will be validated first (first validate / cancel / save the children, then go up the chain to each parent). 

1 way to solve this is to not handle this special case in the vm, but in the view (window).

**Comment by GeertvanHorrik** [comment]
Ok, since the DataWindow is the first one subscribing to the event, there is no way to intercept it. Trying a fix now.

**Comment by GeertvanHorrik** [comment]
Note: we won't be fixing this for Catel 4.x, only for 5.x.

**Comment by GreenKn1ght** [comment]
This situation can be avoided by overriding OnClosing() on DataWindow.

**Comment by GeertvanHorrik** [comment]
![catel_1150](https://user-images.githubusercontent.com/1246444/35386206-81763d5a-01cb-11e8-8f51-a6d36bc50116.gif)

**Comment by GeertvanHorrik** [comment]
This requires 3 things:

1. Update to the latest Catel prerelease Build - 5.3.0-unstable.80 (via MyGet)
2. Update MainWindow code
3. Update MainViewModel code

Main window code:

```
public partial class MainWindow
{
	private bool _allowClosing = false;

	public MainWindow()
	{
		InitializeComponent();

		Closing += MainWindow_OnClosing;
	}

	private async void MainWindow_OnClosing(object sender, CancelEventArgs e)
	{
	    if (_allowClosing)
	    {
	        return;
	    }

	    e.Cancel = true;

	    var vm = ViewModel as MainViewModel;
	    if (vm != null)
	    {
	        _allowClosing = await vm.CanCloseApplication();
	        if (_allowClosing)
	        {
	            Dispatcher.BeginInvoke(() => Close());
	        }
	    }
	}
}
```

VM code:

```
public async Task<bool> CanCloseApplication()
{
	var messageResult = await _messageService.ShowAsync("Are you sure you want to exit?", "Alert",
	    MessageButton.OKCancel, MessageImage.Exclamation);
	return await base.CancelAsync() && messageResult == MessageResult.OK;
}
```

**Comment by GeertvanHorrik** [comment]
Since this is only required on the main window of an app, I think this "workaround / fix" is acceptable.

**Comment by GeertvanHorrik** [comment]
Build takes about 10 minutes, can you please let us know whether this fixes your issue?

**Comment by GeertvanHorrik** [comment]
Overriding OnClosing is also a possibility, but would still require dealing with a field and async code (since IMessageService is async).

**Comment by GreenKn1ght** [comment]
Sorry, i can't check new version due we haven't yet migrated to it from 4.5.4. But we already found workaround without any changes in Catel. I will attach updated repro few minutes later.

**Comment by GreenKn1ght** [comment]
Sorry for delay. 
This sample works with both Catel 4.5.4 and 5.2.0.

[MyApp.zip](https://github.com/Catel/Catel/files/1664063/MyApp.zip)

**Comment by GreenKn1ght** [comment]
@GeertvanHorrik I don't know if we need to make any changes to the Catel (sources and/or docs) or not. But I don't need help with this no more so I close it. 
Thanks for your response.

**Comment by GeertvanHorrik** [comment]
Thanks for uploading a working example, much appreciated.
