### ISSUE TITLE
CloseViewModelAsync doesn't seem to work properly

### ISSUE THREAD

**Issue by mgiu** [Catel/Catel#1152]
CloseViewModelAsync seems not to work properly.

### Steps to reproduce
1. In a VM call  'await uiVisualizerService.ShowAsync(viewModel)' OR 'await uiVisualizerService.ShowDialogAsync(viewModel)'
2. In the correspondent VM call 'CloseViewModelAsync(true)' 

The shown window (or modal window) doesn't close.

Platform: VS2017 on Win10
.NET version: 4.7.1 (but also tried with 4.5.2)

### Expected behaviour
I expect the shown window (or modal window) to close.

### Actual behaviour
The window (or modal window) doesn't close. Please note I checked with the debugger and the CloseViewModelAsync is actually called. 
Thanks

**Comment by GeertvanHorrik** [comment]
Can you please upload a small repro so we don't have to set it up?

**Comment by mgiu** [comment]
[Catel-ExampleCloseAsync-CodeOnly.zip](https://github.com/Catel/Catel/files/1667208/Catel-ExampleCloseAsync-CodeOnly.zip)

Is this enough? Thanks

**Comment by GeertvanHorrik** [comment]
Change the base class of `ControlloManualePortale` to `catel:Window` (or `catel:DataWindow`) and it should work fine.

**Comment by mgiu** [comment]
Thanks!
