### ISSUE TITLE
/Catel.Extensions.Controls;component/themes/generic.xaml not available in 5.x

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1161]
Test application created with Catel 5.3, Orc and Orchestra.
StyleHelper.CreateStyleForwardersForDefaultStyles(); called in App.xaml.cs

### Steps to reproduce

1. Create a new app with Catel template
2. Add some textboxes in the mainwindow view
3. Compile and start the App.

Platform:
.NET version: 4.5
WPF
Catel 5.3

### Expected behaviour

the appearence of control as in Catel 4.5 (with margins and paddings)

### Actual behaviour

![2018-02-20_13h54_32](https://user-images.githubusercontent.com/13942501/36424995-96bd5354-1645-11e8-809d-99be8158812d.png)

**Comment by gofrogi** [comment]
i found it out by myself. The new Resource directory is that: "/Orc.Controls;component/Themes/Generic.xaml". It work's!

**Comment by GeertvanHorrik** [comment]
Glad to hear you were able to solve it. Closing the ticket.
