### ISSUE TITLE
Issue with generic.xaml in Catel 5.x

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1162]
I have to come back to issue #1161 
I added this to App.xaml
    <Application.Resources>
      <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
          <ResourceDictionary Source="/Orchestra.Core;component/themes/Generic.xaml" />
        </ResourceDictionary.MergedDictionaries>
      </ResourceDictionary>
    </Application.Resources>

At the beginning it seems to work but not really. Some seconds after interaction with the UI i always get an exception:
"{DependencyProperty.UnsetValue}" the value of Property "Background" is not valid.

   bei System.Windows.DependencyObject.GetEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, RequestFlags requests)
   bei System.Windows.DependencyObject.GetValueEntry(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, RequestFlags requests)
   bei System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   bei System.Windows.Controls.Border.get_Background()
   bei System.Windows.Controls.Border.OnRender(DrawingContext dc)
   bei System.Windows.UIElement.Arrange(Rect finalRect)
   bei System.Windows.ContextLayoutManager.UpdateLayout()
   bei System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   bei System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei System.Windows.Application.Run()
   bei Catel_5_x_Test.App.Main()

This is the snippet of Output:

15:37:08:857 => [DEBUG] [Catel.IoC.TypeFactory] [10] Cleared type constructor cache
15:37:08:861 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'Orc.Controls.TimeSpanPicker', creating style forwarder
15:37:08:862 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'Orc.Controls.DatePicker' with the additional info from the default style definition
15:37:08:863 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'Orc.Controls.AnimatedGif', creating style forwarder
15:37:08:864 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'Orc.Controls.DateTimePicker' with the additional info from the default style definition
15:37:08:865 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.ComboBox' with the additional info from the default style definition
15:37:08:866 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.TextBox', creating style forwarder
15:37:08:867 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.Slider' with the additional info from the default style definition
15:37:08:867 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.TabControl' with the additional info from the default style definition
15:37:08:868 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.CheckBox' with the additional info from the default style definition
15:37:08:868 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.Primitives.ToggleButton', creating style forwarder
15:37:08:869 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.MenuItem', creating style forwarder
15:37:08:869 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.ProgressBar', creating style forwarder
15:37:08:870 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.ListBox', creating style forwarder
15:37:08:870 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.ListView', creating style forwarder
15:37:08:870 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.Button' with the additional info from the default style definition
15:37:08:871 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.Label', creating style forwarder
15:37:08:871 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.DocumentViewer', creating style forwarder
15:37:08:872 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.TextBlock', creating style forwarder
15:37:08:872 => [DEBUG] [Orchestra.StyleHelper] [10] Couldn't find style definition for 'System.Windows.Controls.PasswordBox', creating style forwarder
15:37:08:873 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.RadioButton' with the additional info from the default style definition
15:37:08:873 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.GroupBox' with the additional info from the default style definition
15:37:08:873 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.ComboBox' with the additional info from the default style definition
15:37:08:874 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.TextBox' with the additional info from the default style definition
15:37:08:874 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.Slider' with the additional info from the default style definition
15:37:08:875 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.TabControl' with the additional info from the default style definition
15:37:08:875 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.CheckBox' with the additional info from the default style definition
15:37:08:875 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.Primitives.ToggleButton' with the additional info from the default style definition
15:37:08:876 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.MenuItem' with the additional info from the default style definition
15:37:08:876 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.ProgressBar' with the additional info from the default style definition
15:37:08:876 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.ListBox' with the additional info from the default style definition
15:37:08:877 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.ListView' with the additional info from the default style definition
15:37:08:877 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.Button' with the additional info from the default style definition
15:37:08:877 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.Label' with the additional info from the default style definition
15:37:08:878 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.DocumentViewer' with the additional info from the default style definition
15:37:08:878 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.TextBlock' with the additional info from the default style definition
15:37:08:878 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.PasswordBox' with the additional info from the default style definition
15:37:08:879 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.RadioButton' with the additional info from the default style definition
15:37:08:879 => [DEBUG] [Orchestra.StyleHelper] [10] Completing the style info for 'System.Windows.Controls.GroupBox' with the additional info from the default style definition

**Comment by gofrogi** [comment]
I tried it now including single xaml files and find out, that if as soon the file Controls.implicit.xaml is includen this causes the exception. May be it can help.

**Comment by GeertvanHorrik** [comment]
"{DependencyProperty.UnsetValue}" the value of Property "Background" is not valid. is generated if you don't set an accent color. 

Please specify an accent color in your resource dictionary and all should work fine.

**Comment by gofrogi** [comment]
Is it for UWP Appls or for WPF also. I have no idea how to do it. Can you give a hint?

**Comment by GeertvanHorrik** [comment]
See https://github.com/WildGums/Orchestra/blob/develop/src/Examples/Orchestra.Examples.Ribbon.Fluent/Orchestra.Examples.Ribbon.Fluent.Shared/Themes/Generic.xaml

**Comment by gofrogi** [comment]
Thank you very mutch!
I already looked for there it, but did not find it. :)

**Comment by gofrogi** [comment]
i plased the accent color in Generic.Xaml and linked it in App.xaml as belowe
```
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <!-- application-wide themes-->
        <ResourceDictionary Source="Themes/Generic.xaml" />
        <ResourceDictionary Source="/Orchestra.Core;component/Themes/generic.xaml" />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
</Application>
```
but the exception still flies when i move the mouse pointer over a button.

**Comment by GeertvanHorrik** [comment]
Where is your *accent color* ?

**Comment by gofrogi** [comment]
in Themes/Generic.xaml

**Comment by gofrogi** [comment]
```
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>

  <SolidColorBrush x:Key="AccentColorBrush" Color="#D24726" />
</ResourceDictionary>
```

**Comment by GeertvanHorrik** [comment]
Please use /Themes/Generic.xaml as uri (add / at the start) and remove the orchestraone and try again.

**Comment by gofrogi** [comment]
then the dialog locks like this
![2018-02-22_15h01_00](https://user-images.githubusercontent.com/13942501/36542505-44fc3024-17e1-11e8-946a-83a79f9a581f.png)
but i would like it this way:
![2018-02-22_15h02_00](https://user-images.githubusercontent.com/13942501/36542551-64cb822e-17e1-11e8-947d-ca3e3247f3eb.png)

**Comment by GeertvanHorrik** [comment]
Weird. You are probably not using one of the shells of Orchestra. In that case, you'll need to create the resource dictionaries yourself. See https://github.com/WildGums/Orchestra/blob/develop/src/Orchestra.Shell/Orchestra.Shell.Shared/Services/ApplicationInitializationServiceBase.cs#L23

**Comment by gofrogi** [comment]
i created the app with the template form Catel 5.3
Ok. I will try it this way.

**Comment by gofrogi** [comment]
thank you

**Comment by GeertvanHorrik** [comment]
Catel templates don't use Orchestra. You should try and follow the Orchestra example apps of you wish to use Orchestra (separate project that uses Catel).

**Comment by gofrogi** [comment]
actually i do not want use orchestra, I want only update my application from 4.5 to 5.3. But to use  StyleHelper.CreateStyleForwardersForDefaultStyles(); in my application startup method i have to include Orhcestra. 
The default control styles seams to be moved from Catel to Orchestra. Or i am wrong with this?

**Comment by GeertvanHorrik** [comment]
Correct, we've migrated as much as possible to other libs. Catel was getting too large and won't change much. We wanted to be more agile on some fronts (such as controls) and make them deliverable besides Catel.

**Comment by gofrogi** [comment]
Yes, i can understand it well.
Should i better define my own default styles for controls? 
What do you mean?

**Comment by GeertvanHorrik** [comment]
I think it's best to:

1. Reference orchestra.core
2. Call this code:

```
            ThemeHelper.EnsureApplicationThemes(GetType().Assembly, true);
```

**Comment by gofrogi** [comment]
Yes! This is the rightest and finest solution! It works and don't crash.
Thank you Geert. You are the greatest :)

**Comment by GeertvanHorrik** [comment]
Glad to hear it's fixed :)

**Comment by gofrogi** [comment]
Yes, finally!
