### ISSUE TITLE
catel 5.3: validation by Dataannotation doesn't work anymore

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1163]
### Steps to reproduce
1. that is the model:

public class ValidationTest : ValidatableModelBase
  {    
    public string FirstName { get; set; }
    [Required]
    public string Surname { get; set; }
    public int Age { get; set; }
  }

ViewModel:
 public class MainWindowViewModel : ViewModelBase
  {
    public MainWindowViewModel()
    {
      DeferValidationUntilFirstSaveCall = false;
      ValidationTest = new ValidationTest {Age = 20, FirstName = "John", Surname = "White"};
    }

    [Model]
    [Expose("FirstName")]
    [Expose("Surname")]
    [Expose("Age")]
    public ValidationTest ValidationTest { get; set; }
...
### Actual behaviour
![grafik](https://user-images.githubusercontent.com/13942501/36434545-86bbc340-165f-11e8-8987-2d8759e3f03a.png)

Surname is required but Catel doesn't check it.

**Comment by gofrogi** [comment]
I forgot to mention, I'm using Fody.

**Comment by gofrogi** [comment]
i have to apologize again. It was my mistake. I had to use the "Required" attribute from namespace "System.ComponentModel.DataAnnotations". It work well then.
The issue can be set to "finished".

**Comment by GeertvanHorrik** [comment]
Thanks for the update!
