### ISSUE TITLE
Issues with Catel.MVVM in NetStandard 2.0

### ISSUE THREAD

**Issue by IsmailHassani** [Catel/Catel#1164]
Hi @GeertvanHorrik, 
I have managed to convert most of the applications to the latest Catel version.
I  1 aps.net core backend, have 2 WPF applications and one UWP application that uses the same base code (models and viewmodels). My model- and viewmodel library is a NetStandard 2.0 library because of the requirement to be multi-platform. However, the viemodel-library gives me an error in the Catel.Mvvm package stating: 

> Package 'Catel.MVVM 5.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

With the core package i have no issues. Are you aware of this? Or is there a workaround?
Thank you in advance.

**Comment by GeertvanHorrik** [comment]
At this stage we don't have a .net standard implementation of Catel.MVVM (would only make sense for xamarin.forms), we have platform specific libraries.

**Comment by GeertvanHorrik** [comment]
And in all honesty I don't think we will implement that. The primary focus with Catel is to solve our own problems, which others can use for free. At this stage we are not interested in a .NET Standard 2.0 implementation of Catel.MVVM.
