### ISSUE TITLE
Nesting with ChildAwareModelBase does not support more than one layer

### ISSUE THREAD

**Issue by mennodeij** [Catel/Catel#1166]
When I run the unit test pasted below, the top level 'GrandParent' is not set to IsDirty=true when the child is changed. I would expect this to happen.

### Steps to reproduce

    public class GrandParent : ChildAwareModelBase
    {
      public void ResetIsDirty()
      {
        IsDirty = false;

      }
      public ObservableCollection<Parent> Children
      {
        get { return GetValue<ObservableCollection<Parent>>(ChildrenProperty); }
        set { SetValue(ChildrenProperty, value); }
      }

      public static readonly PropertyData ChildrenProperty = RegisterProperty(nameof(Children), typeof(ObservableCollection<Parent>), () => new ObservableCollection<Parent>());
    }

    public class Parent : ChildAwareModelBase
    {
      public void ResetIsDirty()
      {
        IsDirty = false;

      }
      public ObservableCollection<Child> Children
      {
        get { return GetValue<ObservableCollection<Child>>(ChildrenProperty); }
        set { SetValue(ChildrenProperty, value); }
      }

      public static readonly PropertyData ChildrenProperty = RegisterProperty(nameof(Children), typeof(ObservableCollection<Child>), () => new ObservableCollection<Child>());
    }

    public class Child : ChildAwareModelBase
    {
      public void ResetIsDirty()
      {
        IsDirty = false;

      }

      public string Name
      {
        get { return GetValue<string>(NameProperty); }
        set { SetValue(NameProperty, value); }
      }

      public static readonly PropertyData NameProperty = RegisterProperty(nameof(Name), typeof(string), null);

    }

    [TestFixture]
    class NestedChildAwareTest
    {
      [Test]
      public void TestNestedIsDirty()
      {
        var g = new GrandParent();
        var p = new Parent();
        var c = new Child();
        g.Children.Add(p);
        p.Children.Add(c);

        c.ResetIsDirty();
        p.ResetIsDirty();
        g.ResetIsDirty();

        Assert.IsFalse(c.IsDirty);
        Assert.IsFalse(p.IsDirty);
        Assert.IsFalse(g.IsDirty);

        c.Name = "Pietje";
        Assert.IsTrue(c.IsDirty);
        Assert.IsTrue(p.IsDirty);
        Assert.IsTrue(g.IsDirty); // THIS FAILS

      }
    }

Platform: Windows
.NET version: 4.6

**Comment by mennodeij** [comment]
This is a problem with the use of `ObservableCollection<T>`. When the properties are just simple properties, the problem does not happen.

**Comment by GeertvanHorrik** [comment]
We'll release a new alpha on MyGet later today so you can use this fix.
