### ISSUE TITLE
I need the ShowDialog (not async) back

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1171]
Platform:
.NET version: >= 4.5 
C++/CLI
Catel 5.3

Hi Geert,

with Catel 5.x the Method UIVisualization.ShowDialog is gone. We should use allways the sync method instead. It work fine in .Net code, but! 
I have one scenario that doesnt work. From my C++/CLI code i have to call a .net method that include a call to await ShowDialogAsync, therefor is the method to be async, but i didn't find a way to call a async Method from C++/CLI code. 
Is there a way to get back the sync method of ShowDialog? Or may be you know how to do it right way?

**Comment by GreenKn1ght** [comment]
"Or may be you know how to do it right way?"
You should ask such questions on StackOverflow. Check those links:
https://stackoverflow.com/questions/42274911/how-to-consume-an-awaitable-in-c-cli
https://stackoverflow.com/questions/22795922/handling-windows-store-app-exceptions-from-getfileasync

I think you can try to implement, raise and handle events from target view model, but then you need to be sure that ShowDialogAsync won't throw exceptions.

**Comment by gofrogi** [comment]
I implemented an sync method to be called in CLI  code and used pure WPF to show my dialog
something like this:

var dialog = new AnyWindow(pramas,...);
dialog.ShowDialog(); // modal and syncron.

The async method will be used only in .net

**Comment by GeertvanHorrik** [comment]
Excellent solution. The stuff Catel provides are just "out-of-the-box" services. Nothing prevents you from implementing your own visualizer service that is non-async.
