### ISSUE TITLE
MSBUILD : warning : Fody: No debug symbols found. It is recommended to build with debug symbols enabled.

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1178]
Platform:
.NET version: 4.5, Catel 5.3, VS 2015

### Expected behaviour

no warnings

### Actual behaviour

in some project with Catel.Fody referenced (not in all) i get this message if compiling Win32 release configuration. 

Why?

**Comment by GeertvanHorrik** [comment]
Fody should write out the pdb files again.

However… it looks like you are building in release mode *without debug symbols*. Even in release mode, it's recommended to create minimal debug symbols:

![image](https://user-images.githubusercontent.com/1246444/39303091-3178fcc6-4955-11e8-882f-007b2a523434.png)

**Comment by gofrogi** [comment]
Thank you. That was it. 😃
