### ISSUE TITLE
InputGesture not properly handled by CommandManager

### ISSUE THREAD

**Issue by philjpearson** [Catel/Catel#1185]
### Steps to reproduce

1. commandManager.CreateComandWithGesture - command1 with InputGesture **Shift+Ctrl+A**
2. commandManager.CreateComandWithGesture - command2 with InputGesture **Alt+Ctrl+A**

Platform:
.NET version: 4.6.2

### Expected behaviour

Each command should be executed in response to the corresponding keyboard input.

### Actual behaviour

Only command 1 works. If you create the commands in the other order still only the **Shift+Ctrl+A** command works; **Alt+Ctrl+A** is ignored.
Change the second InputGesture to **Alt+Ctrl+R** and it works.
(A and R are just examples. Other letter keys give the same problem.)

So two gestures with the same letter key conflict somehow.

**Comment by philjpearson** [comment]
I created 3 pull requests for minor modifications to the Catel.Examples.WPF.Commanding example. This will illustrate the problem. Typing Shift+Ctrl+A will display the Test1 message. Typing Alt+Ctrl+A **should** display the Test2 message but it won't work.

**Comment by GeertvanHorrik** [comment]
I've updated the examples, can't reproduce with the latest version of Catel (5.4.0). What version of Catel are you using?

**Comment by philjpearson** [comment]
Sorry for the delay in replying; I have been away.
I was using 5.3.0 but have now updated to 5.4.0 and the same problem remains.

**Comment by philjpearson** [comment]
I have just discovered that if I change both gestures to use (for example) U (Shift+Ctrl+U and Alt+Ctrl+U) they both work. Alt+Ctrl+A  on its own will still not work (so it's not conflicting with another A gesture).

Maybe Alt+Ctrl+A is being intercepted by something else? It's not in my app, I have 5 different apps using the same gestures and none of my code intentionally intercepts Alt+Ctrl+A.

I'll do some more investigation when I have time.
_Thanks for your interest and attention, but it's probably not your problem after all._
