### ISSUE TITLE
CanExecute WeakRef is cleared when CanExecute-Lambda is in DisplayClass

### ISSUE THREAD

**Issue by bluejack2000** [Catel/Catel#1192]
This one gave me quite some headaches. CanExecute does not work properly depending on where the lambda for it is compiled into. In version 4.5.3 there was no problem. Problems came after upgrade to 5.5.0

### Steps to reproduce

1. I made a unit test for it

Platform: Windows
.NET version: 4.5.2

### Expected behaviour

CanExecute must execute in all cases. Independent whether the compiler puts it in a DisplayClass for whatever reason or not.

### Actual behaviour

CanExecute lambda callback gets lost after garbage collection when the lambda is compiled into a DisplayClass. 

I forced the compiler to use a DisplayClass for the CanExecute lambda by refering a local variable. I checked with ILSpy that this is the case. Once the lambda is put inside a DisplayClass the weak reference will assume that the Target (which is the DisplayClass) is not alive anymore after next GC causing CanExecute to return true in all cases.

Here is my unit test which fails:

```
  public class TestDisplayClassViewModel : ViewModelBase
  {
    public TestDisplayClassViewModel()
    {
      int localVariable = 1;
      TestCommand = new Command(TestFunction, () =>
      {
        Debug.WriteLine("CanExecute called " + localVariable++);
        return false;
      });
    }

    public void TestFunction()
    {
    }

    public Command TestCommand { get; set; }
  }

  public class CatelCanExecuteWeakRefTest
  {
    [Test]
    public void CanExecuteWeakRefLostTest()
    {
      Catel.Logging.LogManager.AddDebugListener();
      var vm = new TestDisplayClassViewModel();

      var canExecuteBefore = vm.TestCommand.CanExecute();
      Debug.WriteLine("CanExecute before: " + canExecuteBefore);
      GC.Collect();
      var canExecuteAfter = vm.TestCommand.CanExecute();
      Debug.WriteLine("CanExecute after: " + canExecuteAfter);
      Assert.That(canExecuteAfter, Is.False);
    }
  }
```

Resulting log is:

> CanExecute called 1
> CanExecute before: False
> 19:58:48:783 => [DEBUG] [Catel.WeakFunc`1] [11] Target for 'Boolean <.ctor>b__0()' is no longer alive, weak event being garbage collected
> CanExecute after: True

**Comment by GeertvanHorrik** [comment]
Does this happen both in release and debug modes?

**Comment by bluejack2000** [comment]
Yes this happens in release mode too. Have to change the Debug.WriteLine to Console.WriteLine ofcourse.

**Comment by bluejack2000** [comment]
As a workaround I use a derived class CatelCommand for now which keeps a reference to the CanExecute func. That passes the unit test above.

```
  public class CatelCommand : Command
  {
    private Func<bool> _canExecuteRef;

    public CatelCommand(Action execute, Func<bool> canExecute = null, object tag = null) : base(execute, canExecute, tag)
    {
      _canExecuteRef = canExecute;
    }
  }

  public class CatelCommand<TExecuteParameter, TCanExecuteParameter> : Command<TExecuteParameter, TCanExecuteParameter>
  {
    private Func<bool> _canExecuteRef;
    private Func<TCanExecuteParameter, bool> _canExecuteWithParameterRef;

    public CatelCommand(Action execute, Func<bool> canExecute = null, object tag = null) : base(execute, canExecute, tag)
    {
      _canExecuteRef = canExecute;
    }

    public CatelCommand(Action<TExecuteParameter> execute, Func<TCanExecuteParameter, bool> canExecute = null, object tag = null) : base(execute, canExecute, tag)
    {
      _canExecuteWithParameterRef = canExecute;
    }
  }
```

**Comment by bluejack2000** [comment]
[CTL-1007](https://github.com/Catel/Catel/issues/123) in my opinion was a misunderstanding and should be reverted. There can't be CanExecute "listeners", only the CanExecuteChanged event can have listeners. 

**CanExecuteChanged** event should be implemented as weak event pattern as proposed in [CTL-1024](https://github.com/Catel/Catel/issues/142) not the CanExecute callback.

**Comment by GeertvanHorrik** [comment]
I think reverting is a big step. I am trying to finish a few deadlines. Maybe we created it to prevent a canexecute in combination with CompositeCommand since that contains a list of commands, but we could argue that it's up to the caller to unsubscribe there.

But if you don't, all items you subscribe to will be kept in memory because they are referenced by the global command (e.g. view models kept in memory, etc). 

But then again, if you correctly unsubscribe you won't have that issue.

**Comment by bluejack2000** [comment]
As it is at the moment Catel commands can't be used. I had all types of issues with CanExecute suddenly returning true in several parts of our application. 

To fix the issue all what has to be done is to remove the weak reference to the CanExecute func in Command, making it a simple reference. Lambdas (which should be a quite common usage scenario for CanExecute) are in danger to get cleaned up by accident with the current implementation.

If you don't have the time I can prepare a pull request. The command must reference the lambda or it can get lost.

As reference, in my link about the compiler discussion he even mentioned the potential problem that arised here:

> If we use the lambda expression with weak reference object like the command or messenger for MVVM, it will be collected by GC.
> 
> I can understand the notClosure expression will be collected, but I think the closure expression should not be collected due to other code.
> 
> If the closure expression will be collected by GC, I am afraid to use the lambda expression because it will cause some defects.

**Comment by GeertvanHorrik** [comment]
We haven't hit any issues in our (pretty large) apps. But please do create a PR, happy to put this into 5.6 which shouldn't be too far from being released.

**Comment by GeertvanHorrik** [comment]
Sorry I didn't get back to this, was on holidays. Were you interested in doing a PR? I am currently trying to finalize a 5.6 release.

**Comment by GeertvanHorrik** [comment]
Adding unit tests to repo now.

**Comment by GeertvanHorrik** [comment]
The display class is stored as a field in the ViewModel. Therefore I am not sure why it would be garbage collected, as long as the vm is still alive. The unit tests also succeed, so maybe things have changed in the meantime?

**Comment by GeertvanHorrik** [comment]
I am tempted to change this as you suggest. The Execute actions aren't weak either, so we should either make it all weak or not. For now I will change it back and people should test / report any memory leaks.
