### ISSUE TITLE
OnDeserializing and OnDeserialized are called twice on ModelBase (de)serialization

### ISSUE THREAD

**Issue by ArXen42** [Catel/Catel#1194]
### Steps to reproduce

1. Attempt to load any model.
2. Place breakpoints/log writes in `OnDeserializing` and `OnDeserialized`.
3. Observe methods invocations.

The behaviour was identical for XML and JSON serialization.

**Platform**: tested on WPF
**.NET version**: 4.6.1, probably any other

Archive with sample project is attached. The model is `TestModel` and loading is placed in `MainWindowViewModel` (from `output/Debug/Model.xml`). Serializer is configured in `App.xaml.cs`.
[TestSerialization.zip](https://github.com/Catel/Catel/files/2098777/TestSerialization.zip)

### Expected behaviour

`OnDeserializing` and `OnDeserialized` were expected to be called once.

### Actual behaviour

These methods are called twice for a single `Load` call.

### Notes
Sorry if I misunderstood something and this is the desired behaviour. I don't have good understanding of Catel serialization code yet, so at the moment I cannot determine the reason why this is happening by myself. Mentioned methods are called from `SerializationContext.CreateSerializableToken` callbacks.

I am not sure if that is a bug, but didn't find any related information.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We will investigate the repro.

**Comment by GeertvanHorrik** [comment]
Seems to happen to the root type of the serialization graph. Will need to ensure this doesn't happen, thanks for reporting!

**Comment by GeertvanHorrik** [comment]
Fixed.
