### ISSUE TITLE
BatchLogListenerBase WriteBatchAsync async handling not working

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1195]
### Steps to reproduce

1. Create new listener class and inherit from Catel BatchLogListenerBase
2. Override WriteBatchAsync and add logic like 2 x Task.Delay(10000).

Platform:
.NET version: UWP Anniversary Update

### Expected behaviour

I would expect to complete WriteBatchAsync completely and approx. 5 seconds later enter the method again (base has a timer triggering each 5 seconds)

### Actual behaviour

I will get inside WriteBatchAsync multiple times before the previous one finishes.

**Comment by GeertvanHorrik** [comment]
Next time please add a repro so we can easily add unit tests.

**Comment by GeertvanHorrik** [comment]
Fixed.
