### ISSUE TITLE
Support PasswordBox for the 'SelectOnFocus' behavior

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1204]
### Feature description

[SelectOnFocus](https://github.com/Catel/Catel/blob/develop/src/Catel.MVVM/Windows/Interactivity/Behaviors/SelectTextOnFocus.cs) behavior works on TextBox only. It could be nice to have it work on PasswordBox also.

Could it be an idea to let the behavior base on `Control` instead of `TextBox` and throw an exception if the attached instance it is not a TextBox or PasswordBox. Else just don't call execute SelectAllTex() when it gets focus, if the associated instance doesn't implements it.

**Comment by GeertvanHorrik** [comment]
PasswordBox derives from Control. I am not sure if we can change the base type of the behavior. Will try for the next beta of Catel. If it breaks anything, I will revert.

**Comment by GeertvanHorrik** [comment]
Implemented, will release a new beta.
