### ISSUE TITLE
PleasewaitService shows only the normal windows waiting rotating donut

### ISSUE THREAD

**Issue by MattiasEppler** [Catel/Catel#1206]
Platform:
.NET version: 4.6.1

Since Version 5.0.0 PleasewaitService shows only the normal windows waiting rotating donut.
No longer the known catel donut with please wait message.

**Comment by GreenKn1ght** [comment]
Check comments: https://github.com/Catel/Catel/issues/1010

**Comment by MattiasEppler** [comment]
Funny. The PleasewaitDialog is removed. But the Pleasewaitservice with the methods to set a message are still there. And also the docs where not updated.

I already said that some times before. Catel looses a lots of functionality. 
So I think its time to say goodbye.

**Comment by GeertvanHorrik** [comment]
@MattiasEppler we made the change to remove the implementation from Catel to make it more lightweight and configurable. If you look at how the PleaseWaitService is implemented in Orchestra (github.com/wildgums/orchestra), you might understand that different types of indicators are still possible with your own implementation.

The reason we kept the messages is to make the upgrades as smooth as possible for every one and custom (such as previous) implementations are still possible. If you wish to keep the old behavior, just copy/paste it and you are done. 

> So I think its time to say goodbye.

No need to threaten with saying goodbye, you are always free to do so. In the end it's a free framework and you have been lucky enough to be able to use it for free. I hope it helped you write great software and earn money with it to pay your bills.

**Comment by MattiasEppler** [comment]
Hi Geert. I think one big problem is the documentation.

But the main reason I say goodbye is not the PleasewaitDialog. 
Its the nested user control problem. 
You made advertise with this feature: https://catelproject.atlassian.net/wiki/spaces/CTL/pages/1409119/Introduction+to+the+nested+user+controls+problem

The reason why I choose catel. But now this does not working anymore. And the open issue is set to pull request.

**Comment by GeertvanHorrik** [comment]
> But now this does not working anymore

It's working fine, we use it in over 12 apps in production. If it's not working, provide a repro. And you are always free to help with the docs, we simply need to focus our resources, which isn't docs at the moment.

**Comment by MattiasEppler** [comment]
I provided a repro in https://catelproject.atlassian.net/browse/CTL-528 in 2014
4 years ago!

**Comment by GeertvanHorrik** [comment]
You're saying the nested stuff isn't working, but it's "just" validation. Please recreate the repro with Catel 5.6 and we'll see if we can fix it.
