### ISSUE TITLE
DeferValidationUntilFirstSaveCall default value inconsistency in tooltip help?

### ISSUE THREAD

**Issue by mgiu** [Catel/Catel#1211]
Hi,
It seems that the default value of ViewModelBase.DeferValidationUntilFirstSaveCall is set true, but according to the tooltip help that pops-up in Visual Studio pointing the property name with the cursor "is false" (please refer to the image enclosed). Is maybe an update of the corresponding tooltip-help 
comment missing?
Thanks!
![catelimg](https://user-images.githubusercontent.com/35818130/44033126-b07662e8-9f09-11e8-8cfb-d12a3d6d88a0.jpg)

**Comment by GeertvanHorrik** [comment]
Great catch, we'll update this in the docs.

**Comment by GeertvanHorrik** [comment]
Fixed.
