### ISSUE TITLE
Entity framework core error when using lazy loading

### ISSUE THREAD

**Issue by bigworld12** [Catel/Catel#1213]
### Steps to reproduce

1. create the following model (i am using Catel.Fody to change the properties)
```
public class AClass : ValidatableModelBase
{
    public virtual BClass RelatedB { get; set; }
}
public class BClass : ValidatableModelBase
{
    public BClass()
    {
        RelatedAs = new HashSet<AClass>();
    }
    public virtual ICollection<AClass> RelatedAs { get; set; }
}
```
2. use `Microsoft.EntityFrameworkCore` with `Microsoft.EntityFrameworkCore.Proxies`
3. open the application and build the model

Platform: win 10
.NET version: .net standard 2.0

### Expected behaviour

should build the model with no problem

### Actual behaviour

you get this error
`No field was found backing property 'RelatedB ' of entity type 'AClass'. Lazy-loaded navigation properties must have backing fields. Either name the backing field so that it is picked up by convention or configure the backing field to use.`

i suppose that is because the way Catel is handling properties, they are not stored in plain fields, but how can i configure lazy loading to work with Catel ?

**Comment by GeertvanHorrik** [comment]
Catel uses "dependency-property" alike registrations. This means the properties are actually stored in a property bag, and the registration / properties are just wrappers around this property bag. Therefore this won't work for relational (proxy) classes.

**Comment by bigworld12** [comment]
so, can i implement `INotifyPropertyChanged` in the model, but use Catel.MVVM in the view model ?
basically i want to use stuff like
`[Model]` and `[ViewModelToModel]` attributes
in my UI project, while still using normal properties in my core project

**Comment by GeertvanHorrik** [comment]
Yep, Model will support as much as it can (e.g. INotifyPropertyChanged, IEditableObject, etc...)
