### ISSUE TITLE
ViewToViewModel attribute doesn't work

### ISSUE THREAD

**Issue by bigworld12** [Catel/Catel#1214]
i have prepared a minimal repo to reproduce the problem
https://github.com/bigworld12/Catel.TestViewToViewModel

basically when updating the view, the viewmodel doesn't change, and updating the viewmodel doesn't update the view either

**Comment by bigworld12** [comment]
@GeertvanHorrik would you check this out please ?

**Comment by bigworld12** [comment]
i fixed it myself, basically i forgot to add
```
    static TestControlView()
    {
        typeof(TestControlView).AutoDetectViewPropertiesToSubscribe();
    }
```
in my `TestControlView.xaml.cs`
Source : http://docs.catelproject.com/5.7/catel-mvvm/view-models/mapping-properties-from-view-to-view-model/

**Comment by GeertvanHorrik** [comment]
Thanks for posting the solution.
