### ISSUE TITLE
Add InvokeAsync() for UWP (NETFX_CORE)

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1215]
InvokeAsync() is not available for UWP (NETFX_CORE). I believe the implementation for NET should be working for UWP as well, so hopefully the fix is just a matter of changing the use of compiler directives.

**Comment by byrialsen** [comment]
@GeertvanHorrik . Maybee this one is an easy catch ?

**Comment by GeertvanHorrik** [comment]
Yep, we should be able to add this one as well, but need to check.

**Comment by byrialsen** [comment]
Sounds great. Actually I just wan'ted to trigger the bot to remove the wontfix label again :-). I assume you will do this when you think the time is right.

**Comment by GeertvanHorrik** [comment]
These methods use DispatcherPriority, let's see if we can add support for that, but it's not as easy as we would think.

**Comment by GeertvanHorrik** [comment]
Added #1228 as a reminder.

**Comment by GeertvanHorrik** [comment]
Done, releasing a new beta now. *Please test carefully, preferrably today*.

**Comment by GeertvanHorrik** [comment]
Build - 5.8.0-beta.2, will take about 10 - 20 minutes

**Comment by byrialsen** [comment]
@GeertvanHorrik. Sorry - just saw your message right now. Had a short day at work:-) Will try to test early in the morning.
