### ISSUE TITLE
UIVisualizerService is not setting parent window correctly

### ISSUE THREAD

**Issue by ccHanibal** [Catel/Catel#1218]
Showing a modal dialog via ShowDialogAsync() does not set active window as owner, resulting in windows with WindowStartupLocation="CenterOwner" not to be placed at the center of their parent.

I think it is because in commit 2d6c27d3173433b2a3776f1f2f7857d6e242e128 the line `if (window != activeWindow)` has been replaced by `if (ReferenceEquals(window, activeWindow))` which is missing the negation of the equality test.

### Steps to reproduce

1. Use IUSVisualizerService.ShowDialogAsync to open a child window with WindowStartupLocation="CenterOwner"
2. Observe that the child window is not placed at the center

Platform:
.NET version: 4.5

### Expected behaviour
The child window should be centered above its parent.

### Actual behaviour

The child window is placed as if it had no WindowStartupLocation="CenterOwner" aka the default window location is used.

![grafik](https://user-images.githubusercontent.com/3986339/45378572-1d23b480-b5fe-11e8-8770-fb3924d494d1.png)

**Comment by GeertvanHorrik** [comment]
Thanks for the investigation. I'll check it right now.

**Comment by GeertvanHorrik** [comment]
btw I recommend checking out Orchestra and Orc.Controls. These are libraries on top of Catel and provide nice controls such as a DatePicker, DateTimePicker, etc (since you are working on form-entry, these might be useful).

**Comment by GeertvanHorrik** [comment]
Fixed, thanks for reporting! We will deploy a new (alpha) version to MyGet right now.
