### ISSUE TITLE
Wrong ViewModel is initialized for View

### ISSUE THREAD

**Issue by mkuch95** [Catel/Catel#1219]
I have following Views:
 - InfoView
 - InfoWindow

And ViewModels:
 - InfoViewModel
 - InfoWindowViewModel

The problem is that InfoWindow has assigned InfoViewModel by resolver.

The problem disappears when when I add the rules manually:
`
	var viewModelLocator = ServiceLocator.Default.ResolveType<IViewModelLocator>();
	viewModelLocator.Register(typeof(InfoWindow), typeof(InfoWindowViewModel));
	viewModelLocator.Register(typeof(InfoView), typeof(InfoViewModel));
`

### Steps to reproduce

1. Clone example problematic project from my github: https://github.com/mkuch95/CatelCloseWindowExample
2. Run application
3. Click "More Info..." button
4. Click "Close" button
5. Logic from "InfoViewModel" will be invoked instead of "InfoWindowViewModel"

Platform:
.NET version: 4.6.1

### Expected behaviour

"InfoWindowViewModel" should be assigned to "InfoWindow"

### Actual behaviour

"InfoViewModel" is assigned to "InfoWindow" by default resolver.

**Comment by GeertvanHorrik** [comment]
Correct, this is "expected behavior". The solution is to manually register this special use case in the UIVisualizerService, we do this for a few use-cases as well:q

```
        // Register some custom windows (since we combine windows and views)
        var uiVisualizerService = serviceLocator.ResolveType<IUIVisualizerService>();
        uiVisualizerService.Register<EulaViewModel, EulaWindow>();
        uiVisualizerService.Register<ReleaseNotesViewModel, ReleaseNotesWindow>();
        uiVisualizerService.Register<ValidationViewModel, ValidationWindow>();
```

This allows us to enforce a specific VM for a window.

**Comment by mkuch95** [comment]
Thanks, your answer dispelled doubts.
