### ISSUE TITLE
CTL-1006: Localized string in tests assertions

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#122]
Jira issue originally created by user szogun1987:

Some tests checks if localized strings are equal to constant values e.g. TheWarningMethod.Warning_ExceptionWithMessageFormat checks if exception message is equal to "additional message 1 | [ArgumentNullException] System.ArgumentNullException: Value cannot be null.\r\nParameter name: log" but on non-english operating systems message is different.

**Comment by GeertvanHorrik** [comment]
Pinging @szogun1987

**Comment by GeertvanHorrik** [comment]
Closing since we got no response.

**Comment by GreenKn1ght** [comment]
Since Im using different culture, I can provide list of such tests (develop):
<details>
 <summary>Failed tests</summary>

```csharp
Catel.Test.Logging.LogFacts.TheDebugMethod.Debug_Exception()
Catel.Test.Logging.LogFacts.TheDebugMethod.Debug_ExceptionWithMessage()
Catel.Test.Logging.LogFacts.TheDebugMethod.Debug_ExceptionWithMessageFormat()
Catel.Test.Logging.LogFacts.TheDebugMethod.Debug_Exception_Aggregated()

Catel.Test.Logging.LogFacts.TheErrorMethod.Error_Exception()
Catel.Test.Logging.LogFacts.TheErrorMethod.Error_ExceptionWithMessage()
Catel.Test.Logging.LogFacts.TheErrorMethod.Error_ExceptionWithMessageFormat()
Catel.Test.Logging.LogFacts.TheErrorMethod.Debug_Exception_Aggregated() //Typo!

Catel.Test.Logging.LogFacts.TheInfoMethod.Info_Exception()
Catel.Test.Logging.LogFacts.TheInfoMethod.Info_ExceptionWithMessage()
Catel.Test.Logging.LogFacts.TheInfoMethod.Info_ExceptionWithMessageFormat()
Catel.Test.Logging.LogFacts.TheInfoMethod.Info_Exception_Aggregated()

Catel.Test.Logging.LogFacts.TheWarningMethod.Warning_Exception()
Catel.Test.Logging.LogFacts.TheWarningMethod.Warning_ExceptionWithMessage()
Catel.Test.Logging.LogFacts.TheWarningMethod.Warning_ExceptionWithMessageFormat()
Catel.Test.Logging.LogFacts.TheWarningMethod.Warning_Exception_Aggregated()

Catel.Test.MVVM.Converters.BooleanToTextConverterTest.Convert_False()
Catel.Test.MVVM.Converters.BooleanToTextConverterTest.Convert_False_YesNoAsText()
Catel.Test.MVVM.Converters.BooleanToTextConverterTest.Convert_False_YesNoAsValue()

Catel.Test.MVVM.Converters.BooleanToTextConverterTest.Convert_True()
Catel.Test.MVVM.Converters.BooleanToTextConverterTest.Convert_True_YesNoAsText()
Catel.Test.MVVM.Converters.BooleanToTextConverterTest.Convert_True_YesNoAsValue()
```
</details>

**Comment by GreenKn1ght** [comment]
@GeertvanHorrik I think forcing culture in GlobalInitialization is fine solution. Please reopen this issue. I'll create pull request then.
Also if you don't mind, I'll change attribute TestCase to Test for these tests.

**Comment by GeertvanHorrik** [comment]
> Also if you don't mind, I'll change attribute TestCase to Test for these tests.

Excellent! I was also considering converting some tests to TestCase (we implemented them at the time we didn't have TestCase), but that's all low prio so great if you could pick that up.
