### ISSUE TITLE
NavigationContext does not contains parameters on INavigationService.GoBack

### ISSUE THREAD

**Issue by vkotov** [Catel/Catel#1221]
### Steps to reproduce

1. Navigate to page with parameters:
`            var parameters = new Dictionary<string, object> { { "query", "search text"} };
            _navigationService.Navigate<SearchViewModel>(parameters);
`
2. Navigate to another page:
`_navigationService.Navigate<ResultViewModel>();`
3. Go back to previous page:
`                if (_navigationService.CanGoBack)
                {
                    _navigationService.GoBack();
                }
`
4. See parameters in **SearchViewModel.OnNavigationCompleted** overload. 

Platform:
.NET version: 4.6.1
WPF **System.Windows.Controls.Frame** control used as root for navigation.

### Expected behaviour

**NavigationContext.Values** should contains parameters like `"query"/"search text"`.

### Actual behaviour

**NavigationContext.Values** contains one key/value: `"context"/null`.

**Comment by GeertvanHorrik** [comment]
@vkotov thanks for reporting. If you can provide a small repro, then we can hopefully fix this soon.
