### ISSUE TITLE
Calling SaveViewModelAsync() twice

### ISSUE THREAD

**Issue by RCP161** [Catel/Catel#1226]
If I use the CancelViewModelAsync() Method, the ViewModel doesn't get the PropertyChanged of the Model anymore. So if I edit the ViewModel again, the changes will be written to the Model, but changes on other Properties will not be shown in the ViewModel.
Addtional to that, if i call CancelViewModelAsync() the second time, nothing happend. 

### Steps to reproduce

Done in this TestRepo: https://github.com/RCP161/IDataObjectTest/tree/master/M1Vm2

1. Start the program and change one value. Leave the field, so that the Property updates. The State TextBlock changes.
2. Click Revert to call CancelViewModelAsync() and change the value again.

=> The TextBlock does not change the state anymore. You can trace the problem in the output window.

4. Click Revert again.

=> Nothing happened.

Platform:
.NET version: 4.6.1

### Expected behaviour

The ViewModel should still listen on the PropertyChanged of the Model.
The CancelViewModelAsync (or SaveViewModelAsync) should be called more times than one. 

### Actual behaviour
ViewModel dosen't listen to the PropertyChanged of the Model anymore.
Can't call  ((System.ComponentModel.IEditableObject)this).BeginEdit(); to use the functionality again. So nothing happened.

**Comment by GeertvanHorrik** [comment]
A model only has a single backup at a time. We don't have plans to support multiple backup scenarios at the same time.

**Comment by RCP161** [comment]
You don’t have to do this as default. 
What I need to know is, how I can create a new backup, so that I can call it by myself. The problem is, that it doesn't work, like it is described in the comment of this [answer](https://stackoverflow.com/a/52853824/7790628) and here in the actual behavior with the ((System.ComponentModel.IEditableObject)this).BeginEdit();.
Also, I need the behavior, that the ViewModel should listen to the Model, until it is not needed anymore. For Example, if the usercontrol will be unloaded or so.

Or what is the common scenario for this? Have I to change the view after calling cancel or save?

**Comment by RCP161** [comment]
Hi,
I don't need multiple backup scenarios at the same time. I need a new backup cycle, after calling CancelViewModelAsync or SaveViewModelAsync.

**Comment by GeertvanHorrik** [comment]
What do you mean by: "a new backup cycle"? Maybe we can make some methods protected virtual so you can customize the model behavior?

**Comment by RCP161** [comment]
Like I explained,
I edit the data and save (or revert). After that, I would expect, that this back up mechanism will start again, so that I can use it multiple times. Like a cycle.

Edit data - Save - Back up will be replaced with new data;
Edit data again - Save - Back up will be replaced with new data;
Edit data again - Cancel - Data will be reverted withe back up;

All without closing the view, so that the view, the model and the viewmodel is all time the same. I dind't find this use case in the examples.

**Comment by GeertvanHorrik** [comment]
At the moment, whenever a VM is saved, it will call `EndEdit` on the `IEditableObject` interface. It has no intention of re-initiating a backup because Catel assumes a VM will only be saved once (and disposed after that). In your case, you can call `base.SaveAsync` and then initialize a `BeginEdit` again with the new values if you want to keep the vm alive.
