### ISSUE TITLE
SavableModelBase.Save throws InvalidCastException for UWP platform

### ISSUE THREAD

**Issue by jjmyrup** [Catel/Catel#1227]
### Steps to reproduce

1. Call Save on a SavableModelBase object with a IRandomAccessStream as first argurment

Platform: UWP 14.393 (anniversary update)

### Expected behaviour

It should save the object, without throwing exception

### Actual behaviour

It throws InvalidCastException

![image](https://user-images.githubusercontent.com/20145185/47715112-09c8b900-dc3f-11e8-996a-9253e1b67c74.png)

### Workaround

Convert the IRandomAccessStream to a System.IO.Stream and use the overloaded version of Save that takes a System.IO.Stream

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We might be able to squeeze this one into Catel 5.8 (currently in beta).

**Comment by GeertvanHorrik** [comment]
Fixed.

**Comment by jjmyrup** [comment]
@GeertvanHorrik thank you for the fast response.

SavableModelBase.Load has the same problem. I have fixed it here:

https://github.com/jjmyrup/Catel/commit/9d6d6d568338917602b01c824c11c7da924a2c0b

I was a bit in doubt whether to use the same issue for this as it was very related or create a new one.

But I will create a pull request where I use the same issue.

**Comment by GeertvanHorrik** [comment]
Thanks, I'll fix it there as well.

**Comment by GeertvanHorrik** [comment]
No need to PR for this minor thing, need to update it anyway. Next time you can PR :-)

**Comment by GeertvanHorrik** [comment]
Build - 5.8.0-beta.3 should be available in about 10 - 20 minutes

**Comment by jjmyrup** [comment]
Thank you I will try it out.

**Comment by jjmyrup** [comment]
I have tried it out now.

In my original application I cannot startup using the beta. I haven't found out why. But I have created a sample application here:

https://github.com/jjmyrup/Catel.Examples/tree/feature/test-5-8-0-beta-3

Save does not work and I can see why.
```
public void Save(IRandomAccessStream fileStream, ISerializer serializer, ISerializationConfiguration configuration = null)
{
    Save((Stream)fileStream, null); <---------------- calls Save with null, but save asserts that it is not null
}

public void Save(Stream stream, ISerializer serializer, ISerializationConfiguration configuration = null)
{
    Argument.IsNotNull("stream", stream);
    Argument.IsNotNull("serializer", serializer); <-------------- Check for not null

    serializer.Serialize(this, stream, configuration);

    this.ClearIsDirtyOnAllChilds();
}
```

**Comment by GeertvanHorrik** [comment]
Thanks for the update, will look into it.

**Comment by GeertvanHorrik** [comment]
The Load was already correct, also fixed the Save now.

**Comment by GeertvanHorrik** [comment]
Will be available in about 20 minutes as Build - 5.8.0-beta.5

**Comment by jjmyrup** [comment]
I have tested 5.8.0-beta0006 now.

In my small sample application Save and Load works fine, but I still cannot start my "original" application.

I get the exception shown below. Do you have any idea about what could cause that?

![image](https://user-images.githubusercontent.com/20145185/47900221-71b81300-de7c-11e8-8314-89de3bd70bb4.png)

**Comment by GeertvanHorrik** [comment]
This is a new feature, are you constructing vm's on a separate thread?

**Comment by GeertvanHorrik** [comment]
Haven't experienced this with my own UWP apps, but will replace with a regular timer and dispatcher on timer tick.

**Comment by GeertvanHorrik** [comment]
Build - 5.8.0-beta.7 being released right now

**Comment by jjmyrup** [comment]
Thanks I will check it out, when it is available.

**Comment by GeertvanHorrik** [comment]
Build - 5.8.0-beta.11 is available now.

**Comment by jjmyrup** [comment]
It works like a charm with beta.11.

Thank you for prioritizing this.

Have a nice weekend

**Comment by GeertvanHorrik** [comment]
Glad to hear it's all fixed, thanks for reporting :)
