### ISSUE TITLE
Rendering blank Catel page fails in VS

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1234]
## Problem
I am not able to render a blank page in VS when using a Catel specific Page. A normal Page seems to work fine. 

### Steps to reproduce

Create the most simple blank Catel Page you can. I have created a repo here for ease:

https://github.com/byrialsen/RenderCatelPage

Platform:
UWP
Catel 5.8

### Expected behaviour

The very simple blank page should render just fine

### Actual behaviour

The Non-Catel page renders fine.
The Catel page fails to render. An exception is thrown:

Exception: Cannot create an instance of "Page" .

`IMPORTANT NOTE`
Blend seems to be able to render it ok.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, but we will put this on low-prio. We don't use the designer ourselves and want to focus the (free) resources we have on other tasks.

**Comment by GeertvanHorrik** [comment]
With the latest 5.9 beta with vs 2017 preview, it seems to work?

![image](https://user-images.githubusercontent.com/1246444/51825658-883c0200-22e5-11e9-9e69-637c004c87c2.png)
