### ISSUE TITLE
Application-wide commands do not work for UWP apps after upgrade to 5.8.0

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1235]
### Steps to reproduce

After upgrading from Catel 5.7.0 -> 5.8.0 my application-wide command shortcut are not working anymore.

like:
```csharp
_commandManager.CreateCommand(Commands.Refresh, new InputGesture(VirtualKey.F5));
_commandManager.RegisterCommand(Commands.Refresh, RefreshCommand, this);
```

Downgrading back to 5.7.0 makes it work again.

Platform:
.NET version: UWP

**Comment by GeertvanHorrik** [comment]
Please provide a simple, ready to use, repro so we can test & fix.

**Comment by byrialsen** [comment]
Hi,

Ofcouse @GeertvanHorrik, A simple repro is added here:

https://github.com/byrialsen/CatelAppWideCommands

As it is (using Catel 5.8.0) it doesn't work. If you downgrade to 5.7.0 it works.

**Comment by GeertvanHorrik** [comment]
Looks like the content of the windows is null at the moment of subscriptions.
