### ISSUE TITLE
Add Catel.MVVM resources to Catel.MVVM.Xamarin.Forms

### ISSUE THREAD

**Issue by okunevdm** [Catel/Catel#1236]
Catel.MVVM.Properties.Resources are not available in Catel.MVVM.Xamarin.Forms
i try use MessageService.ShowAsync("Sure to close the app?", "Warning", MessageButton.OKCancel);
but AlertWindow in Android showing without any buttons, becourse LanguageService.GetString("Cancel") or GetString("OK") return null;

Then i try register custom language sources
var resourcesSource = new LanguageResourceSource("DmMobile", "DmMobile.Properties", "Resources");
languageService.RegisterLanguageSource(resourcesSource);
check:
var cancel = languageService.GetString("Cancel");
result: null

of course Resources.resx file exist in the Properties folder and contains string with name "Cancel"

**Comment by GeertvanHorrik** [comment]
Can you check the generated assembly and check the namespace of the resources?

**Comment by okunevdm** [comment]
generated assembly does not contain files of Catel.MVVM resources.
namespace of the custom resources is correct. It accesible by System.Resources.ResourceManager

**Comment by GeertvanHorrik** [comment]
Could be the default namespace used in Catel.MVVM.Xamarin.Forms. We will look into this and try to fix for 5.9

**Comment by GeertvanHorrik** [comment]
Looks like the resources are not correctly being embedded. Should be an easy fix.

**Comment by GeertvanHorrik** [comment]
Resources will now be embedded, thanks for reporting!

![image](https://user-images.githubusercontent.com/1246444/49151208-95ea0100-f30f-11e8-9927-ef5382993a90.png)

**Comment by okunevdm** [comment]
version 5.9 beta5
dependencyResolver.Resolve<IMessageService>();

Exception:

System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Catel.MVVM.Properties.Exceptions.resources" was correctly embedded or linked into assembly "Catel.MVVM" at compile time, or that all the satellite assemblies required are loadable and fully signed.

**Comment by GeertvanHorrik** [comment]
Could it be a first-chance exception? If not, what target fx?

**Comment by okunevdm** [comment]
this exception appears always when call resolve IMessageService
netstandard 2.0
Catel.MVVM.Xamarin.Forms

**Comment by okunevdm** [comment]
beta 7 resolve IMessageService succesfully.
resource file now embedded.
But first post is actual anyway.
When i try show message with MessageService.ShowAsync i see my message, but button Ok, Cancel is not visible.

**Comment by GeertvanHorrik** [comment]
@okunevdm , please create a new ticket so we can track that separately.
