### ISSUE TITLE
Question: Are there any problems with ViewModelToModel and Field validations?

### ISSUE THREAD

**Issue by DanielKuehner** [Catel/Catel#1243]
We came around with a problem which was there for nearly a year and we did not see it. We are still on Catel v5.2 and are standing directly towards a release so we cannot update to the newest version.

Problem: We lost the field errors in our dialog within the text fields. There were here with Catel v4.5.4 but with v5.2.0 not anymore.

We have this scenario:
- A model with ValidateFields
- A view model with [Model] and [ViewModelToModel] properties
- A view with bindings (ValidatesOnDataErrors=True, UpdateSourceTrigger=PropertyChanged) to the ViewModelToModel-properties
- The view has a OK button which CanExecute checks the model for errors

With v4.5.4 the text fields showed the field errors and the OK button was disabled when there wer errors and vise versa. With the our v5.2.0 there are not shown any field errors but the button is disabled when there are errors.

I just tried to bind directly to the model properties. Then the field errors showed up but the CanExecute of the button does not get called anymore ... I should have know - this is because I bind to sub properties.

Any clue what could went wrong? #1108 did not help too.
Even duplicatign the ValidateFields method from the model to the view model does not work.

**Comment by DanielKuehner** [comment]
wow ... #1108 with setting `DeferValidationUntilFirstSaveCall = false;` did work. I have tested it with the wrong code state... Sorry for any inconvenience.

**Comment by GeertvanHorrik** [comment]
Glad it worked out, good luck with the release!

**Comment by DanielKuehner** [comment]
Thank you!
