### ISSUE TITLE
Ignore loading of resource assemblies to prevent race conditions related to the type cache initialization

### ISSUE THREAD

**Issue by PatrickKursawe** [Catel/Catel#1244]
I get deadlocks in my project parallel test runs if I don't initialize the type cache before starting the tests. The issue is easy to reproduce for me, but unfortunately it is not an open source project. I'll try to strip it down and reproduce, but I'd like to already give you a heads up for the issue.

You find a stack trace of the problem in
https://stackoverflow.com/questions/53668571/catel-type-registration-hangs-in-parallel-unit-tests/53668930

Will try to build a test project showing this behavior.

**Comment by PatrickKursawe** [comment]
Tried to find out the root problem, and of course, as soon as I start running the unit tests against a debug build of catel 5.8.0, the problem does not occur any more.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. It might be a good hint that it does not happen in debug mode. We can still try to figure out the root cause and try to fix it :)

**Comment by GeertvanHorrik** [comment]
I want to fix this for the next release, hopefully we can somehow create a repro and get this fixed (even if it's release-mode only, I am happy to have a repro).

**Comment by PatrickKursawe** [comment]
Still failing (but still trying) to construct a test project that reproduces the error.

**Comment by GeertvanHorrik** [comment]
@PatrickKursawe thanks for the hard research. Good point, Catel itself should ignore resource assemblies as well :)

**Comment by GeertvanHorrik** [comment]
Basically applied your fix by default in the TypeCache.
