### ISSUE TITLE
is Catel.MVVM coming to .net core 3 ?

### ISSUE THREAD

**Issue by bigworld12** [Catel/Catel#1245]
so .net core 3.0 has been released like a week ago, and it's really nice if it improves the performance of wpf apps, and i have been wondering if Catel.MVVM is going to be released for .netcore 3.0 (since Catel.Core is already .net standard) which would be really great

**Comment by GeertvanHorrik** [comment]
We are about to write a blog post about this. We have fully implemented .NET Core 3.0 on the alpha builds, available on NuGet.

We hope to release as stable this month / early next month. More info will be in a blog post soon.
