### ISSUE TITLE
Catel.MVVM.Xamarin.Forms MessageBox showing without buttons

### ISSUE THREAD

**Issue by okunevdm** [Catel/Catel#1252]
Catel.MVVM.Xamarin.Forms (5.9 b7)
I try show message:
`messageService.ShowAsync("please press OK or Cancel", "Hello", MessageButton.OKCancel);`
Message is displayed, but without buttons.

Platform:
.NET Standard 2:

### Expected behaviour
Show message with requested buttons

### Actual behaviour
Buttons is not visible

test project:
[MessageTest.zip](https://github.com/Catel/Catel/files/2787571/MessageTest.zip)

**Comment by GreenKn1ght** [comment]
[Original thread](https://github.com/Catel/Catel/issues/1236)

**Comment by GeertvanHorrik** [comment]
Done.
