### ISSUE TITLE
Allow classes derived from Catel.UserControl to use the AddChild method

### ISSUE THREAD

**Issue by SelvinPL** [Catel/Catel#1260]
Version 5.9 breaks my control(it is working with 5.8.0)
error is thrown from `AddChild(grid);`

Minimal steps tu reproduce

MyFancyView.cs

    using Catel.Windows.Controls;
    using System;
    using System.Windows.Media;

    public class MyFancyView : UserControl
    {
        public MyFancyView()
        {
            Init();
        }

        private void Init()
        {

            var grid = new System.Windows.Controls.Grid();
            grid.Background = Brushes.Red;
            AddChild(grid);
        }
    }

MainWindow.xaml

```
<catel:Window x:Class="CatelBug.MVVM.MainView"
              xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
              xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
              xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
              xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
              xmlns:catel="http://schemas.catelproject.com"
              xmlns:local="clr-namespace:CatelBug.MVVM">
    <Grid>
        <local:MyFancyView />
    </Grid>
    
</catel:Window>
```

**Comment by SelvinPL** [comment]
This is prolly because this change https://github.com/Catel/Catel/issues/1251

**Comment by GeertvanHorrik** [comment]
I think you are forgetting the InitializeComponent?

**Comment by SelvinPL** [comment]
it doesn't ... sorry that I didn't paste the exception but (unfortunately) it is translated to my language and would be meaningless ... anyway I've create MCVE project
https://github.com/SelvinPL/CatelBug

there are 3 branches 
master - with exception
old58 - no error with Catel 5.8
fix59 - how did I fix it ... (but at least it should be stated somewhere in docs that 5.9 has breaking changes)

**Comment by SelvinPL** [comment]
sorry ... there master branch was wrong ... now its not working with 5.9

**Comment by GeertvanHorrik** [comment]
Thanks, looking into this now.

**Comment by GeertvanHorrik** [comment]
In the Initialized event, it will now wrap the user control content. Investigating why this causes issuess.

**Comment by GeertvanHorrik** [comment]
Will try to override AddChild. When a wrap is created, the AddChild method will pass the wrap on to the wrapper grid.

**Comment by GeertvanHorrik** [comment]
Please try Build - 5.10.0-alpha.27, it should be on myget in about 10 - 15 minutes.
