### ISSUE TITLE
IModelExtensions.ClearIsDirtyOnAllChildren() not working with a collection of ModelBase

### ISSUE THREAD

**Issue by Drachenkaetzchen** [Catel/Catel#1262]
### Steps to reproduce

1. Create a Model based on `ChildAwareModelBase` (let's call it "Plugin", that's what I use in my project)
2. Create a Model based on `ModelBase` (let's call it "Preset)
3. On the "Plugin" model, create a `FastObservableCollection<Preset> Presets` of the "Preset" model
4. Add one Preset to the Presets and ensure that some property is changed, so that `IsDirty` is set to true
5. Ensure that `IsDirty` on the Plugin is `false`
6. Call `ClearIsDirtyOnAllChilds()` on the plugin 

### Test Case (requires `Catel.Fody`)
```csharp
public class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            var plugin = new Plugin();
            var preset = new Preset();

            plugin.Presets.Add(preset);
            preset.Foo = "bar";

            Debug.WriteLine($"1.) Preset should be IsDirty=True , it actually is: IsDirty={preset.IsDirty}");
            Debug.WriteLine($"2.) Plugin should be IsDirty=True , it actually is: IsDirty={plugin.IsDirty}");

            Debug.WriteLine($"- Clearing dirty flag on Plugin");
            plugin.ClearDirty();
            Debug.WriteLine($"3.) Plugin should be IsDirty=False, it actually is: IsDirty={plugin.IsDirty}");

            Debug.WriteLine($"- ClearIsDirtyOnAllChilds() on Plugin");
            plugin.ClearIsDirtyOnAllChilds();

            Debug.WriteLine($"4.) Preset should be IsDirty=False, it actually is: IsDirty={preset.IsDirty}");
            Debug.WriteLine($"5.) Plugin should be IsDirty=False, it actually is: IsDirty={plugin.IsDirty}");
        }

    }
    
    public class Preset: ModelBase 
    {
        public string Foo {get;set;}
    
    }

    public class Plugin : ChildAwareModelBase 
    {
        public FastObservableCollection<Preset> Presets { get; set; } = new FastObservableCollection<Preset>();
        public void ClearDirty () {
            IsDirty = false;
        }
    }

```

Output:
```
1.) Preset should be IsDirty=True , it actually is: IsDirty=True
2.) Plugin should be IsDirty=True , it actually is: IsDirty=True
- Clearing dirty flag on Plugin
3.) Plugin should be IsDirty=False, it actually is: IsDirty=False
- ClearIsDirtyOnAllChilds() on Plugin
4.) Preset should be IsDirty=False, it actually is: IsDirty=False
5.) Plugin should be IsDirty=False, it actually is: IsDirty=True
```
### Research and Explanation

I think the collection plays the key role why this bug exists. I could not reproduce it when using `Preset` on `Plugin` directly. This was a nightmare to debug and figure out, but well...less work for you ;)

What happens is:

- `ClearIsDirtyOnAllChilds()` iterates over the `FastObservableCollection`
- `ChangeNotificationWrapper` calls `RaisePropertyChanged` with `updateIsDirty=true`
- On the `Preset` child, `IsDirty` is actually set to `false`, but this in turn causes `IsDirty` on `Plugin` being set to `true`

~~A simple workaround is to call `ClearIsDirtyOnAllChilds()` twice, but I'm not sure if there are side effects.~~ Actually this doesn't work, but `ClearIsDirtyOnAllChilds()` plus an additional `IsDirty=false` on the parent class works for me. Of course that doesn't work with nested `ChildAwareModelBase` models.

Some remarks:
- `IsDirty` is implemented (or used) inconsistently. Often the dirty flag is updated via `SetDirty()`, but sometimes it's done directly, skipping the check for `ShouldPropertyChangeUpdateIsDirty()`
- I'm not sure at this point, but during my debugging I noticed that the `PropertyChanged` event was not raised even though `IsDirty` was changed.

The bugfix is probably a bit complex. Being able to subscribe to `IsDirty` is useful, for example to display if a document has been changed. However, it's difficult since at least `ChangeNotificationWrapper` is not aware of the role of `IsDirty`.

Platform: Windows 10, Catel 5.9
.NET version:

**Comment by Drachenkaetzchen** [comment]
# `ChildAwareModelBase` and reverting changes

As additional thoughts regarding `IsDirty` on `ChildAwareModelBase`. Right now it's not possible to undo a child `IsDirty` without also manually updating `IsDirty` on the parent, which requires a link between the child and the parent.

In my case, and based upon the example above, I have a tree implementation of `PresetPath` on the `Plugin` to indicate under which path the preset is stored. This property stores the whole tree hierarchy.

Each preset can have a single `PresetPath` tree node. When I edit a `Preset` and change the refrence to `PresetPath`, everything is fine. `Preset.IsDirty` gets changed to `true`. If I want to undo that, I can simply set `PresetPath` to the previous value and set `Preset.IsDirty` to false.

But what if I edit a `Plugin` with a collection of `Preset`s? If I change one preset and undo the change, there's no way to notify the `Plugin` that it shouldn't be dirty any longer.

# Conclusion regarding `ChildAwareModelBase`
I think on the long run, it would be best if `IsDirty` isn't a single bool anymore, but reflects the actual state of all properties. For example, if I change a property `Foo`, this would remember `IsPropertyDirty` on the property itself. `IsDirty` could then either iterate over all properties and check if `IsPropertyDirty` is true (which is probably a performance impact) or something like `RecalculateDirtyState`. Both could be implemented on `ChildAwareModelBase`

# Thoughts about property references

Also, I should be able to edit the `PresetPath` hierarchy separately from a `Preset`. I could `BeginEdit` on both objects. As soon as I change a property on a `PresetPath`, this also would mark `Preset` and even `Plugin` as dirty. Cancelling editing on `PresetPath` would neither revert `IsDirty` on `Preset`or `Plugin`.

Yes, this raises additional problems like "How to mark a property that only reference changes should be included in the backup, but not changes to the reference itself". Simply omitting `ModelBase` on `PresetPath` won't work, as sometimes `IsDirty` is required for proper operation and sometimes it hinders proper operation.

**Comment by Drachenkaetzchen** [comment]
Oh, and while it fit's to `ClearIsDirtyOnAllChilds()`: It does not suspend change notifications, and thus fires many events.  Adding a simple `using SuspendChangeNotifications()` beween [here](https://github.com/Catel/Catel/blob/95abb21dd1249b5ee5d429499895a165371d6f15/src/Catel.Core/Data/Extensions/IModelExtensions.cs#L50) and [here](https://github.com/Catel/Catel/blob/95abb21dd1249b5ee5d429499895a165371d6f15/src/Catel.Core/Data/Extensions/IModelExtensions.cs#L59) plus replacing the `IModel` cast with `ModelBase`, I was able to reduce this to 50ms.

Test prerequisites:

ChildAwareModelBase
~1000 childs in collection

Stock `ClearIsDirtyOnAllChilds()`: about 1000ms
With `SuspendChangeNotifications()`: about 50ms

I'm not sure what exactly the difference between `SuspendChangeNotifications()` and `SuspendChangeCallbacks()` is, but adding `SuspendChangeCallbacks()` made no measurable difference at all.

I think I'll refactor this issue into several smaller ones to keep this at a manageable size.

**Comment by GeertvanHorrik** [comment]
I think the bug fix should be to handle the children first, then the parent, then it should all be solved.

**Comment by GeertvanHorrik** [comment]
Written unit tests, could you check why they are succeeding (basically what I did wrong?)

**Comment by Drachenkaetzchen** [comment]
The only thing which I can see is that ClearIsDirtyOnAllChildren` is called on `PluginContainer` and not on a single `Plugin`, but I haven't ran the unit tests so far. I'm currently trying to setup a clone of Catel to run the tests myself and also run my test program and will give feedback after I've done so

**Comment by GeertvanHorrik** [comment]
No, I don't think it's a Catel.Fody issue, that should do nothing differently.

Remember while building:

`./build.ps1 -target build` builds Catel for you, will try to document a few things real quick.

**Comment by Drachenkaetzchen** [comment]
I finally figured it out - I was missing UWP support on my machine, that's why I received lots of odd messages on the CLI. This time I did use Jetbrains Rider, and I got a meaningful error - after installing UWP, building catel works.

However, in my machine, running the unit test fails at [IModelExtensionsFacts.cs#L184](https://github.com/Catel/Catel/blob/b4281185546e6f6731b8f3a883444288537a2358/src/Catel.Tests/Data/Extensions/IModelExtensionsFacts.cs#L184).

Test output:

```
Catel.Tests.Data.IModelExtensionsFacts+TheClearIsDirtyOnAllChildrenMethod.DoesSuspendNotifications

  Expected: True
  But was:  False
```

Same for `Catel.Tests.Data.IModelExtensionsFacts+TheClearIsDirtyOnAllChildrenMethod.DoesNotSuspendNotifications`. Could a possible cause be a different iteration order?

**Comment by Drachenkaetzchen** [comment]
Here's the result when running using `.\build.ps1 -target buildandtest`

```
========================================
Test
========================================

----------------------------------------
Running tests for 'Catel.Tests'
----------------------------------------

Project 'Catel.Tests' is a .NET project, using 'nunit runner' to run the unit tests
Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17763.0
  CLR Version: 4.0.30319.42000

Test Files
    C:/Users/Drachenkatze/source/repos/Catel/output/Release/Catel.Tests/net46/Catel.Tests.dll

=> Catel.Tests.Logging.LogFacts+ThePerformance.LoggingPerformance
Log.Write: 8,74999999999944E-05ms (average), 0,437499999999972ms (total)
=> Catel.Tests.MVVM.Commands.CommandFacts+CTL1192_WeakRef_CanExecute.CanExecuteWeakRefLostTest
CanExecute called 1
CanExecute before: False
CanExecute called 2
CanExecute after: False
=> Catel.Tests.Runtime.Serialization.RedirectDeserializationBinderFacts+ThePerformanceTests.PerformanceTestWithMultithreadedInitialization10000TypesPerThread()
Multithreaded initialization: 32,10002ms (average), 160,5001ms (total)
=> Catel.Tests.Runtime.Serialization.RedirectDeserializationBinderFacts+ThePerformanceTests.PerformanceTestWithMultithreadedInitialization1000TypesPerThread()
Multithreaded initialization: 32,10078ms (average), 160,5039ms (total)
=> Catel.Tests.Runtime.Serialization.RedirectDeserializationBinderFacts+ThePerformanceTests.PerformanceTestWithMultithreadedInitialization100TypesPerThread()
Multithreaded initialization: 68,611ms (average), 343,055ms (total)
=> Catel.Tests.Runtime.Serialization.RedirectDeserializationBinderFacts+ThePerformanceTests.PerformanceTestWithMultithreadedInitialization2500TypesPerThread()
Multithreaded initialization: 35,56242ms (average), 177,8121ms (total)
=> Catel.Tests.Runtime.Serialization.RedirectDeserializationBinderFacts+ThePerformanceTests.PerformanceTestWithMultithreadedInitialization250TypesPerThread()
Multithreaded initialization: 44,06354ms (average), 220,3177ms (total)
=> Catel.Tests.Runtime.Serialization.RedirectDeserializationBinderFacts+ThePerformanceTests.PerformanceTestWithMultithreadedInitialization5000TypesPerThread()
Multithreaded initialization: 28,16616ms (average), 140,8308ms (total)
=> Catel.Tests.Runtime.Serialization.RedirectDeserializationBinderFacts+ThePerformanceTests.PerformanceTestWithMultithreadedInitialization500TypesPerThread()
Multithreaded initialization: 34,92608ms (average), 174,6304ms (total)
=> Catel.Tests.Runtime.Serialization.RedirectDeserializationBinderFacts+ThePerformanceTests.PerformanceTestWithoutMultithreadedInitialization()
Multithreaded initialization: 32,8773ms (average), 164,3865ms (total)

Tests Not Run

1) Explicit : Catel.Tests.Configuration.DynamicConfigurationFacts.CorrectlySerializesComplexObjects()
OneTimeSetUp:

2) Explicit : Catel.Tests.Configuration.DynamicConfigurationFacts.CorrectlySerializesConfiguration()
OneTimeSetUp:

3) Explicit : Catel.Tests.Configuration.DynamicConfigurationFacts.KnowsWhatPropertiesAreSetUsingDeserialization()
OneTimeSetUp:

4) Explicit : Catel.Tests.Configuration.DynamicConfigurationFacts.KnowsWhatPropertiesAreSetUsingSetConfigurationValue()
OneTimeSetUp:

5) Explicit : Catel.Tests.Configuration.DynamicConfigurationFacts.RegistersPropertiesFromSerialization()
OneTimeSetUp:

6) Explicit : Catel.Tests.IoC.TypeFactoryFacts+TheCreateInstanceWithAutoCompletionMethod.IfTypeFactoryIsCalledConcurrentlyItRunsFasterThanSerial()
OneTimeSetUp:

7) Explicit : Catel.Tests.Runtime.Serialization.GenericSerializationFacts+TheWarmupMethod.WarmsUpAllTypes()
OneTimeSetUp:

8) Explicit : Catel.Tests.Runtime.Serialization.GenericSerializationFacts+TheWarmupMethod.WarmsUpSpecificTypes()
OneTimeSetUp:

9) Explicit : Catel.Tests.Data.ChangeNotificationWrapperFacts+TheCollectionChangesLogic.HandlesChangesOfSuspendedFastObservableCollectionCorrectly()
OneTimeSetUp:

10) Explicit : Catel.Tests.Data.ChangeNotificationWrapperFacts+TheCollectionChangesLogic.HandlesClearOfSuspendedFastObservableCollectionCorrectly()
OneTimeSetUp:

11) Explicit : Catel.Tests.Data.ChangeNotificationWrapperFacts+TheCollectionChangesLogic.HandlesCollectionChangesCorrectly()
OneTimeSetUp:

12) Explicit : Catel.Tests.Data.ChangeNotificationWrapperFacts+TheCollectionChangesLogic.HandlesCollectionChangesCorrectlyInSuspensionModeMixedConsolidate()
OneTimeSetUp:

13) Explicit : Catel.Tests.Data.ChangeNotificationWrapperFacts+TheCollectionChangesLogic.HandlesCollectionItemPropertyChangesCorrectly()
OneTimeSetUp:

14) Explicit : Catel.Tests.Data.ChangeNotificationWrapperFacts+TheCollectionChangesLogic.HandlesCollectionResetsCorrectly()
OneTimeSetUp:

15) Explicit : Catel.Tests.Services.IPleaseWaitServiceExtensionsTests.PushInScope_CodeThrowsException_Hides
OneTimeSetUp:

16) Explicit : Catel.Tests.Services.IPleaseWaitServiceExtensionsTests.PushInScope_WithStatus_CodeThrowsException_Hides
OneTimeSetUp:

Errors, Failures and Warnings

1) Failed : Catel.Tests.Logging.Listeners.BatchLogListenerFacts+TheWriteBatchAsyncMethod.TestMultipleBatchesAsync(1000,0)
  The timer should have awaited the calls
  Expected: 0
  But was:  1
   at Catel.Tests.Logging.Listeners.BatchLogListenerFacts.TheWriteBatchAsyncMethod.<TestMultipleBatchesAsync>d__1.MoveNext() in C:\Users\Drachenkatze\source\repos\Catel\src\Catel.Tests\Logging\Listeners\BatchLogListenerFacts.cs:line 56
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

2) Failed : Catel.Tests.Data.IModelExtensionsFacts+TheClearIsDirtyOnAllChildrenMethod.DoesNotSuspendNotifications
  Expected: True
  But was:  False
   at Catel.Tests.Data.IModelExtensionsFacts.TheClearIsDirtyOnAllChildrenMethod.DoesNotSuspendNotifications() in C:\Users\Drachenkatze\source\repos\Catel\src\Catel.Tests\Data\Extensions\IModelExtensionsFacts.cs:line 117

3) Failed : Catel.Tests.Data.IModelExtensionsFacts+TheClearIsDirtyOnAllChildrenMethod.DoesSuspendNotifications
  Expected: True
  But was:  False
   at Catel.Tests.Data.IModelExtensionsFacts.TheClearIsDirtyOnAllChildrenMethod.DoesSuspendNotifications() in C:\Users\Drachenkatze\source\repos\Catel\src\Catel.Tests\Data\Extensions\IModelExtensionsFacts.cs:line 186
Run Settings
    RunAsX86: True
    DisposeRunners: True
    WorkDirectory: C:\Users\Drachenkatze\source\repos\Catel
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Failed
  Test Count: 2355, Passed: 2336, Failed: 3, Warnings: 0, Inconclusive: 0, Skipped: 16
    Failed Tests - Failures: 3, Errors: 0, Invalid: 0
    Skipped Tests - Ignored: 0, Explicit: 16, Other: 0
  Start time: 2019-02-20 16:20:36Z
    End time: 2019-02-20 16:22:47Z
    Duration: 130.741 seconds

Results (nunit3) saved as C:/Users/Drachenkatze/source/repos/Catel/output/Release/testresults/Catel.Tests/testresults.xml
An exception occurred: NUnit3: 3 test(s) failed (exit code 3).
An error occurred when executing task 'Test'.
Error: One or more errors occurred.
        Unit test execution failed
```

**Comment by GeertvanHorrik** [comment]
Cool, I noticed the build server also fails on the same tests. Great, then we have a repro and I can test a fix.

**Comment by GeertvanHorrik** [comment]
Can you check the latest alpha on MyGet to see if that fixes your issue?

**Comment by GeertvanHorrik** [comment]
Closing, feel free to re-open when it's not yet fixed.
