### ISSUE TITLE
Fix binding errors on UserControl for UWP

### ISSUE THREAD

**Issue by byrialsen** [Catel/Catel#1267]
After upgrading from Catel 5.8.0 -> 5.9.0 suddently I see problems with UserControl binding to its own viewmodel. The binding seems to be done on the ParentViewModel of the user control in the first place.
The binding ends up working though, but the error are annoying in the log and more important I might think that it broke something. I suspect that binding problems breaks shortcuts defined in the `ICommandManager`.

### Steps to reproduce

I have created a Repo [here](https://github.com/byrialsen/CatelUserControlProblems).

Please note that the repo uses Catel 5.7.0 to show you that it can run without binding errors and the F5 shortcut executes a command in the UserControls viewmodel. So everything is fine her.

Upgrade to Catel 5.9.0 and run it again. Now you see binding erros and F5 is not working anymore.

UWP version: Anniversary Update (14393) 

### Expected behaviour

It should be working as I does in 5.7.0.  (please note that even 5.8.0 is working in respect to binding, application wide shortcuts were broken in this version, but should be fixed back in 5.9.0)

### Actual behaviour

F5 shortcut not working. Binding logs these errors

```
Error: BindingExpression path error: 'FirstNames' property not found on 'CatelTest.Uwp.Ui.ViewModels.MainViewModel (ID = 0)'. BindingExpression: Path='FirstNames' DataItem='CatelTest.Uwp.Ui.ViewModels.MainViewModel (ID = 0)'; target element is 'Windows.UI.Xaml.Controls.TextBox' (Name='null'); target property is 'Text' (type 'String')
Error: BindingExpression path error: 'LastNames' property not found on 'CatelTest.Uwp.Ui.ViewModels.MainViewModel (ID = 0)'. BindingExpression: Path='LastNames' DataItem='CatelTest.Uwp.Ui.ViewModels.MainViewModel (ID = 0)'; target element is 'Windows.UI.Xaml.Controls.TextBox' (Name='null'); target property is 'Text' (type 'String')
Error: BindingExpression path error: 'TestCommand' property not found on 'CatelTest.Uwp.Ui.ViewModels.MainViewModel (ID = 0)'. BindingExpression: Path='TestCommand' DataItem='CatelTest.Uwp.Ui.ViewModels.MainViewModel (ID = 0)'; target element is 'Windows.UI.Xaml.Controls.Button' (Name='null'); target property is 'Command' (type 'ICommand')
```

**Comment by GeertvanHorrik** [comment]
Thanks for the repro, will try to figure out why this is happening.

**Comment by GeertvanHorrik** [comment]
Looks like the window is null when Catel tries to subscribe to the events.

**Comment by GeertvanHorrik** [comment]
The reason is `InvalidateCommandManagerOnViewModelInitializationAuditor`, it gets constructed too fast.

**Comment by GeertvanHorrik** [comment]
For the subscription for the events, see #1269

**Comment by GeertvanHorrik** [comment]
The subscriptions are fixed, now looking into the binding errors.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, it's fixed and will be available in the next alpha build of Catel (on myget).
