### ISSUE TITLE
Create VM Auditor to subscribe keyboard events instead of CommandManager constructor

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1269]

**Comment by GeertvanHorrik** [comment]
Since Catel creates auditors to invalidate commands, the ctor can no longer be used.

**Comment by GeertvanHorrik** [comment]
Done.

**Comment by taurenshaman** [comment]
UWP
Recently I update the lib from 5.3.0 to 5.10.0. When run the app, I got error:

> System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=System.Private.CoreLib
  StackTrace:
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Runtime.CompilerServices.ConditionalWeakTable`2.Add(TKey key, TValue value)
   在 Catel.ICommandManagerExtensions.SubscribeToKeyboardEvents(ICommandManager commandManager, Window window)
   在 Catel.MVVM.CommandManager.SubscribeToKeyboardEventsInternal()
   在 Catel.MVVM.CommandManager.SubscribeToKeyboardEvents()
   在 Catel.MVVM.Auditing.SubscribeKeyboardEventsOnViewModelCreationAuditor.OnViewModelCreated(IViewModel viewModel)
   在 Catel.MVVM.Auditing.AuditingManager.OnViewModelCreated(IViewModel viewModel)
   在 Catel.MVVM.Auditing.AuditingHelper.RegisterViewModel(IViewModel viewModel)
   在 Catel.MVVM.ViewModelBase..ctor(IServiceLocator serviceLocator, Boolean supportIEditableObject, Boolean ignoreMultipleModelsWarning, Boolean skipViewModelAttributesInitialization)
   在 Catel.MVVM.ViewModelBase..ctor()
   在 Lore.ViewModels.ViewModelBase..ctor() 在 F:\Projects\Lore\Lore.X\ViewModels\ViewModelBase.cs 中: 第 110 行
   在 Lore.ViewModels.ContainerViewModel..ctor() 在 F:\Projects\Lore\Lore.X\ViewModels\ContainerViewModel.cs 中: 第 20 行
   在 Lore.App.<Initialize>d__20.MoveNext() 在 F:\Projects\Lore-branch-no-chuci\Lore.UWP\App.xaml.cs 中: 第 135 行
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Lore.App.<OnLaunched>d__19.MoveNext() 在 F:\Projects\Lore-branch-no-chuci\Lore.UWP\App.xaml.cs 中: 第 85 行


ContainerView is a main NavigationView page.
I haven't changed the code yet. Just update the nuget. The following code is in App.xaml.cs (Line 119-136), and the line 135 is "the_container_vm = new ContainerViewModel();".

``` 

private async Task Initialize() {
      await ViewModels.ViewModelBase.InitializeWcfService();
      await ViewModelBridge.Initialize();
      ViewModelBridge.RefreshLocale();

      var dependencyResolver = this.GetDependencyResolver();
      //var serviceLocator = ServiceLocator.Default;
      //serviceLocator.RegisterType<IViewLocator, ViewLocator>();
      //serviceLocator.RegisterType<IViewModelLocator, ViewModelLocator>();
      //var viewLocator = serviceLocator.ResolveType<IViewLocator>();
      //var commandManager = dependencyResolver.Resolve<ICommandManager>();

      the_main_vm = new MainViewModel( //serviceLocator//,
                                       //serviceLocator.ResolveType<Catel.Services.IPleaseWaitService>(),
                                       //serviceLocator.ResolveType<Catel.Services.INavigationService>()
        );
      the_container_vm = new ContainerViewModel();
    }

```


Can you give me some advice? Should I initialize a Audit or CommandManager?
Thank you very much!

**Comment by GeertvanHorrik** [comment]
@taurenshaman , it hsould not happen, it should check for existing registrations. Can you please create a separate ticket that we can track so it can be fixed?

**Comment by taurenshaman** [comment]
#1339 
@GeertvanHorrik  Sorry....
