### ISSUE TITLE
AssemblyHelper.GetLoadedAssemblies(System.AppDomain) causes System.MissingMethodException in Xamarin.UWP

### ISSUE THREAD

**Issue by GreenKn1ght** [Catel/Catel#1289]
### Steps to reproduce

1. Clone [sample](https://github.com/GreenKn1ght/Catel.Xamarin.Forms.Todo/commits/master).
2. Run Catel.Xamarin.Forms.Todo.UWP

Platform:
Xamarin.UWP

My thoughts on why this happens: .NET Standard and UWP implementations of GetLoadedAssemblies(AppDomain) are different because the first one uses the System.AppDomain from System.Runtime.Extensions and the second one from Catel.Core.

**Comment by GeertvanHorrik** [comment]
Thanks for the repro, is this happening to the latest beta as well? Then I will make sure it's fixed there.

**Comment by GreenKn1ght** [comment]
Reproduced with Catel.MVVM.Xamarin.Forms 5.10.0-beta0008.

**Comment by GeertvanHorrik** [comment]
Can repro for UWP:

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<System.Reflection.Assembly> Catel.Reflection.AssemblyHelper.GetLoadedAssemblies(System.AppDomain)'.
   at Catel.Xamarin.Forms.Todo.App..ctor()
   at Catel.Xamarin.Forms.Todo.UWP.MainPage..ctor()
   at Catel.Xamarin.Forms.Todo.UWP.Catel_Xamarin_Forms_Todo_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage()
   at Catel.Xamarin.Forms.Todo.UWP.Catel_Xamarin_Forms_Todo_UWP_XamlTypeInfo.XamlUserType.ActivateInstance()

```

**Comment by GeertvanHorrik** [comment]
Compiled assemblies do contain the type and method.

**Comment by GeertvanHorrik** [comment]
Migrated extension methods in the Xamarin.Forms project to non-extension methods, now it works. Looks like type redirecting doesn't work as it should in the compiler?

**Comment by GeertvanHorrik** [comment]
Should be fixed in Build - 5.10.0-beta.11

**Comment by GreenKn1ght** [comment]
> Compiled assemblies do contain the type and method.

You're right, but those methods are different in .NETStandard and UWP implementations.

**Comment by GeertvanHorrik** [comment]
To be honest I don't see the difference, there are no directives around the extension methods on this assemblyhelper class.

**Comment by GreenKn1ght** [comment]
As I said,

> NET Standard and UWP implementations of GetLoadedAssemblies(AppDomain) are different because the first one uses the System.AppDomain from System.Runtime.Extensions and the second one from Catel.Core.

**Comment by GeertvanHorrik** [comment]
Oops, totally missed that, sorry :)

**Comment by GreenKn1ght** [comment]
Tested 5.10.0-beta.11 and got same exception.

**Comment by GeertvanHorrik** [comment]
Correct, you need not to use the extension method, Catel will take care of that for you (basically you should not call it yourself).

**Comment by GreenKn1ght** [comment]
Forgot to delete this line :)

**Comment by GeertvanHorrik** [comment]
Let me know if it works for you, if not, we can figure something out.

**Comment by GreenKn1ght** [comment]
Yes, it works, thanks for the help!
