### ISSUE TITLE
ViewModelLifetimeManagement.PartlyManual and NavigationContext.Values problem

### ISSUE THREAD

**Issue by emigranto** [Catel/Catel#1297]
Platform:
.NET version: UWP, .net standart 2.x

### Expected behaviour

If use method INavigationService.Navigate with parameters, when ViewModelLifetimeManagement = ViewModelLifetimeManagement.PartlyManual. When calling the method again with new parameters, the key contains new value in NavigationContext.Values

### Actual behaviour

If use method INavigationService.Navigate with parameters, when ViewModelLifetimeManagement = ViewModelLifetimeManagement.PartlyManual. When calling the method again with new parameters, the key contains old value in NavigationContext.Values

**Comment by GeertvanHorrik** [comment]
Since it's partly manual, you are responsible for closing / making sure that the vm can be re-used.

**Comment by emigranto** [comment]
Ok. How can I submit a new parameter without closing vm

**Comment by emigranto** [comment]
Problem is solved.
