### ISSUE TITLE
DataWindow does not dispose IDisposable ViewModels

### ISSUE THREAD

**Issue by vaecors** [Catel/Catel#1302]
### Steps to reproduce

1. Create ViewModel that implements IDisposable
2. Create associated DataWindow for ViewModel
3. Instantiate DataWindow via UIVisualizationService
4. Close Window

Platform:
.NET version: 4.7.2

### Expected behaviour

IDisposable.Dispose() method should be called upon closing of window.

### Actual behaviour

IDisposable.Dispose() is never called. The current workaround is to override DataWindow.OnViewModelClosedAsync(), conditionally cast ViewModel to IDisposable and call Dispose().

_Note: Debugging showed that this only seems to affect children windows._

### Feature description

WindowLogic should implement a behavioral pattern similar to #1143 in checking if a ViewModel implements IDisposable during close. I am willing and able to take ownership of this and send in pull request if desired.

**Comment by GeertvanHorrik** [comment]
Excellent point, thanks for the research. Interested in doing a PR?

**Comment by vaecors** [comment]
Absolutely I am more than happy to do a PR, however there is one caveat I did discover while testing out this pattern. There is one scenario where this could cause a slight headache for an implementer with regards to ShowDialog.

So a user creates a DataWindow and associated ViewModel with all the necessary Properties then instantiates it via ShowDialogAsync. However because the ViewModel implements IDisposable, as soon as WindowLogic disposes of it the ViewModel is gone.

If the user attempts to access Properties from that ViewModel from the parent ViewModel that instantiated it, they will get a NullReferenceException in ViewModel itself. Normally one would use a shared persist Service to swap information between the two ViewModels but I have seen patterns in the past of a Parent access properties of the Child in this fashion by instantiating the ViewModel with a TypeFactory and passing it to the UI Service handling Show/ShowDialog.

So my concern is a bug report being created because an implementer has an IDisposable ViewModel, uses ShowDialog and then expects to get the information from that ViewModel after the dialog is destroyed and wondering why they got a NullReferenceException.

The only comfortable solution I have for that is really just a documentation update. What are your thoughts?

**Comment by GeertvanHorrik** [comment]
It's not actually "gone", it's just disposed, meaning it no longer has access to (un)managed resources. It doesn't mean that the properties (e.g. the selection done in the window) are also gone. Users should have cleaned up their event handlers, etc in `CloseAsync` anyway, but maybe I am overseeing something?

**Comment by vaecors** [comment]
Honestly I may be overthinking the issue. I'll know better when I implement the unit tests against the change and see what happens.
