### ISSUE TITLE
[Feature]: EventArgsConverter in EventToCommand

### ISSUE THREAD

**Issue by vaecors** [Catel/Catel#1308]
### Preamble

When developing an application, it is usually inevitable that a View type of event has to be handled and a routine within the ViewModel has to be called. Depending on this event there are generally two pathways in which this handled:

**Direct Implementation**
Event is implemented in the View code-behind and the ViewModel is not required as part of the interaction (a service might be though)

**Mixed-Mode Implementation**
Event is implemented in the View code-behind and the ViewModel is required. Implementations such as this come in two types, unidirectional and bidirectional. Unidirectional implementations are for when you need short-circuit the event based on event conditions before passing a call to the ViewModel and do not want to leak the event types to the ViewModel. Bidirectional implementations are where you need to manipulate properties within an Event using results from a method executed in the ViewModel. An example of this would be [DistinctValuesLoading Event](https://docs.telerik.com/devtools/wpf/controls/radgridview/filtering/how-to/howto-display-all-distinct-values) from Telerik's RadGridView.

**EventToCommand Converter**
Event is implemented in the ViewModel as the View is not directly dependent on it. A primitive example would be any **Loaded** event for a **UIFrameworkElement** type object. However there is an inherit downside with this implementation if one must use the **PassEventArgsToCommand** dependency property if for whatever reason **CommandParameter** cannot be used against a require set of object parameters due to limitations within the UI framework of choice.

The downside is that View-level events get exposed into the ViewModel which means the ViewModel is no longer agnostic to the View implementation. That's where this feature idea comes in.

### Feature description

The premise of this is feature is quite straight forward hopefully, the concept is a Dependency Property called **EventArgsConverter** would be introduced within **EventToCommand** that allows an implementer to introduce basically an object bridge between the View and ViewModel that would convert any **EventArgs** implementation into a neutral object that the ViewModel can assimilate. 

There are some limitations to this feature however, while it can help eliminate the need to implement code for a Mixed-Mode Unidirectional implementation and clean-up the platform locking that may occur with an EventToCommand implementation, it would not support Mixed-Mode Bidirectional implementations (though this can be solved using a Service). 

I have personally implemented something like this before so I am familiar with the concept, whether or not you feel it has any value to be added to the Framework in a vNext release I'll leave up to you.

**Comment by GeertvanHorrik** [comment]
Sounds like a great plan! Interested in doing a PR?

**Comment by vaecors** [comment]
Absolutely, however I should note that right now I am having complications compiling Catel within the VM I setup for it. I'm entirely sure it's localized in my environment as I cannot compile in VS2019 directly without a load of reference errors and build.ps1 is complaining about missing targets so I need to resolve that first before I can task out the feature.

**Comment by GeertvanHorrik** [comment]
You probably need to install .net core sdk (Master
(3.0.x Runtime), from https://github.com/dotnet/core-sdk#installers-and-binaries). I could be possible that you would need a prerelease version of vs (e.g. vs 2019 prerelease) to use the prerelease of .net core.

**Comment by vaecors** [comment]
That I do have installed as far as I recall but that wasn't the only issue, when compiling within VS2019 it was throwing reference errors such as Dictionary<,> could not be resolved (net46 and uap10) and so forth. When compiling with cake it complained about missing targets (which I do not recollect). 

My plan was basically just to destroy the VM, build a new one, take a snapshot and try and nail down what parts of VS2019 I could be missing during the install. I don't normally do Xamarin or UWP development so I almost never install those components and most likely missed something.

**Comment by GeertvanHorrik** [comment]
Right, I fixed that about 20 minutes ago, was a repository template issue for UWP.

**Comment by vaecors** [comment]
Ah I see the merge, I'll do a synchronization tonight and a compile test to see if that resolves it.

**Comment by vaecors** [comment]
Just to give you an update, it appears what I cannot compile via build.ps1 is Catel.Templates because its unable to find the props files. I've just disabled that solution for now as it's not critical for this PR. I was able to get Catel installed after installing the proper Windows 10 SDK version (the one I had installed as too new).

I'll start work on the PR this weekend, should take about a week or so.

**Comment by vaecors** [comment]
I'm afraid I'm going to have to put this PR on hold for right now. I am unfortunately unable to get Catel to compile in its environment successfully. I've done several different installation and configurations for VS2019. Attempting to build via Cake results in MSB1001 (unknown switch for binary logging) errors and attempting to compile in VS2019 directly results reference errors which throw for every platform target.

If at some point I can successfully get the build going I'll work on the PR.

**Comment by GeertvanHorrik** [comment]
No problems, I will try to work on this PR. It's always the same with MS, you either be upfront and add support for .NET Core (without decent tooling) or you're too late... So now we are in an "in-between" situation that might not work for everyone...

**Comment by GeertvanHorrik** [comment]
@vaecors is there a way to contact you privately? Could you send me an email at geert [@] catenalogic?

**Comment by vaecors** [comment]
> No problems, I will try to work on this PR. It's always the same with MS, you either be upfront and add support for .NET Core (without decent tooling) or you're too late... So now we are in an "in-between" situation that might not work for everyone...

It wouldn't be fair to throw that type of work over the fence to you due to some wonky environmental issue that appears to only be localized to me. I'm sure once we figure out what on earth Microsoft did this time with the toolchain I'll be able to compile. It feels like its just a Windows SDK problem on one end but an MSBuild issue on another end (for something supposedly fixed in MSBuild 15.6).

> @vaecors is there a way to contact you privately? Could you send me an email at geert [@] catenalogic?

Let me compile verbose outputs from both VS2019 Build and Cake and I'll email them to you so we can take this discussion offline and way from the issue. You may see something I missed. I am still very sure its just a silly environmental issue and I'm missing some obscure "feature" install because of a silly tool change.
