### ISSUE TITLE
Add TypeCacheEvaluator separate to TypeCache to allow customization of already loaded assemblies

### ISSUE THREAD

**Issue by GreenKn1ght** [Catel/Catel#1324]
TypeCache initialization takes about 2 out of 10 seconds of startup time. This time is significantly increased on weak devices.
Xamarin.Android eagerly loads all assemblies. This means that in our application TypeCache processing 114 assemblies at startup. This causing pretty large impact on performace. And we can't even ignore assemblies (or types) by TypeCache.ShouldIgnoreAssemblyEvaluators (or ShouldIgnoreTypeEvaluators) because initialization starts automatically by ModuleInitializer or by ServiceLocator.Default, though call of this property will execute static ctor anyway.

Platform: Xamarin.Android 9.1

**Comment by GeertvanHorrik** [comment]
Good point, I had something similar with UWP apps. I did some additional work around the initialization there. 114 assemblies is a lot to process though, let me check if I can think of something that can work around this.

**Comment by GeertvanHorrik** [comment]
What if we could create a new type called TypeCacheEvaluator. This won't load anything, and will be loaded in the static ctor of TypeCache, but will be able to be customized before the static ctor hits the existing assemblies.

**Comment by GeertvanHorrik** [comment]
Releasing Build - 5.11.0-alpha.54, you should be able to update `TypeCacheEvaluator` before the `TypeCache` kicks in.

**Comment by GreenKn1ght** [comment]
I can not profile the application right now, so I'm trying to find out if it works by other signs.

**Comment by GreenKn1ght** [comment]
By the way, something is messed up here: InitializeAssemblies adds ignored assemblies to _loadedAssemblies and does not log about it; OnAssemblyLoaded does not add ignored assemblies to _loadedAssemblies and logs about it.

**Comment by GreenKn1ght** [comment]
I ignored all assemblies (TypeCacheEvaluator.AssemblyEvaluators.Add (assembly => true) at entry point).
TypeCache.GetTypes (allowInitialization: false) returns 23000 types. I'm believe there should be 0.

**Comment by GeertvanHorrik** [comment]
Good points. I was also thinking, maybe we should have autoLoad and explicitLoad assemblies.

**Comment by GreenKn1ght** [comment]
When and where ModuleInitializer is called? I know about Fody.ModuleInit, but how it actually works? Could it be that ModuleInitializer is called before my code runs?

**Comment by GeertvanHorrik** [comment]
As soon as the assembly is loaded into the appdomain. But it doesn't necessarily load the assemblies just yet. Only whenever the TypeCache type is used, so you *should* be able to customize the TypeCacheEvaluator upfront. Maybe it's Catel.MVVM resolving it first?

**Comment by GeertvanHorrik** [comment]
For related code, see:

https://github.com/Catel/Catel/blob/develop/src/Catel.Core/ModuleInitializer.cs
https://github.com/Catel/Catel/blob/develop/src/Catel.Core/CoreModule.cs

https://github.com/Catel/Catel/blob/develop/src/Catel.MVVM/ModuleInitializer.cs
https://github.com/Catel/Catel/blob/develop/src/Catel.MVVM/MVVMModule.cs

**Comment by GreenKn1ght** [comment]
As I mentioned, Xamarin.Android eagerly loads (i.e. preloads) assemblies. So yes, when my code runs, they are already loaded into AD.

**Comment by GreenKn1ght** [comment]
Hm, I can try to put my code into ModuleInit, but not sure if I should rely on loading order or not =/

**Comment by GeertvanHorrik** [comment]
There is no order reload, but again, technically the code *shouldn't* invoke TypeCache. I will try to debug this tomorrow.

**Comment by GeertvanHorrik** [comment]
But even if they are loaded, the module init code of Catel should not invoke any TypeCache stuff if I am not mistaken. Now trying to investigate this.

**Comment by GreenKn1ght** [comment]
I read the code again and here is a chain of method calls:
ModuleInitializer.Initialize() -> 
ServiceLocator.Default -> 
IoCConfiguration.DefaultServiceLocator -> 
IoCConfiguration.UpdateDefaultComponents() -> 
IoCFactory.CreateServiceLocator() -> 
static IoCFactory() ctor ->
TypeCache.AssemblyLoaded += -> 
static TypeCache ctor.

**Comment by GeertvanHorrik** [comment]
I will move the default initialization call to the first typecache call (making it a bit easier to control).

**Comment by GeertvanHorrik** [comment]
Please try Build - 5.11.0-alpha.58

**Comment by GreenKn1ght** [comment]
At first glance it works well.
Profiling will take a while.

**Comment by GreenKn1ght** [comment]
By the way, which assemblies I shouldn't ignore so that Catel works most efficiently?

**Comment by GeertvanHorrik** [comment]
If you don't need the serialization engine for system types, you could ignore anything that starts with "System." and see if that boosts performance.

**Comment by GreenKn1ght** [comment]
Even if I don't ignore anything, TypeCache.InitializedAssemblies contains only 17 assemblies. Looks like great optimization! All of them starts with "System." except Mono.Security. Can't say why Mono.Security got into TypeCache. I think I'll ignore them all.

```csharp
var assemblies = TypeCache.GetTypes(allowInitialization: false).Select(x => x.Assembly.FullName).Distinct();
var except = assemblies.Except(TypeCache.InitializedAssemblies).ToList();
```
It is interesting that _except_ isn't empty: it contains assembly of app (view and view models are here).

**Comment by GeertvanHorrik** [comment]
Yes, we sometimes do forced initialization of required assemblies (e.g. we definitely need the app assembly). Glad it's working much better for you, thanks for reporting. Let me know if this needs further work, or feel free to close it if it's solved to your satisfaction.

**Comment by GreenKn1ght** [comment]
Thanks for the fix.
