### ISSUE TITLE
Don't throw exception in UIVisualizerService when same view is being re-registered multiple times

### ISSUE THREAD

**Issue by Aitania** [Catel/Catel#1337]
Hallo,

i have read the documentation about closing viewmodels.
https://catelproject.atlassian.net/wiki/spaces/CTL/pages/2359356/Viewmodel+lifetime+example

I use MEF to control the view of my application.
Thru a button "Open A" and "Open B" i have a MainViewA/MainViewModelA and MainViewB/MainViewModelB which are loaded from exported Parts PluginA.dll and PluginB.dll

The Exported Parts are defined as NonShared (a new instance of Part will be created)
    [Export(typeof(InternalShared.IRibbon)), PartCreationPolicy(CreationPolicy.NonShared)]
    [ExportMetadata("Name", "PluginA")]

So i have a application which behave like a A or like B (MainView and Ribbon).

If i klick "Open A" the aplication loads PluginA and it works fine.
If i klick "Open A" again the constructor of MainViewA is called again (CreationPolicy.NonShared), That makes all initialisation of MainViewA/MainViewModelA again, that is what i want...

PROBLEM: in Constructor of MainViewA i have an error:
{"View model already registered"}  at
Catel.Services.UIVisualizerService.Register(String name, Type windowType, Boolean throwExceptionIfExists) at PluginA.ViewModels.MainViewModelA..ctor()

Is it possible to close/unregister the MainViewA via MainViewModelA programmatically OR Initialize the MainViewA so that i have a initilized Model of PluginA like at startup?

Platform: Win 7  -  .NET version: 4.6  -  Catel version: 4.5.4.0

**Comment by GreenKn1ght** [comment]
AFAIK, ViewModelBase and UserControl/Window do not register anything, so it looks like you are trying to manually register a MainViewA and MainViewModelA in the constructor MainViewModelA. Is that so?

**Comment by GeertvanHorrik** [comment]
Looks like this is the registration in the UIVisualizerService itself (it sorts of caches the views it found based on a view model). Maybe we can simply ignore a registration *if it's the same*.

**Comment by GeertvanHorrik** [comment]
Should be fixed in Build - 5.11.0-alpha.84

**Comment by Aitania** [comment]
That will be nice to fix in Build 5x. That will not help me.
I use Catel version: 4.5.4.0 and at the momment i don't want to upgrade for more than one reason.
I will do this later on. At the momment i have a stable Catel framework.
I have tried to update early at this year. I had problems with components which are not suitable to each other. Fody and .NET Core update of the components  was one of these...
In addition i like the old IPleaseWaitService.

**Comment by GeertvanHorrik** [comment]
We don't support < 5, especially not unpaid support. We use Catel 5.x ourselves in over 100 apps and libs, it's working very solid so the only sensible thing I can recommend is to take time to upgrade. We do provide support plans via Open Collective to help you out with the migration if needed.

**Comment by GeertvanHorrik** [comment]
Fixed, closing ticket.
