### ISSUE TITLE
Add instance to the TypeInstantiatedEventArgs

### ISSUE THREAD

**Issue by ttustonic** [Catel/Catel#1342]
*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description
It would be nice to have an instance in the TypeInstantiatedEventArgs, similar to the one in TypeUnregisteredEventArgs.

**Comment by GeertvanHorrik** [comment]
Good idea. Interested in doing a PR?

**Comment by ttustonic** [comment]
Yes, in a day or two.

BTW, how do you feel about raising type instantiated event when resolving instances and types resolved with CanResolveNonAbstractTypesWithoutRegistration ? It would make it consistent.

**Comment by GeertvanHorrik** [comment]
Fast day or two :-)

I think I agree on the event for non-abstract types.
