### ISSUE TITLE
Set tag when resolving via MissingType event

### ISSUE THREAD

**Issue by ttustonic** [Catel/Catel#1344]
### Feature description

Currently, when resolving using `MissingType` event, the tag in the `MissingTypeEventArgs `is not set (always null), so `MissingType `event handler can only create default instances/implementations.

**Comment by GeertvanHorrik** [comment]
Good catch! Interested in doing another PR?

**Comment by ttustonic** [comment]
Yes. 

However, I'm not certain what to do in the `IsTypeRegisteredWithOrWithoutTag` method. In there you are just comparing `serviceType` values in the registered `ServiceInfo `objects (ignoring tags if any). However, I don't think that I should just go on and ignore tags when registering a new services via `MissingType` event

**Comment by GeertvanHorrik** [comment]
I think it's fair to assume that if someone uses "IsTypeRegisteredWithOrWithoutTag", and *nothing* is registered, it's sufficient to register a default one. If not, developers can always pre-register it as a "workaround".
