### ISSUE TITLE
ModelBase changes rollback (IEditableObject) doesn't work with JsonSerializer

### ISSUE THREAD

**Issue by ArXen42** [Catel/Catel#1371]
### Steps to reproduce

1. Create any model derived from `ModelBase`
2. Attempt to use IEditableObjectFunctionality (for example from DataWindow)

Platform: WPF
.NET version: 4.7

### Expected behaviour

Should probably work the same way as with XML serializer.

### Actual behaviour

It just does not restore any properties. I have debugged the following code from `ModelBase` and it seems that nothing is actually deserialized from `_propertyValuesBackup`, though it certainly contains something. 

```cs
/// <summary>
/// Restores the backup to the object.
/// </summary>
public void RestoreBackup()
{
    Dictionary<string, object> oldPropertyValues = null;

    using (var stream = new MemoryStream(_propertyValuesBackup))
    {
        try
        {
            var properties = new List<MemberValue>();

            if (_serializer != null)
            {
                properties = _serializer.DeserializeMembers(_object, stream, null); // <---
                // won't contain anything when using JsonSerializer
            }

            oldPropertyValues = properties.ToDictionary(property => property.Name, property => property.Value);
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to deserialize the data for backup");
        }
    }

    if (oldPropertyValues is null)
    {
        return;
    }

    foreach (var propertyValue in oldPropertyValues)
    {
        if (PropertyDataManager.IsPropertyRegistered(_object.GetType(), propertyValue.Key))
        {
            // Set value so the PropertyChanged event is invoked
            _object.SetValue(propertyValue.Key, propertyValue.Value);
        }
    }

    _object.IsDirty = (bool)_objectValuesBackup[nameof(IsDirty)];
}
```

Attached repro containing model with a single boolean property and corresponding ViewModel/DataWindow. The "Cancel" button won't cancel changes on model. Works fine when commenting out JsonSerializer registration from `App.xaml.cs`.

Same results when calling IEditableObject.BeginEdit/CancelEdit manually.

[CatelTest.zip](https://github.com/Catel/Catel/files/3387623/CatelTest.zip)

**Comment by GeertvanHorrik** [comment]
Thanks for the repro. We will see if we can add this to the beta which is about to be released.

**Comment by GeertvanHorrik** [comment]
Adding unit tests trying to reproduce.

**Comment by GeertvanHorrik** [comment]
Unit tests for CancelEdit are now executed against all serializers.

**Comment by GeertvanHorrik** [comment]
Can repro with unit test, now working on a fix.

**Comment by GeertvanHorrik** [comment]
Unit test succeeds, now let's check whether we didn't break anything else.

**Comment by GeertvanHorrik** [comment]
Build - 5.11.0-beta.1 should contain the fix, ETA 20 minutes.

**Comment by GeertvanHorrik** [comment]
Closing the ticket. If you feel it's not solved, feel free to re-open.
