### ISSUE TITLE
Object reference not set to an instance at design time when calling UserControl.AddChild

### ISSUE THREAD

**Issue by SelvinPL** [Catel/Catel#1374]
After fix for https://github.com/Catel/Catel/issues/1260 we get `Object reference not set to an instance` in designer
 
code is still here
https://github.com/SelvinPL/CatelBug

the solution is to 

either add `DesignerProperties.GetIsInDesignMode(this)` (but is only WPF)

        protected override void AddChild(object value)
        {
            // Fix for https://github.com/Catel/Catel/issues/1260, make sure to create the grid first (and we force it, this
            // might be a non-xaml (e.g. non-InitializeComponent) control
            if (!DesignerProperties.GetIsInDesignMode(this))
            {
                var wrapper = _logic.CreateViewModelWrapper(true);
                if (wrapper != null)
                {
                    // Pass on to the grid
                    ((IAddChild)Content).AddChild(value);
                    return;
                }
            }
            base.AddChild(value);
        }

or expose `base.AddChild(..)` like

        protected void AddChildWithoutWrapper(object value)
        {
            base.AddChild(value);
        }

so it could be called in derived class like 

            if (!DesignerProperties.GetIsInDesignMode(this))
                AddChild(grid);
            else
                AddChildWithoutWrapper(grid);

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We will see if we can put this into 5.11 beta.

**Comment by GeertvanHorrik** [comment]
AddChild is a WPF || NETCORE feature only, so I will try to add this safety code inside Catel itself.

**Comment by GeertvanHorrik** [comment]
Done, thanks for the initial research and the multiple fixes offered. It's fixed inside Catel itself.

**Comment by GeertvanHorrik** [comment]
Build - 5.11.0-beta.5 will contain the fix (ETA 20 minutes, depending on how fast NuGet indexes the new packages).

**Comment by SelvinPL** [comment]
yeap, it's working now
