### ISSUE TITLE
WPF UserControl using Catel VSIX installer has unmet dependencies in Visual Studio 2019 Enterprise

### ISSUE THREAD

**Issue by jeffu231** [Catel/Catel#1378]
VS 2019 has all the normal dependencies installed to conduct WPF development. Applicable snippets from the VSIX log.

7/25/2019 10:46:24 AM - Initializing Install...
7/25/2019 10:46:24 AM - Extension Details...
7/25/2019 10:46:24 AM - 	Identifier         : Catel.ItemTemplates.WPF.UserControl..8fe638ab-9d4a-4d86-9099-50ba996cccbc
7/25/2019 10:46:24 AM - 	Name               : WPF UserControl using Catel
7/25/2019 10:46:24 AM - 	Author             : Geert van Horrik
7/25/2019 10:46:24 AM - 	Version            : 5.0
7/25/2019 10:46:24 AM - 	Description        : Item template to create a WPF UserControl using Catel.
7/25/2019 10:46:24 AM - 	Locale             : en-US
7/25/2019 10:46:24 AM - 	MoreInfoURL        : http://www.catelproject.com/
7/25/2019 10:46:24 AM - 	InstalledByMSI     : False
7/25/2019 10:46:24 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
7/25/2019 10:46:24 AM - 
7/25/2019 10:46:24 AM - 	SignatureState     : Unsigned
7/25/2019 10:46:24 AM - 	Supported Products : 
7/25/2019 10:46:24 AM - 		Microsoft.VisualStudio.Pro
7/25/2019 10:46:24 AM - 			Version : [11.0,)
7/25/2019 10:46:24 AM - 		Microsoft.VisualStudio.VSWinExpress
7/25/2019 10:46:24 AM - 			Version : [11.0,)
7/25/2019 10:46:24 AM - 		Microsoft.VisualStudio.VSWinDesktopExpress
7/25/2019 10:46:24 AM - 			Version : [11.0,)
7/25/2019 10:46:24 AM - 
7/25/2019 10:46:24 AM - 	References         : 
7/25/2019 10:46:24 AM - 	Prerequisites      : 
7/25/2019 10:46:24 AM - 		-------------------------------------------------------
7/25/2019 10:46:24 AM - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
7/25/2019 10:46:24 AM - 		Name         : .NET desktop development tools
7/25/2019 10:46:24 AM - 		Version      : [15.0.26621.2,16.0)
7/25/2019 10:46:24 AM - 
7/25/2019 10:46:24 AM - Signature Details...
7/25/2019 10:46:24 AM - 	Extension is not signed.

7/25/2019 10:46:25 AM - The extension with ID 'Catel.ItemTemplates.WPF.UserControl..8fe638ab-9d4a-4d86-9099-50ba996cccbc' is not installed to Microsoft Visual Studio Enterprise 2019.
7/25/2019 10:46:27 AM - Extension cannot be installed to the following products due to missing prerequisites:
7/25/2019 10:46:27 AM - 	Microsoft Visual Studio Enterprise 2019
7/25/2019 10:46:27 AM - 		-------------------------------------------------------
7/25/2019 10:46:27 AM - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
7/25/2019 10:46:27 AM - 		Name         : .NET desktop development tools
7/25/2019 10:46:27 AM - 		Version      : [15.0.26621.2,16.0)
7/25/2019 10:46:27 AM - 		Error        : The prerequisite version specified does not match the version installed
7/25/2019 10:46:27 AM - 
7/25/2019 10:46:43 AM - InstallProgressPage ChangeType: 'SingleTarget' operationCount: '2' Text: 'Modifying Microsoft Visual Studio Enterprise 2019...'
7/25/2019 10:46:43 AM - The following target products have been selected...
7/25/2019 10:46:43 AM - 	Microsoft Visual Studio Enterprise 2019

**Comment by GeertvanHorrik** [comment]
Looks like we need to remove the top-end constraint.

**Comment by GeertvanHorrik** [comment]
Updated the templates to the latest standards.

**Comment by GeertvanHorrik** [comment]
Moved to separate repository (see https://github.com/catel/catel.templates)

**Comment by GeertvanHorrik** [comment]
New templates should be available. Note that the ids have changed. Will close this ticket, feel free to re-open when not fixed.
