### ISSUE TITLE
CommandManager.CreateCommandWithGesture does not create CommandContainer

### ISSUE THREAD

**Issue by ttustonic** [Catel/Catel#1383]
### Steps to reproduce

1. Run attached console program

Platform:
.NET version: 4.7.2
Catel version: 5.11

### Expected behaviour

An instance of `FileOpenCommandContainer` should be created, `Constructed `event should be raised.

### Actual behaviour

Works in Catel 5.10, does not work in 5.11
The same happens  in Catel.Examples (`WpfCommanding`). `GlobalActionCommandContainer `
and others are created with 5.10 and not created with 5.11

Attached is a unit test which WORKS(!) in both versions, and a console program which doesn't.

[tests.zip](https://github.com/Catel/Catel/files/3447095/tests.zip)

**Comment by ArXen42** [comment]
Can confirm. Tried 5.11 beta 1-2 weeks ago, all application-wide commands were already disabled back then (thought some bug during update on my side), same behaviour now on stable 5.11.

**Comment by ArXen42** [comment]
The following query from `ICommandManagerExtensions` won't return user-defined commands, only `Catel.CommandContainerBase` and, if Orchestra is used, `Orchestra.ToggleConfigurationCommandContainerBase` commands.

```cs
var commandContainerType = (from type in TypeCache.GetTypes(allowInitialization: false) //<-- here
                                where string.Equals(type.Name, commandContainerName, StringComparison.OrdinalIgnoreCase)
                                select type).FirstOrDefault();
```

However, after changing the value of parameter `allowInitialization` to `true`, query will return user-defined commands as well.

Possibly somehow related to May commits that changed something in TypeCache.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. Will see if I can get a hotfix out.

**Comment by ArXen42** [comment]
It seems that it also affected JSON serialization. On a screenshot there is part of `JsonSerializer` that attempts to load type from cache by name (the name is normal concrete model type full name), but returns null.
![image](https://user-images.githubusercontent.com/10744285/62537812-07dcf780-b85a-11e9-9fce-253a9b13e82c.png)

**Comment by GeertvanHorrik** [comment]
You can always work around this by calling `TypeCache.Initialize` manually at startup.

**Comment by GeertvanHorrik** [comment]
I need to investigate why I made this change (maybe to speed up UWP app performance), then will evaluate what's the best option.

**Comment by GeertvanHorrik** [comment]
It's probably caused by #1324 , but that's a good change. Will see if I can work around it for this ticket.

**Comment by GeertvanHorrik** [comment]
Please try Build - 5.11.1-beta.144 for the *CommandManager* issue. I think I will keep the recommendation to manually initialize the TypeCache before serialization manually (then you can decide when the "hit" on your app should take place).

**Comment by ttustonic** [comment]
Yes, it seems OK.
