### ISSUE TITLE
ViewModelCommandManager.OnViewModelCommandExecuted can throw KeyNotFoundException with multiple threads

### ISSUE THREAD

**Issue by abuchanan-hs** [Catel/Catel#1393]
Our application on rare occasions throws the following exception:
2019-08-08 10:00:20.042 -04:00 Unhandled AppDomain exception. [Error] (1)
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Catel.MVVM.ViewModelCommandManager.<OnViewModelCommandExecuted>d__15.MoveNext()

### Steps to reproduce
We have not found a way to reproduce the bug.  We think it occurs when closing both a child window launched in a TaskCommand, and the parent window from different threads in certain (rare) thread/timing conditions.

Platform: WPF / Windows desktop
.NET version:  targeting .NET 4.5.2 (running on Client Framework 4.6.2)

### Expected behaviour
The lock (_lock) block in OnViewModelCommandExecuted should be extended around _command to prevent the exception.

### Actual behaviour
I believe there is a race condition where OnViewModelCommandExecuted begins executing, and is interrupted such that OnViewModelClosedAsync executes and clears the _commands object.  When the call stack returns to OnViewModelCommandExecuted and uses _commands outside the lock(_lock) block it is now empty and the exception is thrown.

I have not come up with a way to prove this, but I based on a code review I think this is a hole in the existing implementation.

Not a bug, but I can't find code that adds to the _commandHandlers object.  _commandHandlers and all code related to it can be removed from the class.  (only _asyncCommandHandlers is used)

**Comment by GeertvanHorrik** [comment]
Interested in doing a PR? We could do this as a hotfix and release Catel 5.11.2

**Comment by GeertvanHorrik** [comment]
Great findings! It's actually a performance improvement as well (probably not noticeable) to only retrieve the command name once.

**Comment by GeertvanHorrik** [comment]
Please see https://github.com/Catel/Catel/commit/41b78d185587c06e43ee8d04d742610e955f6daf

I think the fix is correct, will release hotfix once you've double-checked.
