### ISSUE TITLE
Logging in TypeFactory uses wrong parameter name

### ISSUE THREAD

**Issue by lipchev** [Catel/Catel#1408]
Not a big deal but given how old this class is it seems appropriate to point out.. 

https://github.com/Catel/Catel/blob/6ea8eeb54978f8e6c1b75bb5d68129bcb748a711/src/Catel.Core/IoC/TypeFactory.cs#L397

**Comment by GeertvanHorrik** [comment]
Thanks for reporting!

**Comment by GeertvanHorrik** [comment]
Fixed.
