### ISSUE TITLE
Warning on .Net Core 3 and Expression.Blend.Sdk.WPF 1.0.1

### ISSUE THREAD

**Issue by RCP161** [Catel/Catel#1415]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ X] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ X] .NET Core

## Component

What component is this issue occurring in?
- Catel.MVVM

## Version of Library
- 5.11.2

## Version of OS(s) listed above with issue
- .Net Core 3.0.100-preview8-013656
- WPF 3.0.6920.4902

## Steps to Reproduce
1. Create .Net Core 3 ContronlLibrary or so
2. Add Calte.MVVM 5.11.2
3. Warning is shown (see below)

## Expected Behavior

No warning

## Actual Behavior

Warning is shown. It's still working! This is more an information for you.

Package 'Expression.Blend.Sdk.WPF 1.0.1' was restored using '.NETCoreApp,Version=v3.0' instead the project target framework '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8'. This package may not be fully compatible with your project.

**Comment by GeertvanHorrik** [comment]
I don't think there is a .net core 3.0 package yet, we will try to update as soon as there is one. Not sure how @batzen takes care of this in Fluent.Ribbon?

**Comment by batzen** [comment]
I don't use the Expression.Blend assemblies anymore but XamlBehaviors.Wpf from https://github.com/microsoft/XamlBehaviorsWpf instead.
They refused to publish a preview version compiled against .net core, so i currently just ignore the build warning.
.net core is still in preview so anyone using the ribbon in .net core is using a preview, so things might break at any point.
As soon as .net core is released XamlBehaviors.Wpf should be updated quite fast as there is already https://github.com/microsoft/XamlBehaviorsWpf/pull/20

**Comment by GeertvanHorrik** [comment]
Thanks for taking the time to respond @batzen , we will migrate to that package as soon as .net core is officially released.

**Comment by GeertvanHorrik** [comment]
Related to #1246. This is a breaking change, but should we do it in a minor version anyway?

**Comment by GeertvanHorrik** [comment]
For 6.0, #1246 has been solved. Will close this ticket.
