### ISSUE TITLE
VS2019 hangs when creating a project with Catel Template

### ISSUE THREAD

**Issue by advapiIT** [Catel/Catel#1418]
- [X ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

Catel

## Version of OS(s) listed above with issue
Win 10 Version 10.0.18362.295

## Steps to Reproduce
1.Select the Catel's template
2.Click on OK (to create)
3. I got a messagebox from VS telling One or more error occurred

![image](https://user-images.githubusercontent.com/4690086/64246216-b3866f80-cf0c-11e9-9d34-c668d974b489.png)

## Expected Behavior

The project should be created

## Actual Behavior

An exception with nothing inside the Output window

**Comment by GeertvanHorrik** [comment]
Probably related to https://github.com/Catel/Catel.Templates/issues/12
