### ISSUE TITLE
ObservableDictionary Support

### ISSUE THREAD

**Issue by vaecors** [Catel/Catel#1421]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Introduces a new type of Dictionary that implements INotifyCollectionChanged and INotifyPropertyChanged. 

## API Changes
- Implement ObservableCollection in Catel.MVVM
- Create Approval Tests for ObservableCollection
- Create Unit Tests for ObservableCollection

## Intended Use Case
Useful for scenarios such as ComboBox controls that utilize Dictionaries as an item source but require the flexibility of adding, updating and removing items based on business logic within a ViewModel or Service. 

As a final note, we actually already have this implementation completed as we utilize it for our in-house applications that are built on-top of Catel. The purpose is to share the feature to other users of the framework who may need it.

**Comment by GeertvanHorrik** [comment]
Nice, would love to see this in the framework.

**Comment by vaecors** [comment]
Great, we'll allocate some time to get this into a PR.
