### ISSUE TITLE
Consider using expression trees in ObjectAdapter

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1439]
Suggested in #1438 by @vaecors :

> This is a good example of what would benefit from the expression tree setter and would speed up serialization.

and

> The FastExpressionCompiler is an optional behavioral change and is not necessarily required for those methods. We used it to speed up cold starts and the fact the library it sits in already depends on it due to our use of Mapster. I made about one comment concerning one of the changes. I also was a bit curious of the use of IsValueType vs IsPrimitive type for one of the calling methods but that's more of a preference I feel more than an advantage of A vs B.

**Comment by vaecors** [comment]
Just as a note, if you want to remove the FastExpressionCompiler dependency from the example class, simply replace any `CompileFast` calls with `Compile`.

**Comment by GeertvanHorrik** [comment]
@vaecors I wanted to start working on this this evening. I'll start with expression trees, and then we might consider adding FastExpressionCompiler.

Do you have a good example of expression trees when you really don't know anything about the type? How do you ensure performance (e.g. via caching, or ... )?

**Comment by GeertvanHorrik** [comment]
And is the .Compile available on all platforms or will it be limited on some (e.g. Xamarin, UWP, etc)?

**Comment by vaecors** [comment]
@GeertvanHorrik Yes [.Compile](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1.compile?view=netframework-4.8) is available on all target platforms. I'm not sure about FastExpressionCompiler though as we only target .NET Core and WPF. As for handling unknown types if you look at the [gist](https://gist.github.com/vaecors/fbb7bbafdf47b1e4e7e9b34ae9ab027a) I provided, it has methods to create "untyped" setters (i.e. Action<T, object> and Func<T, object>). 

As we cache the Action/Func within a dictionary (where the property name is the key), we haven't noticed a real performance issue. In a nutshell we have a custom ExcelReader class that uses the OpenXML SDK and using a custom IDataReader class we also created, projects all the objects into concrete types, it projected a 1 million row workbook in about 2-3 seconds.

**Comment by vaecors** [comment]
I just took a quick peak at FastExpressionCompiler, it targets .NET Standard which I believe can be imported into Xamarin/UWP? We don't really do development on those targets so I can't give you a concrete conclusion.

**Comment by vaecors** [comment]
@GeertvanHorrik Just a thought, if you're concerned about unboxing performance when it comes to retrieving values, this may help (we use this in a class we wrote to calculate Blake2b checksums of classes):

```
private static TValue GetValue<TValue>(T item, Func<T, object> propertyGetter)
{
    if (T is null || propertyGetter is null)
    {
        return default;
    }

    object propertyValue = propertyGetter(item);

    if (propertyValue is TValue value)
    {
        return value;
    }
    
    return default;
}
```

**Comment by GeertvanHorrik** [comment]
Thanks for the input! Will finalize the xml serializer, then this is the next thing I will look into. Will run the benchmarks tonight to see if we made any real progress :)

**Comment by vaecors** [comment]
Anytime, I'm actually toying with the idea of doing an implementation where the typed getter/setters could be used against a class in a straight forward fashion (we primarily use only the untyped variant not really worrying too much about inline optimizations).

The premise being the implementation (most likely an instantiated class) would be wrapped around the target class and internal dictionary caches for all primitive types would be maintained (properties shredded out via their primitive type) to avoid any IL boxing/unboxing that could occur. Public methods would then be exposed to handle this. I won't have time though for about the next 3 weeks to really explore that though.

**Comment by GeertvanHorrik** [comment]
Sounds interesting. Let's first create some helper methods / wrappers to use expressions instead of reflection. After that, we can actually wrap it into easy to use classes. Sounds like a great idea!

**Comment by vaecors** [comment]
Yeah I was thinking about it quite a bit today since the properties of a target class already have to be enumerated through to build the expressions it's not out of the realm to group those by their type and direct them to the appropriate cached collection and take advantage of strongly typed getter/setter expression tree. It may be wise to also throw an InvalidOperationException for anything that is a non-primitive or DBNull because of complexity issues but I don't know if that's the best course of action.

I went ahead and made a [blank repository](https://github.com/vaecors/FastPropertyInvokerTest) for now, so when I get free bits of time I'll commit any ideas towards it in-case you want to keep an eye on it.

**Comment by vaecors** [comment]
@GeertvanHorrik There was a signature goof in the gist for the ExpressionBuilder. I have updated it.

**Comment by vaecors** [comment]
@GeertvanHorrik Actually there are some additional issues with the typed getter/setters. I need to re-write these methods so don't use the code for now (I should have it updated tonight though).

**Comment by vaecors** [comment]
@GeertvanHorrik I fixed the associated issues with the strongly typed setters/getters. I also re-wrote them to use expressions instead of delegates so they can take advantage of CompileFast.

**Comment by vaecors** [comment]
@GeertvanHorrik It actually didn't take as long as I thought (about 2 hours), there's a full set of code with benchmarks on the [FastPropertyInvokerTest](https://github.com/vaecors/FastPropertyInvokerTest) repository, have fun.

**Comment by GeertvanHorrik** [comment]
So approx. 2 x faster. Any idea about the cost off the initial cold start?

**Comment by GeertvanHorrik** [comment]
will run all the benchmarks tonight without the expression thingie

**Comment by vaecors** [comment]
> Any idea about the cost off the initial cold start?

I honestly never timed it but correlating with the [benchmarks](https://github.com/dadhi/FastExpressionCompiler/blob/master/README.md#benchmarks) of FastExpressionCompiler and the fact it's only doing public properties (private and protected are ignored) I would imagine it's negligible for most classes. If you start having classes with 50 or more properties the linear operation .GetProperties() might hurt but it's probably getting into premature optimization territory at this point.

**Comment by GeertvanHorrik** [comment]
I will update this in ObjectAdapter.

If ModelBase => use directly
else use these expression trees

The only downside is that we can't use generic (we really don't know anything), but we can build up this using reflection (1 time slow). So as soon as objects are being re-used, we will see benefit.

**Comment by vaecors** [comment]
It's my understanding that neither of those classes had Generic support anyway or am I missing some context here?

**Comment by GeertvanHorrik** [comment]
This seems generic:

https://github.com/vaecors/FastPropertyInvokerTest/blob/master/FastPropertyInvokerTest/FastPropertyInvoker.caches.g.cs#L15

But I had something to drink, maybe I should check tomorrow ;-)

**Comment by vaecors** [comment]
Right now I'm sync'd up with you, yeah the FastPropertyInvoker is a generic to facilitate the building of the caches and functions against the target class. I now see what you mean by doing the reflection as you need to grab the derived type then instantiate it. May even be able to avoid reflection there and use an expression tree to instantiate it (we do this with classes in our system).

**Comment by GeertvanHorrik** [comment]
Introducing a new interface `Catel.Data.IObjectAdapter`. This will be used inside the `Catel.Runtime.Serialization.ObjectAdapter` internally (but that does more, such as creating the member values required for serialization). 

The names are a bit confusing, but for any object adapters, the `Catel.Data` one should be used:

```
/// <summary>
/// Object adapter allowing to customize reflection and member mappings.
/// </summary>
public interface IObjectAdapter
{
    /// <summary>
    /// Gets the member value of the instance.
    /// </summary>
    /// <typeparam name="TValue">The type of the value to retrieve.</typeparam>
    /// <param name="instance">The instance.</param>
    /// <param name="memberName">The member name.</param>
    /// <returns>The member value.</returns>
    TValue GetMemberValue<TValue>(object instance, string memberName);

    /// <summary>
    /// Sets the member value of the instance.
    /// </summary>
    /// <param name="instance">The instance.</param>
    /// <param name="memberName">The member name.</param>
    /// <param name="value">The value.</param>
    /// <returns>The member value.</returns>
    void SetMemberValue<TValue>(object instance, string memberName, TValue value);
}
```

Catel will have 2 implementations:

- ReflectionObjectAdapter (only uses reflection)
- ExpressionTreeObjectAdapter (uses expression trees)

We'll make the generation of the expression tree virtual protected. This allows anyone to use `CompileFast` without `Catel.Core` having to reference external dependencies. I think this is the best solution I can come up with.

Will update the WIP PR soon.

**Comment by vaecors** [comment]
@GeertvanHorrik you may want to look at how Mapster handles configuring FastExpressionCompiler https://github.com/MapsterMapper/Mapster/wiki/FastExpressionCompiler

**Comment by GeertvanHorrik** [comment]
Updated interface definition:

```
/// <summary>
/// Object adapter allowing to customize reflection and member mappings.
/// </summary>
public interface IObjectAdapter
{
    /// <summary>
    /// Gets the member value of the instance.
    /// </summary>
    /// <typeparam name="TValue">The type of the value to retrieve.</typeparam>
    /// <param name="instance">The instance.</param>
    /// <param name="memberName">The member name.</param>
    /// <param name="value">The member value to update.</param>
    /// <returns><c>true</c> if the member was retrieved; otherwise <c>false</c>.</returns>
    bool GetMemberValue<TValue>(object instance, string memberName, ref TValue value);

    /// <summary>
    /// Sets the member value of the instance.
    /// </summary>
    /// <param name="instance">The instance.</param>
    /// <param name="memberName">The member name.</param>
    /// <param name="value">The value.</param>
    /// <returns><c>true</c> if the member was set successfully; otherwise <c>false</c>.</returns>
    bool SetMemberValue<TValue>(object instance, string memberName, TValue value);
}
```

**Comment by GeertvanHorrik** [comment]
Reflection implementation is done. Now we "only" have to implement the expression tree one.

**Comment by GeertvanHorrik** [comment]
Just an update: PR #1447 contains a FastMemberInvoker that is *strongly* based on the great work by @vaecors . I've added virtual Compile methods so users could actually override this and use CompileFast instead.

In the ExpressionTreeObjectAdapter, I'll implement a virtual method to create the FastMemberInvoker class so it can be overridden with a custom implementation (that uses FastCompile). I think this is going to work great. Next step is also adding fields support.

**Comment by GeertvanHorrik** [comment]
See https://github.com/Catel/Catel/pull/1447/files#diff-63eb25c26c7957d68adb286f4ad4a096R96 on where to override the construction of the FastMemberInvoker inside the ExpressionTreeObjectAdapter.

See https://github.com/Catel/Catel/pull/1447/files#diff-63eb25c26c7957d68adb286f4ad4a096R96 to see how to customize the compile methods.

**Comment by GeertvanHorrik** [comment]
@vaecors just pushed a new large update. I've implemented the FastMemberInvoker, both fields and properties are supported. Also implemented the ExpressionTreeObjectAdapter (registered by default).

The FastMemberInvoker does lazy-compilation (instead of premature compilation) so only member access expressions that are required will be compiled.

The only thing I am not happy about (yet) is the part where TValue needs to be casted (but needs to be boxed first):

https://github.com/Catel/Catel/pull/1447/files#diff-f3c1ab2eb24ea2e765b7851bb32201a5R43

I think the rest is starting to look nice.

**Comment by vaecors** [comment]
@GeertvanHorrik Looking good, I have confidence this will greatly help performance in the 5.12 release. Looking at your note about boxing to object (only to then unbox it), I wonder if it pays to look into building a series of delegates to handle primitive type conversions similar to [this](https://stackoverflow.com/a/45508419) but maybe a bit more cleaner/streamlined. Obviously it would only work for primitive types but a T4 template could be shimmed to generate most of the code I think.

**Comment by GeertvanHorrik** [comment]
Created a separate ticket. Will merge this PR so we can actually start testing this with real apps.
