### ISSUE TITLE
FileSupport => SaveFileService & OpenFileService: Bug if InitialDirectory does not exist

### ISSUE THREAD

**Issue by Khashayar-Emami** [Catel/Catel#1453]
// Type: Catel.Services.IFileSupport
// Assembly: Catel.MVVM, Version=5.10.0.0, Culture=neutral, PublicKeyToken=null

In FileSupport for SaveFileService & OpenFileService if the InitialDirectory does not exist, an exception is thrown. A possible fix was marked down:

public override IOpenFileService GetOpenFileService(string title, string filter, string initialDirectory = null, string fileNameSuggestion = null, bool isMultiSelect = false)
        {
            var service = IoCConfiguration.DefaultDependencyResolver.Resolve<IOpenFileService>();
            service.Title = title;
            service.Filter = filter;
            service.InitialDirectory = initialDirectory;
            service.FileName = fileNameSuggestion;
            service.IsMultiSelect = isMultiSelect;
            service.CheckFileExists = true;

            ************// HERE THE FIX:************
            ************// HERE THE FIX:************
            if (!Directory.Exists(fileSupport.InitialDirectory))
            {
                fileSupport.InitialDirectory = null;
            }
            ************// END OFTHE FIX:************
            ************// END OF THE FIX:************

            return service;
        }

public override ISaveFileService GetSaveFileService(string title, string filter, string initialDirectory = null, string fileNameSuggestion = null)
        {
            var service = IoCConfiguration.DefaultDependencyResolver.Resolve<ISaveFileService>();
            service.Title = title;
            service.Filter = filter;
            service.InitialDirectory = initialDirectory;
            service.FileName = fileNameSuggestion;
            service.ValidateNames = true;

            ************// HERE THE FIX:************
            ************// HERE THE FIX:************
            if (!Directory.Exists(fileSupport.InitialDirectory))
            {
                fileSupport.InitialDirectory = null;
            }
            ************// END OFTHE FIX:************
            ************// END OF THE FIX:************

            return service;
        }

Thank you, kind regards
Khashayar Emami

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. I think we can implement this for 5.12. We do have Orc.FileSystem which we prefer to do file / directory related operations, need to figure out how to deal with that (maybe make it virtual and override in Orchestra).

**Comment by Khashayar-Emami** [comment]
Thank you for that. Please notify me if the problem has been fixed in the new version.
Regards
Khashayar

**Comment by GeertvanHorrik** [comment]
We don't do notification stuff, not even for paying / supporting customers. We will close the ticket once it's done, that's all we can give with the resources we have.

**Comment by Khashayar-Emami** [comment]
Ok
