### ISSUE TITLE
ViewModel can't be created

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1458]
after upgraded from 5.9 to 5.11 i found out that some of mine viewmodels are failing to construct. 
Logger says "Constructor is not valid because parameter 'authProvider' cannot be resolved from the dependency resolver".
Here is the constructor: 
    public MyMainWindowViewModel([NotNull] IUserLoginService loginService,
      [NotNull] IAuthenticationProvider authProvider,
      [NotNull] IUIVisualizerService visualizerService,
      [NotNull] IMessageService messageService,
      [NotNull] IMessageMediator msgMediator,
      [NotNull] IRevisionWindowStackService vmStackService,
      [NotNull] IExceptionService exceptionService
      )
    {}
Is the IAuthenticationProvider not registered automatically anymore?

 - [ ] WPF

the view used to be shown by call of
await uiVisualizerService.ShowAsync<MyMainWindowViewModel>();

now doesn't work: 

12:33:00:234 => [ERROR] [Catel.Argument] [1] Argument 'viewModel' cannot be null
Exception thrown: 'System.ArgumentNullException' in mscorlib.dll
An exception of type 'System.ArgumentNullException' occurred in mscorlib.dll but was not handled in user code
Argument 'viewModel' cannot be null

**Comment by gofrogi** [comment]
Remark. This provider has been registered by attribute
[ServiceLocatorRegistration(typeof(IAuthenticationProvider))]
and ServiceLocator.Default.AutoRegisterTypesViaAttributes = true;
It has been working until now.

**Comment by GeertvanHorrik** [comment]
Does Catel even have an out of the box `IAuthenticationProvider`?

**Comment by gofrogi** [comment]
No, Catel declares only the Interface. But why the registration via
attribute diesn't work sometimes?

Geert van Horrik <notifications@github.com> schrieb am Mo., 28. Okt. 2019,
13:15:
