### ISSUE TITLE
Implement IRevertibleChangeTracking

### ISSUE THREAD

**Issue by ghost** [Catel/Catel#1460]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
So to give a bit of background, there was/is an active discussion going within the .NET [subreddit](https://www.reddit.com/r/dotnet/comments/dofeul/recommended_wpf_mvvm_framework_for_2019_net_core/) about MVVM frameworks and I had brought up Catel. During that discussion it was revealed that the interfaces `IChangeTracking` and `IRevertibleChangeTracking` exist. It may be a good idea to integrate these into ModelBase for people that may either expect the behavior or have something dependent on it (I've never personally used these, didn't know they existed until today).

## API Changes
Implement `IChangeTracking` ([source](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/IChangeTracking.cs,dc28bbd667de6460)) and `IRevertibleChangeTracking` ([source](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/IRevertibleChangeTracking.cs,1ad6de2fe3f6a4f3)) [note: implementing `IRevertibleChangeTracking` also implements `IChangeTracking`] within `ModelBase.editableobject.cs` to provide the following:

- `IsChanged`: Can be explicitly implimeneted and wrap around `IsDirty` to avoid breaking change perhaps?
- `AcceptChanges`
- `RejectChanges`

## Intended Use Case
Would simply add support for any controls and/or use-cases where a developer may expect these interfaces to exist in addition to `IEditableObject`. They are available on all targeted platforms.

## Notes ##
I'd consider this a low priority given #1450 and all associated work, maybe a tech debt target for 6.x?

**Comment by GeertvanHorrik** [comment]
Should be fairly simple to implement, and could be implemented while we carefully test the new serialization engine in the new alpha builds.

Will put it on the list for 5.12, but might put this on 6.0 if there is not enough time after all.

**Comment by vaecors** [comment]
It just seemed very intriguing when it came up. I’m actually curious of any controls (such as Telerik or DevExpress) actually take any advantage of the interface.

**Comment by GeertvanHorrik** [comment]
I really never heard of it, even when implementing all the, at the time to me, most commonly used interfaces. Anyway, shouldn't be hard to support.

**Comment by Grauenwolf** [comment]
Unlike IEditableObject, I seriously doubt any controls implement it.

IChangeTracking is about unsaved changes. As far as I know, there's no UI standard for that other than adding an asterisk (*) to the title of the window.

**Comment by Grauenwolf** [comment]
Note that IRevertibleChangeTracking implies a 2nd level of undo. 

IEditableObject.CancelEdit only reverts back to the last time you called BeginEdit.

IRevertibleChangeTracking.RejectChanges goes back to the original state when the record was loaded from the database.

If you don't already have the infrastructure for it then I would suggest deferring IRevertibleChangeTracking to a separate ticket.

**Comment by GeertvanHorrik** [comment]
Note that we have Orc.projectmanagement for dirty state tracking of a whole project. And Orc.memento for any level of undo / redo.

**Comment by GeertvanHorrik** [comment]
Moving to 5.13 / 6.0. I want to finalize the release for 5.12 and hope to do that later today.

**Comment by GeertvanHorrik** [comment]
Just checked this. While we could easily wrap the AcceptChanges / RejectChanges:

```
        void IChangeTracking.AcceptChanges()
        {
            ((IEditableObject)this).EndEdit();
        }

        void IRevertibleChangeTracking.RejectChanges()
        {
            ((IEditableObject)this).CancelEdit();
        }
```

But... It will be hard *what* to accept / reject because we need a signal to start watching for specific changes. For example, the IEditableObject is a better implementation because it has a start and end (accept / reject) moment. I don't think I've ever seen the `I(Revertible)ChangeTracking` in the wild.

Therefore I will close this ticket as won't fix. If there is a good logic, I am happy to re-open but for now I think there is a (much) better alternative via the `IEditableObject`.

**Comment by Grauenwolf** [comment]
They are meant for different use cases. 

`IChangeTracking` is for tracking unsaved documents. For example, it let's you know when to prompt the user to save when closing a window. So the start is always the last time the document was loaded or saved. 

`IEditableObject` is for dialog windows and data grids, where the UI actions denote a start/end point and you can instantly revert by clicking Cancel or pressing Escape. But pressing Ok doesn't usually instantly save the record in question.  Hence the reason I usually have both interfaces. 

So while I haven't seen `IRevertableChangeTracking` in the wild, I feel that `IChangeTracking` is important.

**Comment by GeertvanHorrik** [comment]
@Grauenwolf , thanks for these great insights, very useful. I think this interface would be much more fitting in Orc.ProjectManagement since that actually represents something "saveable" (a project). We could consider implementing this in 
`SaveableModelBase` as well. Will keep it in consideration. I think a model does not necessarily represent a document.

**Comment by Grauenwolf** [comment]
When a say "document" I mean "something that is saved as a whole". It could be a file, it could also be a collection of database rows that are always saved as a group. 

So normally I don't put that interface on every class like I would for editable object. Instead I just put it at the top where the "unsaved changes" indicator can see it.

**Comment by GeertvanHorrik** [comment]
Totally makes sense. In that case I think it's not wise to try and implement this in the ModelBase. It could be up to the caller (that is actually aware of the document structure) to implement it.
