### ISSUE TITLE
DependencyObjectExtensions.FindLogicalOrVisualAncestor returns null when it should find a parent

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1474]

**Comment by GeertvanHorrik** [comment]
Not sure why it only searches 1 level up. 

A workaround is using FindLogicalAncestorByType<T> instead.

**Comment by vaecors** [comment]
Is it getting stuck on one level for all platforms or just a specific one?

**Comment by GeertvanHorrik** [comment]
It just checks for a single level. Probably for performance reasons, but I wouldn't expect it.

**Comment by vaecors** [comment]
Strange, we have something similar in our framework called ParentOfType<> (we also have a ChildrenOfType<>) but not with the same quarky behavior.

**Comment by GeertvanHorrik** [comment]
See https://github.com/Catel/Catel/blob/36999a7a19c43d647a20934c2003879236a3a7b2/src/Catel.MVVM/Windows/Extensions/DependencyObjectExtensions.cs#L48, it capped at 1 level. So now I've added the checks that actually respect the maxDepth that was provided.
