### ISSUE TITLE
Consider the usage of SortedDictionary for Property Bag and Boxing Cache implementation

### ISSUE THREAD

**Issue by alexfdezsauco** [Catel/Catel#1478]
@GeertvanHorrik @vaecors 

Since an object have few properties and efficient access to the elements by index and/or key is required we could consider the usage of SortedDictionary for Property Bag implementation.

Could be also useful for Boxing Cache implementation.

**Comment by vaecors** [comment]
@alexfdezsauco I can see that given that `SortedDictionary` uses a TreeSet under the covers so it would be fast enough for this. Might also be a good idea to type it's backing Field/Property as an `IDictionary`.

**Comment by GeertvanHorrik** [comment]
From what I remember from reading somewhere, casting dictionaries is a bad idea?

**Comment by GeertvanHorrik** [comment]
See https://www.nimaara.com/beware-of-the-idictionary-tkey-tvalue/

**Comment by vaecors** [comment]
That information looks like it's based on a very large collection using `Dictionary<TKey, TValue>`. That would be a problem anyway because it uses hash tables. If you use an `IDictionary` backed by a `SortedDictionary` it generally doesn't have the same issue. At least I've never personally observed it with collections in the hundreds of thousands. 

Classes wouldn't have that many problems (if they did, you have another problem entirely).

**Comment by GeertvanHorrik** [comment]
I will create a simple benchmark to see if it makes sense to make the change.

**Comment by vaecors** [comment]
That might be the best path, I'm trying to run that gentlemen's same code in LinqPad and I'm getting very much different results both in the timings and the IL generation. It's quite possible some nuances changed.

**Comment by GeertvanHorrik** [comment]
I decided to expand the already existing benchmark research on the typed property bags. This way we can combine all the combinations we ever want to combine.

See https://github.com/geertvanhorrik/propertybagresearch

@alexfdezsauco , if you want to write different kind of benchmarks, feel free to PR.

**Comment by GeertvanHorrik** [comment]
I think the benchmarks for the dictionaries need more values / properties to show something meaningful.

```
|            Method |     Mean |    Error |   StdDev |   Median | Rank | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------ |---------:|---------:|---------:|---------:|-----:|------:|------:|------:|----------:|
|  SortedDictionary | 40.09 ns | 1.156 ns | 3.408 ns | 41.25 ns |    1 |     - |     - |     - |         - |
| RegularDictionary | 38.90 ns | 1.514 ns | 4.463 ns | 40.26 ns |    1 |     - |     - |     - |         - |
```

@alexfdezsauco , could you please extend the examples so they contain more (say at least 10) properties (which seems like a fair count to reflect simple models in production scenarios)?

**Comment by vaecors** [comment]
I agree with that assessment, to have any real impact classes would need to be implementing between 10 and 30 properties otherwise the impact may not be worth it, even for a `TreeSet` or a `HashTable`.

If one has to go beyond 30 properties for a class then either the class needs to be refactored or one needs to consider an ExpandoObject implementation (which in the end uses a Dictionary as a bridge anyway). But that's more common in scenarios where one needs dynamic data grids because the column source is variable (this is common in financial data grids such as chart of accounts and trial balances).

While I usually hate it when something does magic under the covers, I wonder if there would be a purpose of PropertyBag dynamically choosing whether or not to use a Dictionary based on the property count.

**Comment by GeertvanHorrik** [comment]
A property bag with about 15 properties:

```
|                       Method |     Mean |    Error |   StdDev |   Median | Rank | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |---------:|---------:|---------:|---------:|-----:|------:|------:|------:|----------:|
|  SortedDictionary_FirstValue | 43.54 ns | 1.654 ns | 4.850 ns | 46.18 ns |    2 |     - |     - |     - |         - |
|   SortedDictionary_LastValue | 39.95 ns | 1.767 ns | 5.210 ns | 41.41 ns |    1 |     - |     - |     - |         - |
| RegularDictionary_FirstValue | 43.76 ns | 1.662 ns | 4.899 ns | 46.28 ns |    2 |     - |     - |     - |         - |
|  RegularDictionary_LastValue | 39.79 ns | 1.525 ns | 4.496 ns | 41.68 ns |    1 |     - |     - |     - |         - |
```

**Comment by vaecors** [comment]
@GeertvanHorrik Though now it may be getting to the point of premature optimization and this may be a shot in the dark, and may not make any bit of difference. What about having the implementation of the dictionary with a case insensitive key (`StringComparison.OrdinalIgnoreCase`).

**Comment by GeertvanHorrik** [comment]
Oops, scrap all of that. I used the wrong factory type

**Comment by GeertvanHorrik** [comment]
> What about having the implementation of the dictionary with a case insensitive key (StringComparison.OrdinalIgnoreCase).

C# is case sensitive. If we would make the property bag case insensitive, it could potentially break stuff.

**Comment by GeertvanHorrik** [comment]
Here are the real benchmarks with the correct dictionary factories:

```
|                       Method |      Mean |     Error |    StdDev |    Median | Rank | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |----------:|----------:|----------:|----------:|-----:|------:|------:|------:|----------:|
|  SortedDictionary_FirstValue | 160.33 ns |  6.981 ns | 20.584 ns | 169.97 ns |    3 |     - |     - |     - |         - |
|   SortedDictionary_LastValue | 580.62 ns | 11.992 ns | 33.231 ns | 588.40 ns |    4 |     - |     - |     - |         - |
| RegularDictionary_FirstValue |  47.16 ns |  0.996 ns |  1.429 ns |  47.10 ns |    2 |     - |     - |     - |         - |
|  RegularDictionary_LastValue |  39.42 ns |  1.443 ns |  4.232 ns |  41.12 ns |    1 |     - |     - |     - |         - |
```

**Comment by GeertvanHorrik** [comment]
I don't think using the sorted dictionary inside the property bags is a good idea. We could consider it for the BoxingCache.

**Comment by vaecors** [comment]
>  SortedDictionary_LastValue | 580.62 ns 

Oof that is a very long time just to jump to the end of the list. Yeah a `Dictionary` is going to be better in this case, order of the properties really shouldn't matter as that's a UI concern.

**Comment by vaecors** [comment]
I see where the bottleneck is, `SortedDictionary` implements it's own `ValueCollection` type which is just another `SortedDictionary` under the covers so it's enumerating the entire collection to jump. `Dictionary` uses a `HashTable` with a set of Array buckets. I'm not even sure implementing it for the BoxingCache would be a good idea either, might be just best to use `Dictionary` for both.

**Comment by alexfdezsauco** [comment]
Yeah, doesn't look too promising the usage of sorted dictionaries.

![image](https://user-images.githubusercontent.com/1785664/68709101-fd21b500-0562-11ea-8fc0-a1baafcaa3da.png)

**Comment by GeertvanHorrik** [comment]
Perfect, thanks for the research. Let's drop the idea of the dictionary and close this ticket.
