### ISSUE TITLE
Update the docs to cope with recent versions

### ISSUE THREAD

**Issue by bigworld12** [Catel/Catel#1481]
## Summary
Catel is a fast moving project, so it's bound to happen that the docs might not be able to keep up.
This can be observed in multiple occasions:
e.g.

1. the docs [here](https://docs.catelproject.com/vnext/catel-core/data-handling/observableobject/) state that `ObservableObject` implments `INotifyPropertyChanging` but there is no reference for `IPropertyChanging` in the code base at all (not sure if it was dropped at some point for some reason)
2. Some classes don't have any documentation at all e.g. [ValidatableModelBase](https://docs.catelproject.com/vnext/catel-core/data-handling/validatablemodelbase/)

I think the docs should be getting some love, since even after 2 years of using this library, i still have new things to discover every day! (just shows how much dedication is put into it ^^)

## API Changes

- docs should be updated 

 
## Intended Use Case
- New users trying to understand the library will find it easier

**Comment by GeertvanHorrik** [comment]
Fully agree. Today we've put effort into auto-generating the site once the docs have been updated. This was one of the prerequisites for this to happen.

Now basically anyone can PR the docs and it should auto-update.

**Comment by GeertvanHorrik** [comment]
If you are missing features, please let us know so we can work on those first.

**Comment by bigworld12** [comment]
@GeertvanHorrik is there a contribution guide for the docs ?

**Comment by GeertvanHorrik** [comment]
Not yet, but each page has a link at the left bottom:

![image](https://user-images.githubusercontent.com/1246444/68854554-91635780-06dc-11ea-835e-46cb330bcb7c.png)

**Comment by GeertvanHorrik** [comment]
A contribute guide has been written (will add the rules later):

https://github.com/catel/catel.docs/
