### ISSUE TITLE
Add VisualizerResult with instance of view model

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1489]
At the moment the `IUIVisualizerService` returns a bool representing the result of the DialogResult (which is based on the view model result).

However, sometimes it's convenient to access the used VM in cases like this:

```
var result = await uiVisualizerService.ShowDialog<MyViewModel>();
if (result ?? false)
{
    // do something here with the vm
}
```

At the moment, one has to manually instantiate the view model and pass the instance into the `IUIVisualizerService` in order to use it later.

The idea is to introduce a new class:

```
public class VisualizerResult : VisualizerResult<IViewModel>

public class VisualizerResult<TViewModel>
    where TViewModel : IViewModel
{
    public VisualizerResult(bool? result, object dataContext}
    {

    }

    public bool? Result { get; set; }

    public object DataContext { get; }

    public TViewModel ViewModel { get { return DataContext as TViewModel; } }
}
```

Instead of `bool?`, the `IUIVisualizerService` will return this class and allow for the following use case:

```
var result = await uiVisualizerService.ShowDialog<MyViewModel>();
if (result ?? false)
{
    var vm = result.ViewModel; // MyViewModel
}
```

With implicit operator overloads to bool, we should be able to still use this (commonly used) code:

```
if (await uiVisualizerService.ShowDialog<MyViewModel>() ?? false)
{
    // do something here, but no need for vm
}
```

**Comment by vaecors** [comment]
Does this mean that the ViewModel will no longer be present in `UICompletedEventArgs.DataContext` when specifying a closing function during `Show` and `ShowAsync`? That’s how we’ve been accessing it.

**Comment by GeertvanHorrik** [comment]
It will still be accessible there, but I think the UICompletedEVentArgs required a callback?

**Comment by GeertvanHorrik** [comment]
Basically only the return type of the methods will change (for more convenient usage).

**Comment by vaecors** [comment]
Yeah it does, both `ShowAsync` and `ShowDialogAsync` have and optional parameter to specify a Func which takes that class as a return.

We use that for 2 reasons. 1 to reduce the complexity of a method (keeps SonarQube happy) and 2 to access the ViewModel.

I don’t see any issue with the return type though but I also wonder what will happen with ViewModels that implement the disposable interface.

**Comment by GeertvanHorrik** [comment]
The vm's will be disposed as usual and the return object will (should) be a short-living object. Even if an object is disposed, you can still access its properties to check any required values.

**Comment by GeertvanHorrik** [comment]
Thinking what could be done about ShowOrActivateAsync. If it's already shown, we don't know the result.

**Comment by GeertvanHorrik** [comment]
Decided to await the call incase it cannot be activated, and keep the signature to return a bool? in this case (since it can also refer to a call to `Window.Acticvate`).

**Comment by GeertvanHorrik** [comment]
Adding `Window` to `UIVisualizerResult` to always have access to the window as well (if needed).

**Comment by GeertvanHorrik** [comment]
Done.
