### ISSUE TITLE
Make Generic Catel.Collections.SuspensionContext Public

### ISSUE THREAD

**Issue by vaecors** [Catel/Catel#1509]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
This actually came up as a result of #1506 and #1508. It would be nice of `SuspensionContext<T>` was actually made `public`. Right now it is `internal` and only the non-generic `SuspensionContext` is `public`. 

## API Changes
Change `Catel.Collections.SuspensionContext` from `internal` to `public`

## Intended Use Case

We actually have several use cases where we use `SuspensionContext<T>` in our end implementation and to avoid overlap we maintain our own fork of Catel to expose it rather than override it at the namespace level.

**Comment by bigworld12** [comment]
think i can solve that
