### ISSUE TITLE
Fix a potential NullReferenceException in FastMemberInvoker

### ISSUE THREAD

**Issue by bigworld12** [Catel/Catel#1510]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [x] UWP
 - [x] iOS
 - [x] Android
 - [x] .NET Standard
 - [x] .NET Core

## Component

Catel.Core

## Version of Library
6.0
## Steps to Reproduce
this line holds a potential `NullRefrenceException` when `getterExpression` is null (that i encountered randomly during unit tests)

https://github.com/Catel/Catel/blob/398b6c822e5450e2f7bb001104dc1771496fcfe5/src/Catel.Core/Reflection/FastMemberInvoker/FastMemberInvoker.caches.g.tt#L54

it should be moved exactly below this line 
https://github.com/Catel/Catel/blob/398b6c822e5450e2f7bb001104dc1771496fcfe5/src/Catel.Core/Reflection/FastMemberInvoker/FastMemberInvoker.caches.g.tt#L51

same problem applies to all the methods below it.

## Actual Behavior

**Comment by GeertvanHorrik** [comment]
Maybe we should hotfix this together with the event storm into 5.12.1?

**Comment by bigworld12** [comment]
should I make a separate pr for the hot fix ?

**Comment by vaecors** [comment]
I would given that this and the event storm both affect 5.12.

**Comment by GeertvanHorrik** [comment]
Fixed in 5.12.1 hotfix branch, thanks @bigworld12 !
