### ISSUE TITLE
ObservableDictionary Performance Issue with Large Collections

### ISSUE THREAD

**Issue by vaecors** [Catel/Catel#1511]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [x] UWP
 - [x] iOS
 - [x] Android
 - [x] .NET Standard
 - [x] .NET Core

## Component

`Catel.MVVM.Collections.ObservableDictionary`

## Version of Library

5.12.0

## Version of OS(s) listed above with issue

Windows 10 Enterprise

## Steps to Reproduce
1. Instantiate an `ObservableDictionary` with a large collection (10,000 or more items)

## Expected Behavior

Process consumption time should be negligible.

## Actual Behavior

Process can take up to several 10s of seconds to run through the collection.

## Discussion

This is a separate bug but related to #1506 indirectly as it was discovered. I'm not sure if I would consider this an edge case, maybe it is, maybe it isn't. I know for us it isn't because we have some business processes that use drop-downs with this many objects (note: use of VirtualizingStackPanel is strongly recommended for that). 

The problem isn't with the implementation of the `IndexedKeyedCollection` as that is fast. The issue is actually with the `Insert` method. In order to handle the events properly an index has to be calculated and the use of `Collection.IndexOf()`. The problem is this is taking a huge amount of time:

![image](https://user-images.githubusercontent.com/49293119/71487134-b5d84680-27e7-11ea-9394-daea192c390d.png)

I'm not exactly sure how to approach this issue yet but it's an obvious bottleneck. Also whether or not it's critical to 5.12.x is up to interpretation given the use cases.

**Comment by vaecors** [comment]
@GeertvanHorrik @bigworld12 what are your thoughts on introducing this to `IndexedKeyedCollection`?

```csharp
public int IndexOfKey(TKey key)
{
    int index = -1;

    foreach ( TKey innerKey in Dictionary.Keys )
    {
        index++;

        if ( Equals(key, innerKey) )
        {
            return index;
        }
    }

    return -1;
}
```

When I replaced all the `_collection.IndexOf` calls with `_collection.IndexOfKey` the result ended up being this:

![image](https://user-images.githubusercontent.com/49293119/71489031-a231dd80-27f1-11ea-8aa2-60e72565b7e1.png)

So it went from 41.6ms to 4.5ms and as far I as can tell this wouldn't introduce any race conditions but I'm a bit punch today so a second pair of eyes would help.

**Comment by bigworld12** [comment]
I kept thinking about this recently, but isn't `ObservableDictionary` just a `FastObservableCollection<KeyValuePair>` + an internal dictionary that maps keys to values ?

**Comment by vaecors** [comment]
I mean it could _technically_ implement `FastObservableCollection<KeyValuePair<TKey, TValue>>` but that could pose some issues since it would allow duplicate keys without extra checks. When I built `ObservableDictionary` it was built with the premise that it would essentially be a complete implementation similar to `Dictionary` except that it supported Collection and Property Change events.

I had basically a few choices for the backing implementation which were buckets, a `TreeSet` or an `KeyedCollection` (which essentially implements a `Dictionary` anyway). The issue was that `_collection.IndexOf` used `ICollection.IndexOf` which was horribly slow because it compared both the key and the value when I only cared about the key. That's why I wrote the `IndexOfKey` instead to use the `ICollection<TKey>.Keys` source instead, while it's still a linear operation it wasn't as bad as `ICollection.IndexOf`.

**Comment by bigworld12** [comment]
@vaecors I am rewriting a new implementation for ObservableDictionary that's optimized for large operations from scratch (other than just notification suppression)
since the current implementation has insert time O(N) per item
and O(N*M) for multiple items
i am rewriting an implementation that has O(N+M) running time

**Comment by vaecors** [comment]
That’s fine, honestly my time at this point has been so limited I don’t have as much to dedicate to these things as much as I’d like.

**Comment by GeertvanHorrik** [comment]
@bigworld12 doest his mean that this will be done for 6.0, not 5.12.1?

**Comment by bigworld12** [comment]
I wrote a new list to avoid any accidental breaking charges in the public api
and users can opt in the new list, which will get renamed to ObservableDictionary  in 6.0
