### ISSUE TITLE
FastMemberInvoker.GetObjectPropertyGetter() is not thread safe

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1518]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] WPF

## Component
FastMemberInvoker 
What component is this issue occurring in?
Method GetObjectPropertyGetter causes NullReferenceException when many objects creating in a Parallel.ForEach loop with MaxDegreeOfParallelism > 1. 
Objects are derived from ValidatableModelBase

## Version of Library
5.12.1

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
It is difficult to create a little repro because of a lot another components involved. Maybe  a screenshot of the crash and the stack trace can help to recognize the potential problem.

Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   bei Catel.Reflection.FastMemberInvoker`1.GetObjectPropertyGetter(String memberName) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Reflection\FastMemberInvoker\FastMemberInvoker.caches.g.cs:Zeile 49.
   bei Catel.Reflection.FastMemberInvoker`1.TryGetPropertyValue(TEntity entity, String propertyName, Object& item) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Reflection\FastMemberInvoker\FastMemberInvoker.getpropertymethods.g.cs:Zeile 312.
   bei Catel.Reflection.FastMemberInvoker`1.TryGetPropertyValue[TValue](Object entity, String propertyName, TValue& value) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Reflection\FastMemberInvoker\FastMemberInvoker.getpropertymethods.g.cs:Zeile 23.
   bei Catel.Data.AdvancedPropertyChangedEventArgs..ctor(Object originalSender, Object latestSender, String propertyName, Object oldValue, Object newValue, Boolean isOldValueMeaningful, Boolean isNewValueMeaningful) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Data\EventArgs\AdvancedPropertyChangedEventArgs.cs:Zeile 134.
   bei Catel.Data.ModelBase.RaisePropertyChanged(Object sender, PropertyChangedEventArgs e, Boolean updateIsDirty, Boolean isRefreshCallOnly) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Data\ModelBase.cs:Zeile 430.
   bei Catel.Data.ModelBase.RaisePropertyChanged(Object sender, AdvancedPropertyChangedEventArgs e) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Data\ModelBase.cs:Zeile 383.
   bei Catel.Data.ModelBase.SetValue[TValue](PropertyData property, TValue value, Boolean notifyOnChange) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Data\ModelBase.propertyediting.cs:Zeile 173.
   bei Catel.Data.ModelBase.SetDirty(String propertyName) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Data\ModelBase.cs:Zeile 512.
   bei Catel.Data.ModelBase.RaisePropertyChanged(Object sender, PropertyChangedEventArgs e, Boolean updateIsDirty, Boolean isRefreshCallOnly) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Data\ModelBase.cs:Zeile 486.
   bei Catel.Data.ModelBase.RaisePropertyChanged(Object sender, AdvancedPropertyChangedEventArgs e) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Data\ModelBase.cs:Zeile 383.
   bei Catel.Data.ModelBase.SetValue[TValue](PropertyData property, TValue value, Boolean notifyOnChange) in C:\CI_WS\Ws\143929\Source\Catel\src\Catel.Core\Data\ModelBase.propertyediting.cs:Zeile 173.
   bei Rubin.Server.Model.EntityBase.set_ImplAttr(ImplicitAttributesT value) in C:\develop\Projects\cc\cad_prj-668\Rubin\Server\Model\EntityBase.cs:Zeile 24.
   bei Rubin.Server.Model.EntityBase..ctor() in C:\develop\Projects\cc\cad_prj-668\Rubin\Server\Model\EntityBase.cs:Zeile 89.

EntityBase is derived from ValidatableModelBase

here the screenshort from the code place where the exception has been thrown:

![Catel Core 5 12 1 2020-01-10 111808](https://user-images.githubusercontent.com/13942501/72163282-d5649700-33c3-11ea-89e0-a536b872bbeb.png)

My code has been working until the version 5.11.2 inclusively.

**Comment by GeertvanHorrik** [comment]
We had something similar yesterday as well. We need to investigate the cause and do another hotfix.

**Comment by GeertvanHorrik** [comment]
I was able to reproduce in a unit test.

**Comment by GeertvanHorrik** [comment]
The exception happens inside the dictionary. Replaced Dictionary with ConcurrentDictionary.

**Comment by GeertvanHorrik** [comment]
Releasing new beta now.
