### ISSUE TITLE
Add static setting to specify the default value for SupportIEditableObject and SupportValidation for Model attributes

### ISSUE THREAD

**Issue by AliveDevil** [Catel/Catel#1528]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [X] .NET Core

## Component

Catel.MVVM (I guess …), could be related to Catel.IoC, Catel.MVVM or Catel.Core

## Version of Library
5.12.2

## Version of OS(s) listed above with issue
WPF .NET Core App 3.1 on Windows 10 18363.

## Steps to Reproduce
1. Extract Zip ([catel-repro.zip](https://github.com/Catel/Catel/files/4099863/catel-repro.zip))
2. dotnet run
3. click Buttons
4. See number in main window changing if "This Duplicates" button is clicked and Window is closed

## Expected Behavior
The number just stays at 1, and never changes.

## Actual Behavior
Opening and closing a Window, with a ViewModel which has a `[Model]`-property sharing the same entity with another ViewModel creates a duplicate copy of a child class instance.

**Comment by GeertvanHorrik** [comment]
Thanks for the repro, we'll look into this asap.

**Comment by GeertvanHorrik** [comment]
Btw you could be interested in [Orc.ProjectManagement](https://github.com/wildgums/orc.projectmanagement) if you want to work with project management.

**Comment by AliveDevil** [comment]
I am aware of Orc.ProjectManagement.
This is issue came from working with ProjectManagement, though is not related to it.

**Comment by GeertvanHorrik** [comment]
The reason is support for `IEditableObject`. When this is supported (which Catel models do out of the box), it keeps track of an internal copy (xml serialization) of the whole object graph. In that case, as soon as you *cancel*, it restores the state (and could result in new instances).

A few options:

1. Disable IEditableObject support:

```
        [Model(SupportIEditableObject = false)]
        public Project Project { get; private set; }
```

2. Implement your own IEditableObject support that uses a different kind of serialization.

**Comment by AliveDevil** [comment]
Okay then … I'll go with the model-attribute property value. Overriding `OnCancelEdit` and returning `e.Cancel = true` is somehow a valid option too though might interfere with this automatic backup handling. It'd be great if this could be documented somewhere.

May be some policy in Catel `HandleEditableObjectByDefault` which is set to `true` (by default), and two attributes on ModelBase which allow either opt-in to EditableObject, or opt-out of EditableObject depending on the state of `HandleEditableObjectByDefault`-policy?

**Comment by GeertvanHorrik** [comment]
I will consider the options, but to be honest we haven't touched this feature for years (always has been this way). Restoring a backup of a graph can be more complex then it looks at first sight.

A static bool defining to disable it system wide sounds tempting. Will consider it for 6.0

**Comment by GeertvanHorrik** [comment]
Done for 6.0, thanks for the idea!
