### ISSUE TITLE
the ViewModeltoModel binding does not refresh the model properties as used to.

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1531]
- [ x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

MVVM

## Version of Library
5.12.2

## Version of OS(s) listed above with issue
Windows 10

We built a repro for you to test the following behavior.
A WPF View includes a listview where two product groups should be shown. 
The object of Article references a list of ProductGroups.
The test data will be created in App.xaml.cs in the Startup method. We are using EF6.4 and lazy loading for navigation properties such as ProductGroups.

Exposing of simple scalar types (Name property in this example) still always works fine.
But exposing of "lazy loaded" collections (ProducGroups property in this example) doesn't work anymore.
Exposed property ProductGroups is used in the view as ItemsSource of the ListView
If you set a break point in the InitializeAsync method and look with the debugger
on the ProductGroups property of Article the list view is also filled afterwards.
It doesn't work if we declare ProductGroups as property and decorate it with [ViewModelToModel] attribute. We concluded that the ViewModelToModel binding for reference types doesn't work properly anymore. 
Maybe the refreshing of viewmodel properties is deferred and  we simply should set any property?

With Catel version until 5.9 binding of exposed properties always worked.

[ExposeError.zip](https://github.com/Catel/Catel/files/4127779/ExposeError.zip)

**Comment by GeertvanHorrik** [comment]
The Expose property is taken care of by Catel.Fody. I am getting an instance of a collection here (in the event handler), but it's indeed empty.

```
        [ViewModelToModel(nameof(Article))]
        public FastObservableCollection<ProductGroup> ProductGroups { get; set; }

        private void OnProductGroupsChanged()
        {

        }
```

Calling this in the initialize makes sure it works:

```
        protected override async Task InitializeAsync()
        {
            await base.InitializeAsync();

            // TODO: subscribe to events here

            Article.ProductGroups.ToList();
        }
```

**Comment by gofrogi** [comment]
it's correct. With ToList() you are doing eager loading. That is not what it should be and we want. It always worked the way binding had loaded the collection from EF by lazy loading. If you set the framework version back to 5.9 you will see that it works. If the collection changes in the model, that would be transferred to the viewmodel but initial it doesn't work.

**Comment by gofrogi** [comment]
this is the working version. I only downgraded the catel framework.
[ExposeError-downgrade.zip](https://github.com/Catel/Catel/files/4128793/ExposeError-downgrade.zip)

**Comment by GeertvanHorrik** [comment]
We are considering to fix this for 5.12.4 (about to be released). I hope to find some time and energy to pick this up, but got some other things to finalize as well.

**Comment by GeertvanHorrik** [comment]
Probably this is because Catel is no longer "watching" child properties anymore (performance reasons). Will check whether I created a setting back then to enable this for users like you.

**Comment by GeertvanHorrik** [comment]
I've been testing this without the ViewModelToModel using this code:

```
        [Model(SupportIEditableObject = false)]
        [Expose("Name")]
        //[Expose("ProductGroups")]
        public Article Article { get; set; }

        [ViewModelToModel(nameof(Article))]
        public ObservableCollection<ProductGroup> ProductGroups { get; set; }

        private void OnProductGroupsChanged()
        {

        }

        protected override async Task InitializeAsync()
        {
            await base.InitializeAsync();

            ProductGroups = Article.ProductGroups;
        }
```

That seems to work?

**Comment by GeertvanHorrik** [comment]
Sorry, I missed that the explicit mapping in InitializeAsync should not be necessary.

**Comment by GeertvanHorrik** [comment]
Interesting observable. In the mappings logic (of the vm), whenever we do a clean map, it will return an (empty) FastObservableCollection. However, when I inspect the *Article* model using the debugger inspector, it immediately gets replaced by a valid collection.

Before inspection:

![image](https://user-images.githubusercontent.com/1246444/77667519-9be30700-6f82-11ea-8740-2e18aa589954.png)

After inspection:

![image](https://user-images.githubusercontent.com/1246444/77667577-b3ba8b00-6f82-11ea-91b7-5d34e6a242af.png)

So in the past, Catel probably did something with the model, causing it to lazy-load the collection.

**Comment by GeertvanHorrik** [comment]
Could be caused by EF replacing (overriding) the virtual property. Catel still stores the values inside the property bag, and the _objectAdapter uses the fastest way possible (it's a Catel object, so use direct property bag retrieval) method available.

I think before we used reflection to retrieve the values, causing it to use the actual property (but it was much slower).

Since this is only affecting a real specific niche situation, I am hesitant to fix this.

**Comment by GeertvanHorrik** [comment]
An easy workaround is btw to override the IObjectAdapter, something similar to this:

```
public class EntityObjectAdapter : Catel.Data.ExpressionTreeObjectAdapter
{
    public override bool GetMemberValue<TValue>(object instance, string memberName, out TValue value)
    {
        if (instance is MyModelBase entity)
        {
            // Important: EF requires reflection
            return PropertyHelper.TryGetPropertyValue(entity, memberName, out value);
        }

        return base.GetMemberValue(instance, memberName, out value);
    }

    public override bool SetMemberValue<TValue>(object instance, string memberName, TValue value)
    {
        if (instance is MyModelBase entity)
        {
            // Important: EF requires reflection
            return PropertyHelper.TrySetPropertyValue(entity, memberName, value);
        }

        return base.SetMemberValue(instance, memberName, value);
    }
}
```
