### ISSUE TITLE
Analogy.LogViewer.CatelProject: Request for logs examples

### ISSUE THREAD

**Issue by LiorBanai** [Catel/Catel#1539]
Hi,
I would like to create a parse for Catel logs in my open source project [(Analogy Log Viewer)](https://github.com/Analogy-LogViewer). 
For this I would appreciated  some example logs for developing and testing.

**Comment by GeertvanHorrik** [comment]
See https://github.com/wildgums/logviewer, I think it's also parsing the logs. Note that eventually it's free to the develop to decide, but I will look up the default format.

**Comment by GeertvanHorrik** [comment]
Here is an example:

```
10:58:20:390 => [INFO] [Gum.Services.ApplicationInitializationServiceBase] [6] App was launched using the following command line:
10:58:20:390 => [INFO] [Gum.Services.ApplicationInitializationServiceBase] [6] 
10:58:20:459 => [INFO] [Orchestra.ThemeHelper] [6] Setting theme to '#FF009983'
10:58:21:568 => [INFO] [Orchestra.Services.ShellService] [6] Checking if software was correctly closed previously
10:58:21:592 => [INFO] [Gum.Services.ApplicationInitializationServiceBase] [6] Initializing feature toggles
```

See this for details:

https://github.com/Catel/Catel/blob/cf144107bb6c93ae7c103d2615f799535f04b5f8/src/Catel.Core/Logging/LogListenerBase.cs#L327

**Comment by LiorBanai** [comment]
Thanks for the info.
I'll look into both of those.

**Comment by LiorBanai** [comment]
With those examples I was able to create initial parser :)
Thanks
![Example](https://user-images.githubusercontent.com/36262995/74045182-f9bc8f00-49d4-11ea-849b-8fbac7a0c1fa.jpg)

**Comment by GeertvanHorrik** [comment]
Thanks, looks great!
