### ISSUE TITLE
UIVisualizerService attempts to create window on non-UI thread

### ISSUE THREAD

**Issue by ArXen42** [Catel/Catel#1545]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

UIVisualizerService

## Version of Library
5.12.3

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. Call ShowDialogAsync from non-UI thread

## Expected Behavior

Modal window should be shown.

## Actual Behavior
Exception like this is thrown:
`Catel.MVVM.ViewHelper Failed to construct view 'MyDialogWindow' with both injection and empty constructor | [TargetInvocationException] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
`

It appears that calls to UIVisualizer service were automatically dispatched to UI thread in previous versions but in 5.12.3 they are not.
Was this intended change?

**Comment by GeertvanHorrik** [comment]
Not that we are aware off. Can you create a small repro (that worked before 5.12.3 and doesn't now)? Then we might be able to fix it.

**Comment by ArXen42** [comment]
Thanks for the quick response!

Here is the repro. The following code is located at `MainViewModel`:
[MyCatelApplication1.zip](https://github.com/Catel/Catel/files/4231719/MyCatelApplication1.zip)

```cs
try
{
    // Works
    await _uiVisualizerService.ShowDialogAsync(new TestViewModel());

    // Works
    new Thread(() =>
        {
            _dispatcherService.Invoke(() => { _uiVisualizerService.ShowDialogAsync(new TestViewModel()); });
        }
    ).Start();

    // Doesn't work
    await Task.Run(async () => { await _uiVisualizerService.ShowDialogAsync(new TestViewModel()); });
    
    // Won't work too with the same exception
    new Thread(() =>
        {
            _uiVisualizerService.ShowDialogAsync(new TestViewModel()).Wait();
        }
    ).Start();
}
catch (Exception ex)
{
    await _messageService.ShowErrorAsync(ex);
}
```
I have used latest project template for VS, updated all libraries to latest version and removed Fody just in case (it didn't seem to do any difference though).

I have tried with different versions down to Catel 5.8, but it didn't work there too.

Now I certainly don't understand why two dialog windows (called during some work on separate threads) in my application suddenly broke sometime around last month (noticed just today). They shouldn't have worked from the start because they are always called from another worker thread.

Anyway, is this normal behavior? Should user wrap all `IUIVisualizerService` calls inside dispatcher if there is possibility to run on other thread?

I always assumed that changing Catel properties or calling `IMessageService` or `IUIVisializerService` can be done from any thread and it seemed to work fine, but perhaps that was wrong approach.

Or maybe my problem is not with `IVisualizerService` call itself but with the ViewModel being created on a different thread?

**Comment by GeertvanHorrik** [comment]
Not all components are "thread- or dispatcher safe". With all the await stuff, we could have implemented this (check if dispatch is required, then dispatch, etc), but as you mention this is indeed not the case by default.

I think you can safely create your own implementation and override the method that actually shows the dialog. In that method, you can use the IDispatcherService and await the call there.

If the custom class works, then we are happy to embed it into Catel (probably 6.0) so it will benefit everyone :)

**Comment by ArXen42** [comment]
I'll be happy to improve Catel a little bit :)

I read implementation of `MessageService.ShowMessageBoxAsync`: it is "dispatcher-safe" but doesn't check current thread, just  `_dispatcherService.BeginInvoke` + `TaskCompletionSource`.
Going to try to do the same with `UIVisualizerService.CreateWindow`.

Just to clarify implementation details, one question: was there any particular reason to go with `TascCompletionSource` instead of `_dispatcherService.InvokeAsync(...)` (to avoid deadlock maybe) here?
```cs
        protected virtual Task<MessageResult> ShowMessageBoxAsync(string message, string caption = "", MessageButton button = MessageButton.OK, MessageImage icon = MessageImage.None)
        {
            Argument.IsNotNullOrWhitespace("message", message);

            var tcs = new TaskCompletionSource<MessageResult>();

            _dispatcherService.BeginInvoke(() =>
            {
                MessageBoxResult result;
                var messageBoxButton = TranslateMessageButton(button);
                var messageBoxImage = TranslateMessageImage(icon);

                var activeWindow = Application.Current.GetActiveWindow();
                if (activeWindow != null)
                {
                    result = MessageBox.Show(activeWindow, message, caption, messageBoxButton, messageBoxImage);
                }
                else
                {
                    result = MessageBox.Show(message, caption, messageBoxButton, messageBoxImage);
                }

                tcs.SetResult(TranslateMessageBoxResult(result));
            });

            return tcs.Task;
        }     
```

**Comment by GeertvanHorrik** [comment]
I think the reason is that Invoke might cause dreadlocks, begin invoke does not.

**Comment by GeertvanHorrik** [comment]
If you want, we can squeeze this one into 5.12.4 (otherwise you'll have to wait for 6.x to be released). Interested in helping out?

**Comment by ArXen42** [comment]
Oops, made working "fork" of `UIVisualizerService` that seems to work in my project, but still haven't send pull request, hope will be able to make one today.

**Comment by GeertvanHorrik** [comment]
you can also send the file and I will embed it, whatever you prefer!

**Comment by ArXen42** [comment]
Well, at least for now you can review this change if you'll have time:
https://gist.github.com/ArXen42/fbe0c66152895d07fd3a419430fe9f22

I had to make CreateWindow (and all overloads using it) async:
```cs
		protected virtual async Task<FrameworkElement> CreateWindow(Type windowType, Object data, EventHandler<UICompletedEventArgs> completedProc, Boolean isModal)
		{
			var tcs = new TaskCompletionSource<FrameworkElement>();

			_dispatcherService.BeginInvoke(
				() =>
				{
					var window = ViewHelper.ConstructViewWithViewModel(windowType, data);

					if (isModal)
					{
						var activeWindow = GetActiveWindow();
						if (!ReferenceEquals(window, activeWindow))
						{
							PropertyHelper.TrySetPropertyValue(window, "Owner", activeWindow);
						}
					}

					if (window != null && completedProc != null)
					{
						HandleCloseSubscription(window, data, completedProc, isModal);
					}

					tcs.SetResult(window);
				}
			);

			return await tcs.Task;
		}
```

I will try to make Catel solution load on my PC today and make these changes to Catel source file (my file is totally reformatted and merged with `UIVisualizerService.wpf.cs` file, so can't just copy paste). Also, I guess same changes will be needed for UWP.

**Comment by GeertvanHorrik** [comment]
Thanks, will try to use it.

**Comment by GeertvanHorrik** [comment]
Thanks, was able to put this into Catel. Please review the attached commit.

**Comment by ArXen42** [comment]
Thanks!
This seems like all changes I did, but shouldn't there also be similar changes in UIVisualizerService.uap.cs? From my understanding it won't compile without changing CreateWindow to async version there too.

**Comment by GeertvanHorrik** [comment]
Uap is not on the supported platforms for now. Too much work to support and we might revisit for 6.0

**Comment by ArXen42** [comment]
All right, didn't notice that uap code is not used now.
Thanks for embedding this! Guess issue can be closed now.

**Comment by GeertvanHorrik** [comment]
Thanks for confirming the fix. Note that it's already available in the latest beta available on NuGet.
