### ISSUE TITLE
Support .NET Core only starting with Catel 6.0

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1547]
We are considering to only support .NET Core starting with Catel 6.0. This means we could, in theory, get rid of quite some components since they are now in .NET Core out of the box (such as logging, dependency injection, etc).

For the people that are unable to move forward / have to stick with .NET 4.x, we will support (paid!) 5.x Catel versions. 

Moving to .NET Core will significantly decrease the maintainability footprint and allow us to move faster in smaller iterations.

**Comment by bigworld12** [comment]
I completely agree to this, but by .net core, are you referring to .net standard for `Catel.Core` or .net core ?

**Comment by GeertvanHorrik** [comment]
We could consider supporting .net standard. But... I think everything in the future will be .net core and .net standard will die a silent death (similar to PCL).

**Comment by bigworld12** [comment]
well based on this article here
https://devblogs.microsoft.com/dotnet/introducing-net-5/
.net standard will remain, and .Net 5 will remain and replace .net framework and .net core

**Comment by GeertvanHorrik** [comment]
> Do we still need .NET Standard? We are working through these issues now and will soon be sharing design docs for you to read and give feedback on.

I read this as in: it might no longer be required and will be gone in the future. But let's not throw away anything until we are sure. We will support .NET Standard / .NET Core for Catel.Core as I foresee it now.

**Comment by GeertvanHorrik** [comment]
We now know that .NET Standard will go away eventually. Let's postpone this decision to 7.0 (.net core will be the standard by then, and maybe we only have to target net5 / net6 / net7 by then).

**Comment by GeertvanHorrik** [comment]
Moving towards Catel 6.0. We are already going to target .netcoreapp3.1 / net5.0 only for all the other components we support, taking off the burden from the development team and increase build performance.

**Comment by vaecors** [comment]
As this is an obvious point of architectural contention (we're facing this internally ourselves) I'm going to also add this to the comment chain as a reference just as an extra input. As we're not adopting until .NET 6 we're on the fence whether we should target .netstandard2.1 or just straight .net6.0 depending on use the case:

https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/

**Comment by GeertvanHorrik** [comment]
Catel 6 is now .NET 6 only (and will include LTS .NET frameworks in the future).
