### ISSUE TITLE
Deadlock in ExpressionTreeObjectAdapter.GetMemberValue

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1550]
- [x ] WPF

## Component

class ExpressionTreeObjectAdapter, method GetMemberValue, line 60: if(!_fastMemberInvokerCache.TryGetValue...

## Version of Library
Catel.Core 5.12.3

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
i'v tried to reproduce it with a simple unit test, but the bug doesn't appear in this scenario.

## Expected Behavior
no deadlocks in parallel treads

## Actual Behavior
the deadlock appears always when i try to copy a lot of model objects in Parallel.ForEach.
This models are derived from ValidatableModelBase. If i change to ModelBase, my code runs properly. 

see attached screenshort.
![DeadLock_ExpressionTreeObjectAdapter_fastMemberInvokerCache](https://user-images.githubusercontent.com/13942501/76315032-359a8b00-62d8-11ea-9dd0-e3c82a3d7d29.png)

**Comment by GeertvanHorrik** [comment]
Care writing a small unit test / repro? Then we can test + release a hotfix for this.

**Comment by GeertvanHorrik** [comment]
We are now working on 5.12.4, please provide more info if you want this fixed in Catel 5.x, otherwise it will be planned for 6.x

**Comment by gofrogi** [comment]
i already tried to reproduce this behavior in a simple unit test but i couldn't. As a solution i derived my models from ModelBase instead from ValidateableModelBase. This solved my problem. But i will continue locking.

**Comment by GeertvanHorrik** [comment]
Will try to embed locks around it to prevent deadlocks.

**Comment by GeertvanHorrik** [comment]
Pushed a potential fix. I will release a beta for 5.12.4 soon, you might want to try that one.

**Comment by gofrogi** [comment]
this issue seems to has been fixed. My tests are successful.


Am Fr., 20. März 2020 um 10:18 Uhr schrieb Geert van Horrik <
notifications@github.com>:
