### ISSUE TITLE
XAML FocusMoment not working for EventName MouseLeftButtonUp

### ISSUE THREAD

**Issue by blearyeye3** [Catel/Catel#1566]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

WPF

## What component is this issue occurring in? 
Catel.MVVM (I think)

## Version of Library: 
5.12.4

## Version of OS(s) listed above with issue: 
Windows 10

## Steps to Reproduce
1. Create Catel WPF solution in Visual Studio on PC.
2. Paste in Window XAML shown below.
3. Click on control named mouseLeftButton

## Expected Behavior
Focus should go to control named testTarget

## Actual Behavior
Focus stays on mouseLeftButton

## Window XAML

```
<catel:Window x:Class="CatelTestFromScratch.Views.MainWindow"
              xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
              xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
              xmlns:catel="http://schemas.catelproject.com"
              xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
              ResizeMode="CanResize">
    <Window.Resources>
        <Style TargetType="TextBox">
            <Setter Property="VerticalAlignment" Value="Center"/>
            <Setter Property="HorizontalAlignment" Value="Center"/>
            <Setter Property="Margin" Value="0,10,0,0"/>
            <Setter Property="FontSize" Value="20"/>
        </Style>
    </Window.Resources>

    <Grid>
        <StackPanel VerticalAlignment="Center">
            <TextBox Name="testTarget"  Text="Test Target" Background="Aquamarine">
                <i:Interaction.Behaviors>
                    <catel:Focus FocusMoment="Event" Source="{Binding ElementName=mouseEnter}" EventName="MouseEnter" FocusDelay="0" />
                    <catel:Focus FocusMoment="Event" Source="{Binding ElementName=mouseLeftButtonUp}" EventName="MouseLeftButtonUp" FocusDelay="0"/>
                </i:Interaction.Behaviors>
            </TextBox>
            
            <TextBox Name="mouseEnter" Text="Mouse Enter"/>
            <TextBox Name="mouseLeftButtonUp" Text="Left Button Up"/>
        </StackPanel>
    </Grid>
</catel:Window>

```

See also this [StackOverflow question](https://stackoverflow.com/q/61122106/3657408)

**Comment by GeertvanHorrik** [comment]
When I directly subscribe to the events (as in regular event handlers), the events are not fired either, so that's the core of the issue.

**Comment by GeertvanHorrik** [comment]
See https://stackoverflow.com/questions/318288/wpf-mouseleftbuttonup-not-firing. The solution is to use `PreviewMouseLeftButtonUp` (which is always invoked, no matter whether it's handled or not).

**Comment by blearyeye3** [comment]
In that same question, [ILIA BROUDNO](https://stackoverflow.com/a/50263185/3657408)  notes that this means mixing tunneling with bubbling, which can get confusing, and suggests a way to resolve it. 

Perhaps `catel:Focus` could have a Boolean argument `HandledEventsToo`, parallel to that of `UIElement.AddHandler`.

**Comment by GeertvanHorrik** [comment]
Could be. We haven't had the need yet, but you are free to provide a PR ;-)

Note though that this will probably only added to Catel 6.x, we only do hotfixes if we need it ourselves or paying customers.
