### ISSUE TITLE
TypeFactory.CreateInstanceWithParametersAndAutoCompletion does not "auto-complete"

### ISSUE THREAD

**Issue by lipchev** [Catel/Catel#1587]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!
Does this include this top line or is it safe to delete it? :)

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component

Catel.IoC

## Version of Library

5.12.5

## Version of OS(s) listed above with issue

Win 10

## Steps to Reproduce
1. Register one or more dependencies via the service locator
2. Obtain a type factory
3. Try to CreateInstanceWithParametersAndAutoCompletion  providing the _remainder_ of the missing parameters 

I've uploaded a tiny [repro here](https://github.com/lipchev/CreateInstanceWithParametersAndAutoCompletion)..

## Expected Behavior

Object constructed with part of the constructor parameters resolved via the DI, the remainder provided via the `params object[] parameters` argument

## Actual Behavior

As far as I can see the evaluation of [this line](https://github.com/Catel/Catel/blob/9654364c1718ff5cbd00c9492a409810ead0869a/src/Catel.Core/IoC/TypeFactory.cs#L404) causes it to skip the automatic DI part in my example.

**Comment by GeertvanHorrik** [comment]
Unfortunately it doesn't work this way. The method was implemented to support injecting 1 or more parameters, then resolve the remainders from the IoC container.

I think this is fairly easy to implement as an extension method, but don't see this happening for a 5.x release (earliest on 6.x).

**Comment by lipchev** [comment]
Right, I see- I've never really thought about it- but I assume the same restriction applies for the order of the Model parameter in a ViewModel..
