### ISSUE TITLE
Catel.Logging problem

### ISSUE THREAD

**Issue by abrca** [Catel/Catel#1588]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] .NET Core

## Component

What component is this issue occurring in?
Catel.Logging

## Version of Library
nuget 5.12.5

## Version of OS(s) listed above with issue
Windows 10 x64

## Steps to Reproduce
1. Write small console app:
```

namespace ConsoleApp1
{
    using System;
    using Catel.Logging;

    class Program
    {
        private static readonly ILog Log = LogManager.GetCurrentClassLogger();

        static void Main(string[] args)
        {
#if DEBUG
            LogManager.AddDebugListener();
#endif

            LogManager.AddListener(new FileLogListener { FilePath = @"{WorkDir}\{AutoLogFileName}" });

            Log.Info("Catel log start");

            Console.WriteLine("Hello World!");

            Log.Info("Catel log stop");
        }
    }
}

```
2. Run it
3. Search for log :)

## Expected Behavior
File log created and filled with at least two info messages

## Actual Behavior
File log is written in async manner? If program quit too fast, log have no time to be written.
Adding 
`System.Threading.Tasks.Task.Delay(5 * 1000).Wait();`
at last line of example gives time to create empty log (in my case). And 10 seconds delay is enough to write all info.

**Comment by GeertvanHorrik** [comment]
I think you can (or should) call LogManager.FlushAsync() at the end of the program.

**Comment by abrca** [comment]
FlushAllAsync() works, thanks!
