### ISSUE TITLE
Use Microsoft.Xaml.Behaviors.Wpf instead of Expression.Blend.Sdk.WPF

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1595]

**Comment by GeertvanHorrik** [comment]
could be breaking change, but we have to go through this to fully support .NET Core

**Comment by vaecors** [comment]
It appears that a portion of the breaking changes are [namespace based](https://github.com/MahApps/MahApps.Metro/issues/3400#issue-389952762)

**Comment by GeertvanHorrik** [comment]
Correct. We decided to do this (even if it's considered a breaking change) because we need it in our apps and our (larger) theming capabilities improvements in Orc.Theming and all the other Orc libraries. We are nearly done and this will bump all of the Orc libraries to 4.x.

Keeping the Expression.Blend.Sdk for non-core projects was impossible because it would be too much pain (more than we are willing to / can take) to allow behaviors in multi-targeting xaml files.

**Comment by vaecors** [comment]
If I'm not mistaken Expression.Blend.Sdk is deprecated as well isn't it? So the move overall is a good idea.

**Comment by GeertvanHorrik** [comment]
Yes, and it does not support .NET Core, so this is definitely a step in the right direction.
