### ISSUE TITLE
Improve the logo

### ISSUE THREAD

**Issue by FJduFou** [Catel/Catel#1607]
Hi,
I am a person who pays great attention to the graphic side, and when I saw the logo, I asked myself: why a old logo and with white parts and the old shadow system ?
![image](https://user-images.githubusercontent.com/46401854/84265025-72b62980-ab22-11ea-9aff-57c0421e68b0.png)
I have made for you a new logo, I present the result to you, I can make it evolve as you wish if you want...
![image](https://user-images.githubusercontent.com/46401854/84265259-dc363800-ab22-11ea-9520-045cc4a87874.png)

**Comment by GeertvanHorrik** [comment]
Thank you for taking the effort to recreate the logo. Can I ask what the reasoning is for creating this icon? I can't remember any other messages from you and creating a new logo for such a project must have been quite some work?

**Comment by FJduFou** [comment]
Thx
I have create this icon because i have view you icon, and, sorry, it's horrible for me, just when I explore in Github
You don't remember me because it's the first time I write/contribute
No, it's very fast, I just have modernize...

**Comment by FJduFou** [comment]
up

**Comment by mkhomutov** [comment]
I like it

**Comment by FJduFou** [comment]
UP
