### ISSUE TITLE
Remove class constraint on FastMemberInvoker to support structs

### ISSUE THREAD

**Issue by Averus-a** [Catel/Catel#1610]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [x] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
Catel
Catel.MVVM
## Version of Library
5.12.7-beta3

## Version of OS(s) listed above with issue
Win10

## Steps to Reproduce
Repo to reproduce https://github.com/Averus-a/Catel-autocompletion-repro
1. Configure Exception Settings to stop on TypeLoadException
2. Start application
3. See first-chance exception thrown from ExpressionTreeObjectAdapter

## Expected Behavior
Actually, the FastMemberInvoker<T> constraint T to be class, so there is a problem if binded collection's item is struct typed. But the list of suggestions returned from behavior is empty.

## Actual Behavior

**Comment by GeertvanHorrik** [comment]
Fixed.
