### ISSUE TITLE
Always generate AdornerLayer for DataWindow to make sure validation results can be shown

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1615]
- [x ] WPF
 - [x ] .NET Standard
 - [ x] .NET Core

## Component
DataWindow with different type of validation rules in the model.

## Version of Library
5.12.6

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. build the attached repro
2. start the program and see the validation results in main window and how the differs from the DataWindow created by click on the button

## Expected Behavior
In both windows the textboxes Name and Description2 should appear with red boxes because of the validation errors. The validation messages should appear in the pull down list.

## Actual Behavior
In DataWindow - dialog the invalid fields are not markt with read box. Only if you enter something in there and then empty the field again, you would see the red box.
DeferValidationUntilFirstSaveCall = false; in both cases.
[TestValidation.zip](https://github.com/Catel/Catel/files/4811893/TestValidation.zip)

**Comment by GeertvanHorrik** [comment]
@gofrogi, we did fix a bug in the upcoming beta (5.12.7 beta), can you please try that one?

**Comment by gofrogi** [comment]
i tried it, but nothing changed :( 
![image](https://user-images.githubusercontent.com/13942501/85367672-fcee8c80-b529-11ea-82eb-9afa993c0c2a.png)

**Comment by GeertvanHorrik** [comment]
With the latest beta and `DeferValidationUntilFirstSaveCall` set to true:

![image](https://user-images.githubusercontent.com/1246444/85379622-43e57d80-b53c-11ea-9d23-066d3f4f92de.png)

**Comment by GeertvanHorrik** [comment]
This only works when the model is not yet validated. I think at model initialization, Catel needs to check the validation code. Will check if this is an easy fix and worth the trouble for us.

**Comment by gofrogi** [comment]
but why it is working in the class Window? Why not in the DataWindow? Could be a workaround building my own DataWindow, derived from Window?

**Comment by GeertvanHorrik** [comment]
This is an edge case scenario where you:

1. Use an already validated model (so no validation events occur!)
2. Use view model to model mappings (so it should read the validation from the model and expose it via the VM)

I am implementing unit tests and initialize validation checks of exposed properties now, which I think should fix the issue.

**Comment by GeertvanHorrik** [comment]
The reason it's working in the Window class is because that is the first time the model gets validated (and thus the VM for the window class get change events for the validation). If you disable validation in the window class and allow the child VM to validate the object, all works fine.

**Comment by GeertvanHorrik** [comment]
The model validation kicks in because `ValidateModelsOnInitialization` is set to `true`. This causes the model error info (metadata about the model) to be aware of the validation context of the model.

**Comment by gofrogi** [comment]
> The reason it's working in the Window class is because that is the first time the model gets validated (and thus the VM for the window class get change events for the validation). If you disable validation in the window class and allow the child VM to validate the object, all works fine.

in this case i have used different models for each of VM and different VMs for each of Window. Why depends DataWindow from Window then?

**Comment by gofrogi** [comment]
> The model validation kicks in because `ValidateModelsOnInitialization` is set to `true`. This causes the model error info (metadata about the model) to be aware of the validation context of the model.

i tried it, but with the same "success".  Error messages there, but red box absent. This property seems not to change anything.

**Comment by GeertvanHorrik** [comment]
I am still investigating, it's a complex issue ;-)

**Comment by GeertvanHorrik** [comment]
Ok, found something interesting. I think it's the WPF rendering that does not show up initial binding errors out the box. If I move the initialization of the model to InitializeAsync:

```
public class DataViewModel : ViewModelBase
{
    private readonly ModelClass2 _model;

    public DataViewModel(ModelClass2 model)
    {
        DeferValidationUntilFirstSaveCall = false;
        _model = model;
    }

    [Model]
    [Expose("Name")]
    [Expose("Description")]
    [Expose("Description2")]
    public ModelClass2 Model { get; set; }

    public override string Title { get { return "Welcome to DataWindow TestValidation"; } }


    protected override Task InitializeAsync()
    {
        Model = _model;

        return base.InitializeAsync();
    }
}
```

It works perfect. I am trying to figure out a good way to solve this without breaking anything.

**Comment by GeertvanHorrik** [comment]
So the combination seems to be:

1. DeferValidationUntilFirstSaveCall = false
2. Model is set in the ctor (so bindings are not yet active)

**Comment by GeertvanHorrik** [comment]
Interesting, it seems to be this problem:

http://www.andyfrench.info/2014/03/validation-adorners-not-displaying-in.html

So at startup, in very specific cases, the adorner layer is not yet present.

**Comment by GeertvanHorrik** [comment]
Releasing latest beta now.

**Comment by gofrogi** [comment]
I checked the new beta in my test project. It locks and works fine. Thank you for your Effort! I have to test our big solution with this packages version, but for now this ticked can be closed, i guess.
