### ISSUE TITLE
Dictionary serialization in ModelBase failes for .NET Core

### ISSUE THREAD

**Issue by mennodeij** [Catel/Catel#1642]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [X] .NET Core

## Component

What component is this issue occurring in?
Catel.Core

## Version of Library
5.12.8 most recent 

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. build and run unit tests in attached solution
2.
3.

## Expected Behavior
both unit tests pass

## Actual Behavior
only the unit test with workaround
[CatelPocoAsDictionaryKeys.zip](https://github.com/Catel/Catel/files/5108836/CatelPocoAsDictionaryKeys.zip)

**Comment by GeertvanHorrik** [comment]
Sounds like an extreme scenario, probably not covered by the unit tests. Can you provide a unit test so we can see what's happening? I can't promise a fix though, don't want to mess too much with the serialization engine.

**Comment by mennodeij** [comment]
unit test is attached in zip-file.

**Comment by GeertvanHorrik** [comment]
Just migrated the unit tests to .NET Core and indeed see failure in serialization of dictionary. Will see if I can squeeze it into the next hotfix.

**Comment by GeertvanHorrik** [comment]
Issue seems to be in *deserialization*. Working on a fix.

**Comment by GeertvanHorrik** [comment]
Looks like serialization itself is actually working in the unit test, it's the binary serializer that is failing (which is fine, shouldn't be used anyway).

**Comment by GeertvanHorrik** [comment]
Serialization is fixed, now looking into the poco class serialization stuff.

**Comment by GeertvanHorrik** [comment]
Serialized xml:

```
<?xml version="1.0" encoding="utf-8"?>
<FailToSerialize xmlns:ctl="http://schemas.catelproject.com" xmlns:i="http://www.w3.org/2001/XMLSchema-instance" ctl:graphid="1">
  <Items>
    <SerializableKeyValuePair ctl:graphid="2" xmlns:x="http://www.w3.org/2001/XMLSchema" xmlns:d0p0="http://schemas.datacontract.org/2004/07/Catel.Runtime.Serialization" i:type="d0p0:SerializableKeyValuePair">
      <Key xmlns:d1p1="http://schemas.datacontract.org/2004/07/Catel.Tests.Runtime.Serialization" i:type="d1p1:GenericSerializationFacts.DictionarySerialization.PocoKeyClass">
        <d1p1:X>1</d1p1:X>
        <d1p1:Y>2</d1p1:Y>
        <d1p1:Z>3</d1p1:Z>
      </Key>
      <Value i:type="x:string">test me</Value>
    </SerializableKeyValuePair>
  </Items>
</FailToSerialize>
```

**Comment by GeertvanHorrik** [comment]
Issue is that during deserialization, the known types is not respected. Fixing.

**Comment by GeertvanHorrik** [comment]
Thanks for the great unit test, this made it so much easier to fix this issue.

![image](https://user-images.githubusercontent.com/1246444/92714458-8872ff00-f35c-11ea-883c-6b58cc5d9803.png)

**Comment by GeertvanHorrik** [comment]
@mennodeij  Please try Build - 5.12.9-beta.19 (being released right now, should be ready in 20 minutes) and let us know whether it's fixed.

**Comment by GeertvanHorrik** [comment]
Closing the ticket since the unit tests succeed. Assuming the bug is fixed.
