### ISSUE TITLE
InvalidateCommandManagerOnViewModelInitializationAuditor instance creation fails during MainWindow initialization

### ISSUE THREAD

**Issue by Averus-a** [Catel/Catel#1651]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
Catel.Core
## Version of Library
starting from 5.12.9-beta0015 version

## Steps to Reproduce
1. https://github.com/Averus-a/Catel_5.12.9_bug - barely empty project with only catel core and mvvm installed
2. Run project and see unhandled exception in CacheStorage ctor (equalityComparer passed here is null)
3. Callstack:
```csharp
>	Catel.Core.dll!Catel.Caching.CacheStorage<string, System.Collections.Generic.List<System.Reflection.ConstructorInfo>>.CacheStorage(System.Func<Catel.Caching.Policies.ExpirationPolicy> defaultExpirationPolicyInitCode, bool storeNullValues, System.Collections.Generic.IEqualityComparer<string> equalityComparer) Line 88	C#
 	Catel.Core.dll!Catel.IoC.TypeFactory.TypeMetaData.TypeMetaData(System.Type type) Line 828	C#
 	Catel.Core.dll!Catel.IoC.TypeFactory.GetTypeMetaData.AnonymousMethod__0() Line 361	C#
 	Catel.Core.dll!Catel.Threading.ReaderWriterLockSlimExtensions.PerformUpgradableRead<Catel.IoC.TypeFactory.TypeMetaData>(System.Threading.ReaderWriterLockSlim lockSlim, System.Func<Catel.IoC.TypeFactory.TypeMetaData> criticalOperation) Line 113	C#
 	Catel.Core.dll!Catel.IoC.TypeFactory.GetTypeMetaData(System.Type type) Line 354	C#
 	Catel.Core.dll!Catel.IoC.TypeFactory.CreateInstanceWithSpecifiedParameters(System.Type typeToConstruct, object tag, object[] parameters, bool autoCompleteDependencies) Line 284	C#
 	Catel.Core.dll!Catel.IoC.TypeFactory.CreateInstanceWithTag(System.Type typeToConstruct, object tag) Line 146	C#
 	Catel.Core.dll!Catel.IoC.TypeFactory.CreateInstance(System.Type typeToConstruct) Line 134	C#
 	Catel.Core.dll!Catel.IoC.TypeFactoryExtensions.CreateInstance<Catel.MVVM.Auditing.InvalidateCommandManagerOnViewModelInitializationAuditor>(Catel.IoC.ITypeFactory typeFactory) Line 27	C#
 	Catel.MVVM.dll!Catel.MVVMModule.Initialize(Catel.IoC.IServiceLocator serviceLocator) Line 46	C#

```

## Expected Behavior
The app should run without any exception

## Actual Behavior
Exception thrown, confirmed it works with 5.12.8 of Catel.Core

**Comment by GeertvanHorrik** [comment]
Investigating

**Comment by GeertvanHorrik** [comment]
Trying new app (built with Catel project template), replaced version to 5.12.9-beta0020 and it doesn't throw this exception.

**Comment by GeertvanHorrik** [comment]
Cloning your repo.

**Comment by GeertvanHorrik** [comment]
Your repro throws the exception, looking for a fix now.

**Comment by GeertvanHorrik** [comment]
Interesting, I only replaced a Dictionary with ConcurrentDictionary. Would expect it to behave the same, but apparently you cannot pass in null here. Fixing.

**Comment by GeertvanHorrik** [comment]
Fixed, thanks for reporting!
