### ISSUE TITLE
ArgumentNullException when using ViewModelToModelMapping on property of concrete model that does not have this property

### ISSUE THREAD

**Issue by monkey123q** [Catel/Catel#1669]
- [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Version of Library
Starting from 5.12.4

## Steps to Reproduce
1. Clone https://github.com/monkey123q/CatelRepro
2. Run test

## Expected Behavior
ArgumentNullException has occured

## Actual Behavior
Property mapping works

**Comment by GeertvanHorrik** [comment]
We just closed a hotfix a few days ago... I am tempted to only fix this in Catel 6. Need to investigate first.

**Comment by GeertvanHorrik** [comment]
Thanks for the great unit tests 👍

**Comment by GeertvanHorrik** [comment]
The reason is because Catel checks the model type, not the actual instance. The `Name` property is defined on `DogModel`, not on `AnimalModelBase`, therefore it cannot retrieve the type info.

Investigating what we can do about this.

**Comment by GeertvanHorrik** [comment]
Fixed, in this *specific case*, Catel now defaults to typeof(object) which seems to work fine.

**Comment by GeertvanHorrik** [comment]
Done.
