### ISSUE TITLE
Validation messages don't appear for child windows when using content presentors

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1670]
- [x ] WPF
 - [ x] .NET

## Component
DataWindow

## Version of Library
Catel 5.12.8

## Version of OS(s) listed above with issue
Win 10

## Steps to Reproduce
Build and run the attached repro.

## Expected Behavior
alle validation errors and warning should immediately appear in the pull-down list. The Ok-Button should be disabled and the field with errors should be surrounded by a red border.

## Actual Behavior
this is a followup ticket of https://github.com/Catel/Catel/issues/1615#issue-642840804

Thought the issue that was described in the issue above was fixed i still find constellations where it doesn't work. Check my repro. I changed it a bit. Now the DataWindow has a embedded UserCotrol, that have a Model with validation errors. It seems always to be a issue when one o more embedded controls have been using. 
 
[TestValidation2.zip](https://github.com/Catel/Catel/files/5306654/TestValidation2.zip)

**Comment by GeertvanHorrik** [comment]
The issue seems that the validation already occurred before the `WarningAndErrorValidator` is attached and will not notify about the "delta". Trying a potential fix.

**Comment by GeertvanHorrik** [comment]
Done. Please let me know if Build - 5.12.10-beta.4 fixes it for you (should be available in about 20 minutes).
