### ISSUE TITLE
ViewModelBase constructor memory leak

### ISSUE THREAD

**Issue by lipchev** [Catel/Catel#1712]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

ViewModelBase + ServiceLocator

## Version of Library

5.12.10

## Version of OS(s) listed above with issue

win 10

## Steps to Reproduce
1. Using the [Catel.GettingStarted.WPF](https://github.com/lipchev/Catel.GettingStarted.WPF) (updated to latest WPF versions & with an extra [50mb of bytes added in the FamilyWindow](https://github.com/lipchev/Catel.GettingStarted.WPF/blob/6f0d65aa22de6bab420284daf70b75bfdb26aebe/WPF.GettingStarted/Views/FamilyWindow.xaml.cs#L12)) 
2. Start the application - and observe the initial ram usage (Snapshot 1)
3. Create one family (open and close the FamilyWindow)
4. Force GC and observe the new ram usage (Snapshot 2) - 50 mb retained
5. Repeat for last two steps for Snapshot 3 (note that before GC actual ram is +100mb)
6. After N iterations: ram remains at +50mb 

![image](https://user-images.githubusercontent.com/5253184/99732567-61f1e280-2ac8-11eb-8fdf-5a633480813b.png)

## Expected Behavior
After closing the window both View and ViewModel are removed from memory.

![image](https://user-images.githubusercontent.com/5253184/99733232-85695d00-2ac9-11eb-8e54-4638b4dab786.png)

## Actual Behavior
The DoubleClickToCommand holds the view in memory as it is bound to the viewModel command, which is routed to the ServiceLocator:

![image](https://user-images.githubusercontent.com/5253184/99734123-fb21f880-2aca-11eb-8084-1307430d7923.png)

This happens during the [creation of the IObjectIdGenerator<int>](https://github.com/Catel/Catel/blob/b0bee31ebda82a2a174f6559a01e13a3ba4cc9ec/src/Catel.MVVM/MVVM/ViewModels/ViewModelBase.cs#L204) . 
`            serviceLocator.RegisterType(typeof(IObjectIdGenerator<int>), x => GetObjectIdGeneratorType(), type, RegistrationType.Singleton, false);`

The function ` x => GetObjectIdGeneratorType()` referencing the current instance is added to the ServiceLocator's cache. 
Replacing the call with the one below produced the screenshot in the Expected Behavior section. All testes passed and I didn't notice any change in behavior with the test application.
``            serviceLocator.RegisterType(typeof(IObjectIdGenerator<int>), GetObjectIdGeneratorType(), type, RegistrationType.Singleton, false);``

**Comment by GeertvanHorrik** [comment]
Thanks for the detailed research, well done. I will investigate this asap.

**Comment by GeertvanHorrik** [comment]
I am not sure why we even chose to add this as a callback. It's a 1-time registration *per type* (so not ViewModelBase, but the actual type). Will try to refactor.

**Comment by lipchev** [comment]
It was probably meant for delayed resolution (avoiding the virtual constructor call), but the fact that the generator is actually resolved on the next line kills that idea..

**Comment by GeertvanHorrik** [comment]
Again, great research. Implemented a fix, could you please review the code to double check?

**Comment by GeertvanHorrik** [comment]
Build - 5.12.11-beta.7 is being deployed to NuGet right now.

**Comment by lipchev** [comment]
Tested with both the test application, and the projects inside my solution- everything looks good. (except for the small hiccup with #1716 but that is not related)

**Comment by GeertvanHorrik** [comment]
Thanks for confirming, closing this ticket.
