### ISSUE TITLE
StartProcess(path) from IProcessService doesn't work as used to

### ISSUE THREAD

**Issue by gofrogi** [Catel/Catel#1741]
- [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ x ] .NET Standard
 - [ x ] .NET Core

## Component

IProcessService

## Version of Library
Catel.Core and MVVM 5.12.10

## Version of OS(s) listed above with issue
Windows 10 20H2

## Steps to Reproduce
for this i created a console app with .netcore 3.1 and this main code:

        using Catel.IoC;
        using Catel.Services;
        using System;
        using System.Diagnostics;

        
        namespace IProcessServiceBug
        {
          class Program
          {
            static void Main(string[] args)
            {
              var path = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
              // using IProcessService to raise exprorer with path pre-selected
              var service = ServiceLocator.Default.ResolveType<IProcessService>();
        
              // it has been always enough to use service in .net like that.
              service.StartProcess(path);
              // explorer would be raised with path pre-selected.
        
              // Latterly it leads to a issue. We get a access denied exception.
              // that because it is an unintended side-effect of how things were done in .NET Framework, 
              // as Process.Start(string) was always meant to take a file name, not a folder path
              // In .NET Framework UseShellExecute was true in dotentcore it is false.
              // It works as expected if we create a ProcessStartInto with UseShellExecute = true
              ProcessStartInfo startInfo = new ProcessStartInfo(path) {
                 UseShellExecute = true
              };
              
              Process.Start(startInfo);
        
              // The IProcessService works also if called like this:
              service.StartProcess(new ProcessContext { FileName = path, UseShellExecute = true});
        
              // this issue leads to a problem in Orc.OpenFilePicker and Orc.DirectoryPicker
              // the folder button in those controls does nothing if you click on.
            }
          }
        }

## Expected Behavior
the well known behavior of StartProcess(path) should raise the explorer with pre-selected path.

## Actual Behavior
I noticed that in Orc.DirectoryPicker the folder button doesn't work. Version of Orc.Conrols 4.1.1, but my analysis has shown that the problem is Orc.Controls use Catel IProcessService that uses System.Diagnostic.Process.Start that causes the issue.

**Comment by GeertvanHorrik** [comment]
We have fixed this by adding "UseShellExecute" to the context parameter of the process service. We didn't want to *change* the behavior in .NET 5 / core because this is how MSFT (correctly) decided to make the default behavior.

If you want to use the shell to execute something (e.g. to open a folder), you can set `UseShellExecute` to `true`.

Another option is to run "explorer.exe" and use the directory as a parameter (but I prefer the UseShellExecute option).

**Comment by gofrogi** [comment]
actually my problem was in Orc.OpenFilePicker and Orc.DirectoryPicker, these depending on IProcessService.  Did you fix the issue there?

**Comment by GeertvanHorrik** [comment]
Not yet:

https://github.com/WildGums/Orc.Controls/blob/develop/src/Orc.Controls/Controls/DirectoryPicker/ViewModels/DirectoryPickerViewModel.cs#L81#1742

**Comment by GeertvanHorrik** [comment]
@ceo1647 please create a hotfix in Orc.Controls for this one.

**Comment by ceo1647** [comment]
fixed

**Comment by GeertvanHorrik** [comment]
Thank you, closing this ticket.
