### ISSUE TITLE
Modelbase property data is null during initilialization using singleton pattern

### ISSUE THREAD

**Issue by Marshmal2ow** [Catel/Catel#1750]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x] .NET Core

## Component
Modelbase 
PropertyData is null in constructor when using the singleton pattern

## Version of Library
Catel.Core 5.12.11

## Version of OS(s) listed above with issue
Win10 1909

## Steps to Reproduce

```

// try access 
var brush = DesignManager.Palette.ForegroundBrush ;

    public class DesignManager : ModelBase
    {
        public DesignManager()
        {
            // try set value
            ForegroundBrush = new SolidColorBrush(Colors.Black);
        }

        private static readonly DesignManager _palette = new DesignManager();
        public static DesignManager Palette => _palette;

        public Brush ForegroundBrush
        {
            get { return GetValue<Brush>(ForegroundBrushProperty); }
            set { SetValue(ForegroundBrushProperty, value); }
        }
        public static readonly PropertyData ForegroundBrushProperty = RegisterProperty(nameof(ForegroundBrush), typeof(Brush), null);
}
```

## Expected Behavior

Set value for property ForegroundBrush in constructor

## Actual Behavior
ForegroundBrushProperty  is null

throw exception:
System.TypeInitializationException
ArgumentNullException: Argument "property cannot be null
  This exception was originally thrown at this call stack:
    Catel.Argument.IsNotNull(string, object)
    Catel.Data.ModelBase.SetValue<TValue>(Catel.Data.PropertyData, TValue, bool)
    ...DesignManager.ForegroundBrush.set(System.Windows.Media.Brush) in DesignManager.cs
    ...DesignManager.DesignManager() in DesignManager.cs
    ...DesignManager.DesignManager() in DesignManager.cs

Inner Exception 1:
ArgumentNullException: Argument 'property' cannot be null

**Comment by GeertvanHorrik** [comment]
I think this actually has to do with static field initialization order. Because the static fields are initialized in the order they are available in, the static initializer calls the ctor when the static property is not yet available.

A good workaround for this is to use Lazy<DesingManager> instead of instantiating it immediately.

**Comment by Marshmal2ow** [comment]
First of all thanks for the fast and helpful answer.
Please excuse me for misleading and tagging this as a issue.
Your assumption is correct it has do with static field initialization order. 
I implemented it the way you suggested and it works as expected.
