### ISSUE TITLE
catel/fody object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Offline-R503B** [Catel/Catel#1766]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component
 
Catel/Fody

## Version of Library

Custom build from latest release in the case of orchestra (Mahapps + fluent, instead of one or the other)  otherwise standard latest release. 

## Version of OS(s) listed above with issue
All the OS's

## Steps to Reproduce
1. Fork/Clone Wolvenkit at : https://github.com/WolvenKit/Wolvenkit (DEV BRANCH)
2. regular steps to open a project / restore nugets.
3. build&run.  get error. 

## Expected Behavior
Press green button once to build and run the debug.

## Actual Behavior
Need to press green button twice always.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We will try to repro.

**Comment by GeertvanHorrik** [comment]
@Offline-R503B , have created the ticket in the Catel.Fody repro.

**Comment by Offline-R503B** [comment]
@GeertvanHorrik Thanks wasn't sure where to post it exactly but I think thats the correct spot yeah :)
