### ISSUE TITLE
Catel build fails if Dev Studio not installed in default location

### ISSUE THREAD

**Issue by mcpherson-sa** [Catel/Catel#1767]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component
Build system.

## Version of Library
5.5.12

## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. Run the PowerShell build script. 

## Expected Behavior
Build succeeds.

## Actual Behavior
Build fails.

I have VS installed in a non-default location and I noticed that the Cael source fails to build in this case. After some digging I found that in the relevant cake file. in which teh code looks in a number preset locations to try and find various editions of VS. Whilst it was easy enough to make the necessary change to the cake file to make the build work, it would be nice to build something into the scripts to handle this out of the box. Simplest thing would be to just provide a way to configure it without modifying the checked in cake files or try to find it automatically - maybe something like the approach here: 

https://stackoverflow.com/questions/30504/programmatically-retrieve-visual-studio-install-directory in the answer by lauxjpn. 

Other approaches on this page that try to read HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\<version>\InstallDir don't seem to work anymore as that key doesn't exist on my machine (I have 2019 pro).

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. Are you interested in doing a PR with a fix?

**Comment by GeertvanHorrik** [comment]
Here is the logic located:

https://github.com/catel/catel/blob/develop/deployment/cake/lib-msbuild.cake#L249
