### ISSUE TITLE
How does DeferValidationUntilFirstSaveCall work?

### ISSUE THREAD

**Issue by ttustonic** [Catel/Catel#1803]
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)

Documentation for `DeferValidationUntilFirstSaveCall ` says that 

> If this value is true, all validation will be suspended

However, I'm running a `Catel.Examples.WPF.Validation` example and, no matter what is the value for the `DeferValidationUntilFirstSaveCall` in the ValidationWithValidateMethodsViewModel both `ValidateFields` and `ValidateBusinessRules` methods are called multiple times before any saving. The only difference is that error messages are not shown when this value is true.

Is this a bug, or is this supposed to work this way? How can I really prevent business rules validation until saving? I have a long running rule which is called and failed multiple times in a row, even before any info is entered in the form.

Thanks, Tom

**Comment by GeertvanHorrik** [comment]
I think, along the way, we changes this from not validating to validate but hide validation results. This way we could map states to the validation context without exposing them immediately to the end user.

If you have an expensive validation rule, I suggest that you check for both `IsValidationSuspended` and `HideValidationResults` to be false, and only then check the expensive rule.

Another option would be to only check the expensive rule during save (and return false when the rule fails).
