### ISSUE TITLE
NullReferenceException in XmlSerializer.BeforeDeserialization

### ISSUE THREAD

**Issue by pascalgross** [Catel/Catel#1901]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x ] .NET Core

## Component

Catel.Core / Catel.MVVM

## Version of Library

5.12.22

## Version of OS(s) listed above with issue
Windows 10 Pro

## Steps to Reproduce
ViewModel has some weaved properties:

```
public class PartEditViewModel : ViewModelBase
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;

        [Model]
        [Expose("Number")]
        [Expose("Description")]
        public Part Part { get; set; }
...
```
The model Inherits Catel.Core's ModelBase.
When I close the view (Catel.Windows.Window) I guess Catel tries to reset the model (the model does not have any changes I know of) but it throws an exception I can't interpret.

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Catel.Runtime.Serialization.Xml.XmlSerializer.BeforeDeserialization(ISerializationContext`1 context)

Do I need to prepare anything for serialization to work? I'm using EF core if this is relevant.
I'm unable to junp into the code of catel to see what is happening - is there a symbolserver I can use?

**Comment by pascalgross** [comment]
Today, the error is gone. Mysterious.
I'll close it for now.

**Comment by pascalgross** [comment]
Following up https://stackoverflow.com/questions/70142139/reset-model-to-initial-state-in-catel

I think those issues are related.
I've tried to create a repro (https://github.com/pascalgross/ModelReset).

Creating the repro I noticed that it might have to do with LazyLoading and EF Core.
To use the repro, you might have to adjust the connection string in ModelReset.DAL.ApplicationContext.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. Unfortunately we have other priorities where this is a non-blocking issue. When we have time in the future or when this bug affects us, we will look into this.

**Comment by GeertvanHorrik** [comment]
Closing this since it seems related to EF. If it's still an active issue that we could fix for Catel 6.x, feel free to re-open.
