### ISSUE TITLE
ShowAsync returns Null when closing a Dialog

### ISSUE THREAD

**Issue by Mazzelfassel** [Catel/Catel#1916]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

IUIVisualizerService & IUIVisualizerServiceExtensions

## Version of Library
5.12.22

## Version of OS(s) listed above with issue
Win 10

## Steps to Reproduce
Open a Dialog like this

```c#
IUIVisualizerService uiservice = this.GetServiceLocator().ResolveType<IUIVisualizerService>();
bool? res = await uiservice.ShowAsync<TestViewModel>(new TestModel());
```
and close the Dialog normally by hitting the OK button.

after this `res` should be _true_ but instead is _null_. This error occoured in my own project (Using Orchestra and other libaries) and a simple test project I setup for this issue. 

After checking the code I found that `ShowContextAsync` is used inside the extension so I tried it again like this:
```c#
IUIVisualizerService uiservice = this.GetServiceLocator().ResolveType<IUIVisualizerService>();
TestViewModel vm = this.GetTypeFactory().CreateInstanceWithParametersAndAutoCompletion<TestViewModel>(new TestModel());
bool? res = await uiservice.ShowContextAsync(new UIVisualizerContext
{
    Data = vm,
    IsModal = true,
    CompletedCallback = null
});
```
The result was, that `res` was _true_ and it worked like intended.

Theoretically both methods  execute the same Functions but they behave differently.

**Comment by GeertvanHorrik** [comment]
The different between `Show` and `ShowModal` in Windows is the same. `ShowModal` is a *blocking* call and allows setting the `DialogResult`, the `Show` is a *non-blocking* call and does not allow setting the `DialogResult`.

**Comment by Mazzelfassel** [comment]
First, thank you for the fast reply. It indeed worked when I changed it to `ShowDialogAsync`. My guess is there was a change in the `ShowAsync` when I updated to 5.12.22. Before that my dialogs worked fine with `ShowAsync` and that's what confused me.
