### ISSUE TITLE
Consider specifying Foreground Color in InfoBarMessageControl

### ISSUE THREAD

**Issue by johncbaur** [Catel/Catel#1987]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
I am using the Orc Wizard, and it is using the InfoBarMessageControl to report errors.  This control display the following text in a TextBlock.  The TextBlock seems to have a light yellow background.

**"The following warnings and/or errors were found (hover to view):"**

The background for this TextBlock is specified by the style but it seems like the foreground (text color) is left unspecified.  The application I am using the Wizard in has a dark theme so the default text color is white.  White on light yellow does not read well.  Seems like if the background is being specified that maybe it is appropriate to also control the text color.

## API Changes

I believe the following TextBlock would benefit from having an explicit foreground color.

 <TextBlock Padding="4,2,4,2" Text="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type local:InfoBarMessageControl}}, Path=InfoMessage}" />

## Intended Use Case
This is to fix an issue I am experiencing with the Orc Wizard and to prevent us from having to modify the source.

**Comment by GeertvanHorrik** [comment]
I think this is a great idea. We have another open PR left as well so would consider release a new "hotfix" for this. Interested in doing a PR?

**Comment by johncbaur** [comment]
Yes I can do a PR.  Thank you.

**Comment by johncbaur** [comment]
I do have a question, when I run the Orc.Wizard Example application.  I enter my name advance to the Age page and then go back to the Person page clear out the names and attempt to go back to the Age page.  The InfoBarMessageControl is displayed and the bar looks orange-ish to me.  Where is this color coming from?  The InfoBarMessageControl.generic.xaml seems to read like it should be light yellow.  The application I am working on it is light yellow.  If you put your mouse over the bar you see the errors and their background is light yellow.  I sort of think the orange color looks better and stands out more.  I am hoping you might be able to point me to where this orange color is coming from?

**Comment by GeertvanHorrik** [comment]
I think the updated colors could come from [Orc.Theming](https://github.com/wildgums/orc.theming), where the theming of all controls (when using Orc components) is managed.

Here, for example, is the [InfoBarMessageControl style](https://github.com/WildGums/Orc.Theming/blob/develop/src/Orc.Theming/Themes/Controls.implicit.catel.infobarmessagecontrol.xaml).

**Comment by johncbaur** [comment]
Can we move forward with this PR?  I am not sure I could use Orc.Theming in my application without causing problems with other styling.

**Comment by GeertvanHorrik** [comment]
Yes, will try to look into this asap, but currently it's the holidays. Hopefully first week of the new year.

**Comment by GeertvanHorrik** [comment]
Approved and will be released to 6.x alpha todya.
