### ISSUE TITLE
Remove unnecessary references for netfx(net4x) targets

### ISSUE THREAD

**Issue by SelvinPL** [Catel/Catel#2032]
There is no need for netfx target to depend on `System.Configuration.ConfigurationManager` and `System.ComponentModel.Annotations` packages

The solution :
in Directory.Build.shared.explicit add `NETFX` in lines like  bellow for all $(TargetFramework) which starts with `net4`
`<DefineConstants>$(DefineConstants);NET;NET48;NET480</DefineConstants>`

then in project files remove
```
 <ItemGroup>
         ....
        <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
         ....
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
  </ItemGroup>        
```
and replace with:

```
  <ItemGroup Condition="$(DefineConstants.Contains(NETFX))">
         <Reference Include="System.ComponentModel.DataAnnotations" />
         <Reference Include="System.Configuration" />
  </ItemGroup>

  <ItemGroup Condition="'$(DefineConstants.Contains(NETFX)) == 'false'">
        <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
  </ItemGroup>
```

now all packages for net4x would not depend on eny external libraries

**Comment by GeertvanHorrik** [comment]
In the develop branch (upcoming Catel 6 release) only supports .NET core. Would this still be an issue in such case?

**Comment by SelvinPL** [comment]
No

**Comment by SelvinPL** [comment]
No
