### ISSUE TITLE
Deadlock in ServiceLocator

### ISSUE THREAD

**Issue by PatrickKursawe** [Catel/Catel#2048]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?

## Version of Library
Catel.Core 5.12.22

## Version of OS(s) listed above with issue
Windows 11

## Steps to Reproduce
1. Run parallel unit tests that resolve types that try to resolve their own dependencies from the constructor
2.
3.

## Expected Behavior
Should work

## Actual Behavior
End in deadlock (see screenshots)
![Deadlock1](https://user-images.githubusercontent.com/14345249/212046787-82ca3f63-c7e3-48de-9501-10d98c9780b9.png)
![Deadlock2](https://user-images.githubusercontent.com/14345249/212046820-d5af489c-af0a-4a7b-b87c-94f471d6e2d1.png)

Changing my code to use only injection in the constructor instead of calls to resolvetype seems to circumvent the problem.
at least I could not reproduce the deadlock.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. Is there a way you can provide this in a (failing) unit test format? Then we can try to embed the tests into catel and fix if possible.

**Comment by PatrickKursawe** [comment]
Will try to cook something up when I am done with removing that default constructor.

**Comment by PatrickKursawe** [comment]
Unfortunately, I can't reproduce the issue in a simplified test case, so maybe close this issue?

Looking at the catel source, though, something seems a little odd to me:

In ServiceLocatorExtensions.TryResolveType, the "this" (the service locator itself) is used as a lock object.
In ServiceLocator.IsTypeRegisteredInCurrentLocator, the dedicated internal lock object is used as a lock.
How can this result in a deadlock? Do you understand what is happening here?

What's the reason for locking in the extension method at all? That lock should not prevent anyone from removing the type between the check for registration and the attempt at object creation, as that method is using a different lock.
But this lock will result in a deadlock if some object that is created while resolving calls TryResolveType from a different thread in the constructor (for example because of GUI depending code). So, if you don't mind that I am wasting your time more than I already did, what scenario is the lock in the extension method supposed to avoid?
Thanks!

**Comment by GeertvanHorrik** [comment]
Great find about the lock in the service locator. I've removed the lock (it's not needed). We also worked on a fix that was caused by the ConfigurationService (took us a while to figure out). We will release a new alpha with the fixes soon.
