### ISSUE TITLE
StringToObjectHelper.ToRightType returns wrong values for type byte

### ISSUE THREAD

**Issue by thoblerone** [Catel/Catel#2070]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
Catel.Core

## Version of Library
5.12.22

## Version of OS(s) listed above with issue
Win 11 21 H2

## Steps to Reproduce
1. All tests within this test case are failing:
```
        [TestCase]
        public void ByteConversion()
        {
            var value = StringToObjectHelper.ToRightType(typeof(byte), "0");
            // returns 48
            Assert.AreEqual((byte)0, value);

            value = StringToObjectHelper.ToRightType(typeof(byte), "10");
            // returns 49
            Assert.AreEqual((byte)10, value);

            value = StringToObjectHelper.ToRightType(typeof(byte), "123");
            // returns 49
            Assert.AreEqual((byte)123, value);
            
            value = StringToObjectHelper.ToRightType(typeof(byte), "01");
            // returns 48
            Assert.AreEqual((byte)1, value);
        }
```

## Expected Behavior
Test completes successfully - StringToObjectHelper.ToRightType should return 0, 10, 123, 1 respectivly

## Actual Behavior
StringToObjectHelper.ToRightType returns 48, 49, 49, 48 respectivly

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. We'll try to get this fixed for Catel v6 (which we hope to release soon).

**Comment by GeertvanHorrik** [comment]
Should be fixed, releasing new alpha for Catel 6 now.
