### ISSUE TITLE
"Serializing delegates is not supported on this platform" exception in ChildAwareModelBase.BeginEdit method

### ISSUE THREAD

**Issue by Green7** [Catel/Catel#2139]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component
Catel.MVVM

## Version of Library
6.0.0-alpha1271

## Version of OS(s) listed above with issue
Windows 11

## Steps to Reproduce
ChildAwareModelBase class raises an exception "Serializing delegates is not supported on this platform" when calling the BeginEdit method.
This exception does not appear if Catel.Fody is not installed.
Here is a minimal example:

```
  public class CatelChildAwareModelTests
  {
    [Test]
    public void SerializingDelegatesExceptionTest()
    {
      var model = new TestModel();
      Assert.DoesNotThrow(() => (model as IEditableObject).BeginEdit());
    }

    private class TestModel : ChildAwareModelBase
    {
      public ObservableObject ChildProp { get; set; }

      public TestModel()
      {
        ChildProp = new ObservableObject();
      }
    }
  }
```

## Expected Behavior
  No exception.

## Actual Behavior
  Exception.

**Comment by GeertvanHorrik** [comment]
I *think* this has to do with a breaking change on the way properties are registered. Thanks for creating a repro, will look into this as soon as I have time.

**Comment by GeertvanHorrik** [comment]
Can reproduce, looking into this.

**Comment by GeertvanHorrik** [comment]
Solved by adding `[field:NonSerialized]` to the event on ObservableObject. Will release a new alpha soon.
