### ISSUE TITLE
Prevent duplicate property change notification when using ViewModelToModel attribute on models that don't check for equality before raising

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#2164]
See https://github.com/Catel/Catel.Fody/issues/531 for more details.

The solution is to get the existing value before assigning it in the model (but it will be "more expensive"). But since this feature is "expensive" anyway, it's reasonable.

**Comment by GeertvanHorrik** [comment]
@Green7 fix should be out on NuGet (prerelease).

**Comment by Green7** [comment]
@GeertvanHorrik It works 👍 Thank you.
