### ISSUE TITLE
Rename IPleaseWaitService to IBusyIndicatorService

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#691]
Jira issue originally created by user @geertvanhorrik:

Even considering to implement this in Catel.Core. Then we can show progress everywhere, and implement whatever we need in any library.

**Comment by GeertvanHorrik** [comment]
@vaecors / @bigworld12 what are your thoughts, should this be fixed or keep the current name?

**Comment by vaecors** [comment]
I guess it really depends on how many people are actually using it. I know we're not (we opt for Telerik instead for this). Renaming obviously means a breaking change unless maybe you rename it, preserve the old names as a wrapper and mark them as obsolete and remove them in 6.x

**Comment by GeertvanHorrik** [comment]
This would only be changed for 6.x anyway. We will keep the current names for the 5.x releases (which we won't release anymore, we need to bite the bullet for 6.x at some stage).

**Comment by vaecors** [comment]
So if that's the case my viewpoint is this, renaming it to `IBusyService` would make more sense given it's behavior. Just about every implementation I've seen of this from Infragistics to Telerik calls it a Busy Indicator. Even a lot of controls in Telerik have it built in an expose it via an IsBusy property.

**Comment by alexfdezsauco** [comment]
ModalService?

**Comment by GeertvanHorrik** [comment]
Modal? It doesn't do anything related to modal?

**Comment by alexfdezsauco** [comment]
Well is a Modal dialog that waits or show a progress. But Modal could also include IUVisualizerService functions.

**Comment by alexfdezsauco** [comment]
Unless that PleaseWaitService implementation allows to display progress or wait on any control, in such case IBusyService is Ok.

**Comment by GeertvanHorrik** [comment]
>Unless that PleaseWaitService implementation allows to display progress or wait on any control, in such case IBusyService is Ok. 

@alexfdezsauco that is exactly what it does. For example, orchestra re-implements this for each shell

**Comment by GeertvanHorrik** [comment]
I am thinking `IBusyIndicatorService` instead of `IBusyService`.

**Comment by GeertvanHorrik** [comment]
Done!
