### ISSUE TITLE
CTL-695: CanExecuteMethod called more than one time during validation

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#692]
Jira issue originally created by user advapi:

I've also noticed that validation is called more times then expected.

Consider the example I've attached

When:
*  It loads it's called once (OK)
* Username 2 times (why?)
* Age 2 times(why?)
* Pets (or when all fields are filled 3 times, why?)

Has this issue been related with my other ticket #692?

**Comment by GeertvanHorrik** [comment]
@advapiIT is this still relevant?

**Comment by advapiIT** [comment]
yes, it's

**Comment by GeertvanHorrik** [comment]
@advapiIT do you have a repro? Otherwise we will close this ticket.
