### ISSUE TITLE
CTL-706: Problem with Catel's Window and Telerik AutoComplete Box

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#697]
Jira issue originally created by user advapi:

Hello,
I've noticed a strange behavior when I open a window for updating a cusom item and the selected item has more then one match. I thought that the problem was on the Telerik side so I wrote them and here's the reply.

Hi Paolo,

Thank you for contacting us.

We investigated the provided project and seems that the observed behavior is caused by third party framework used. If you try using regular WPF in order to display the PortfolioChooserControl inside you won't observe that issue - please test the following snippet in the OnOpenCommandExecute method:

//uiVisualizerService.Show(model);
 
var wpfWindow = new Window();
wpfWindow.Content = new PortfolioChooserControl()
{
    DataContext = model.PortfolioModel,
    LoadDefaultValue = false,
    AllowNull = false
};
 
wpfWindow.Show();

Looks like the Catel framework is moving the Window after is shown and it is reloading the content somehow which causes that issue, as workaround you can hook to the LocationChanged event of the PopupWindow and close the drop down of the AutoCompleteBox as shown below:

private void DataWindow_LocationChanged(object sender, System.EventArgs e)
{
    this.PortfolioChooserView.PortfolioCompleteBox.IsDropDownOpen = false;
}

Hope this helps."

Considering that their solution can be acceptable for me , is a wanted thing that the Window is moved? 

I've attached the sample I've sent to Telerik in order to test yourself

**Comment by GeertvanHorrik** [comment]
@advapiIT Is this still relevant?

**Comment by advapiIT** [comment]
no it's not, thanks

**Comment by GeertvanHorrik** [comment]
Closing.
