### ISSUE TITLE
CTL-743: Extending CommandHelper.CreateCommand

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#734]
Jira issue originally created by user advapi:

It would be great to extend the CommandHelper.CreateCommand in order to support CreateCommand<T> as sometime it's usefull to pass a parameter to the Command, and also provide a CreateTaskCommand to create a TaskCommand

I came across CommandHelper while reading [Hooking a command to validation automatically]

**Comment by GeertvanHorrik** [comment]
@advapiIT interested in doing a PR?

**Comment by advapiIT** [comment]
I'm going to see it right now

**Comment by GeertvanHorrik** [comment]
@advapiIT can you show me a use-case of how you would like to use this feature?

**Comment by GeertvanHorrik** [comment]
Closing since we got no response.
