### ISSUE TITLE
CTL-748: RaisePropertyChanged with InvalidateCommand

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#739]
Jira issue originally created by user mattias:

InvalidateCommands ist not called automaticaly. Only if I change a catel property. But if I have a property only with a geter  returning the value form a service. And the service provides a event to call RaisepropertyChanged the Commands ar not validated.

So a nice extension will be: to call RaisePropertyChanged with InvalidateCommands.
Its not possible to override RaisePropertyChanged its not virtual in ViewModelBase.

**Comment by GeertvanHorrik** [comment]
@MattiasEppler Pinging you about this issue.

**Comment by MattiasEppler** [comment]
Hi. In my opinion you can close the issue. As I sayed you can call RaisePropertyChanged("xxx") and it works. Why ist not working with an empty string. I don't know, but thats not so important.

**Comment by GeertvanHorrik** [comment]
Thanks for the follow-up. Closing.
