### ISSUE TITLE
CTL-772: Does Catel manipulate the AdornerLayer which shows the red validation border on errors

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#760]
Jira issue originally created by user DanielKuehner:

One year ago we changed .NET from 4.0 to 4.5. At this point we used Catel 3.9.0.
With this change of .NET we mentioned a red border around our grids (GridControl of DevExpress) which had bound an observable collection of ModelBase instances with business field errors for the first time.
In the first place we did some bad researched and thought this came up through a DX update which does not - it seems to be a .NET feature. Because our customers did not like the always on top red border we started a ticket: https://www.devexpress.com/support/center/Question/Details/T304979
In this discussion DX insist on you manipulating the VisualTree to show the border around the grid. But I do not believe this because of some investigations on my side and [CTL-584](https://catelproject.atlassian.net/browse/CTL-584).

So my question is: does Catel has to something with this red border around the grid?

I have attached to repos: one with DX (ErrorVisualization) and the other without DX but with a little bit different approach.

I am aware that the ArdonerLayer has to be always on top of everthing because its pretty close to the root of the VisualTree.

**Comment by GeertvanHorrik** [comment]
@DanielKuehner is this one still relevant? Otherwise I will close it. If it is relevant, then this should be fixed or v5.

**Comment by advapiIT** [comment]
Excuse me , does this ticket mean I shouldn't have to put an adorner myself
in order to show red border? since right now I've to...

**Comment by GeertvanHorrik** [comment]
@advapiIT if you set_ValidatesOnDataErrors_ & _NotifyOnValidationErrors_ to true, it should automatically work.

**Comment by DanielKuehner** [comment]
I am really out of this topic. We got a workaround from DevExpress so the panels are on top of the red border ... more ugly than helpfull. But I am still not aware of where the red border comes from.
So if there is capacity to look into this, please do it. Otherwise close and I will reopen if the topic comes up again.

**Comment by GeertvanHorrik** [comment]
@DanielKuehner thanks for the info. I will close for now. Feel free to re-open once it plays up again.
