### ISSUE TITLE
CTL-781: Support parent / child IoC containers

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#770]
Jira issue originally created by user @geertvanhorrik:

We need this in Orc.FilterBuilder and Orc.WorkspaceManagement. For now we have solved it with tags, but best is to created scoped containers where there is a fallback:

ServiceLocator
- child 1
- child 2

If a type cannot be found on a child, fallback to parent.

**Comment by lipchev** [comment]
Hello,
I have a question that may pertain to this issue- or maybe it is simply a misunderstanding on my part:
I have several screens, each displaying lists of the same type of user control, but requiring a different set of DI components injected into the children(per screen- not per instance). 
In the child's view model I would ideally like to have my dependencies injected via constructor parameter(along with the model), while the registrations are done on app level. However having failed to achieve that I resolved to using the RegisterDependencyResolverForType(typeof(MyChildViewModel), rootResolver)- when opening the screen- which overrides whatever the previous screen had set as dependencies, and having all of the services registered to rootResolver(the resolver for each screenVM-type) on app start- the screenVMs do not deal with any of the children's services- they just display children. However they do become aware of the types of child view models(as they require the explicit resolver registration to occur in the screen instance). Also having two screens display same type of children at the same time with different services injected into them- would seem to require a custom resolver.
It would have be nice to have the possibility that DI's in a child view model fail-back to the parent's VM dependency-resolver (or some parent scope). Or maybe there is already a way to achieve this that I'm not seeing?

**Comment by GeertvanHorrik** [comment]
@lipchev The IoC components inside Catel do support nesting and resolving inside a scope, but it's hard to apply this inside a user control view. If you can upload a simple (!) demo / repro with requirements, I might be able to implement something like this if we need something similar for our own needs.

**Comment by lipchev** [comment]
Thank you,
here is a simple(!) example of what I would like to achieve: 1 control (PersonsList) and two sub-contexts for birthday & wedding parties- each
 one contains an instance of GiftSelectionView, however I would like to inject a different type of IGiftShopService into each of them (BirthdayShop & WeddingShop resp.)
Ideally all registration is done in app.xaml.cs.
[FamilyScope.zip](https://github.com/Catel/Catel/files/1959171/FamilyScope.zip)

**Comment by lipchev** [comment]
Hello again,
I've just encountered another use case- this time concerning the DbContext scope & the UoW implementation from Orc.EntityFrameworkExtensions (I'm sorry if what follows reads like a stackoverflow question- but since it directly concerns this topic I thought I'd post it here):

Imagine the following scenario: the user is presented with a dialog/wizard for the creation of a complex object- like say an 'Order'. The window's view model is a type of AggregateRootViewModel<T> containing the RootEntity and the Unit of Work responsible for saving the modifications.
The different tabs/pages inside the window/dialog/wizard are implemented as separate views: one responsible for the Customer selection, one for the order components etc. None of the child view models have direct access to the UoW- they only fill up and validate their part of the object graph. But how do I then provide IRepository<Customer> to the child view model that uses the same DbContext as the UoW?
The way i see it I have the following options: 

1. Implement this the same way as described in my first post- having the AggregateRootVM register the RegisterDependencyResolverForType(typeof(MyChildViewModel), ..) - I really wouldn't want to go down this road this time.

**Comment by GeertvanHorrik** [comment]
Wouldn't tags in the service locator solve your problem? You can resolve types from the service locator with tags, and if a specific implementation is not registered, it will fallback to the default one (without a tag).

**Comment by lipchev** [comment]
I don't think so- for the following two reasons
1. I'd still have to register them with a late bound DbContext (I guess I could use the DbContextManager with the same tag that would be set upon the creation of the UoW)- which means that I'd have to account for every possible use of a [UoW : IRepository]- and I don't wan't to know if some IStartCustomer is _the_ repository that would(or not) be requested in the CustomerSelectionViewModel
2. if I had to assume that multiple creation workflows could be started- then what tag should the child view model register to? If it couldn't be constant I'd have to rely on a TagResolver of sorts - which is kinda like using the DependencyResolverForInstance on the model.

**Comment by lipchev** [comment]
On second thought maybe the first issue could be resolved if I setup the OrderCustomerSelectionVM with a constructor requiring a IOrderCustomerRepository, the implementation requiring an OrderCreationContext- that is the type of DbContext which is created in the UoW. Now I can register the OrderCreationContext  as late bound- using the DbContextManager< OrderCreationContext  > and this should work fine with a single instance creation(operation) workflow. It's a lot of code but at least it is clear: it's up to the child VM to either request OrderCreationContext type repositories or face the consequences of handling detached objects. 

As for point two- now I think we come back to either using tags or some other strategy for associating a given execution context with it's DbContext instance.. Still- would be nice to directly register dependencies on the current "View Model Scope"- this way I'd only register the OrderCreationContext inside the OrderCreationScreenVM (the AggregateRootVM)

**Comment by GeertvanHorrik** [comment]
Closing this one for now. We might re-consider this in the future, but for now it's off the table.

**Comment by lipchev** [comment]
Ok, sure- I'll ping you if I get some free time- I was planning on trying to help out with this one. 
FYI, the approach for handling the two DbContexts (reading/writing), outlined in my last few comments, seems to be working out fine thus far.
