### ISSUE TITLE
CTL-829: ShowDialog() closes many other UserControls

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#822]
Jira issue originally created by user menno:

I'm seeing some strange behavior when a modal dialog is displayed, either through the IUIVisualizerService or just by calling ShowDialog on the view manually.

What I'm seeing is that many parts of my user interface in the main window are closed when the dialog is shown, and their Unloaded methods are called. 

Not all parts are closed, however, and I'm at a loss why this is happening.

**Comment by GeertvanHorrik** [comment]
@mennodeij is this one still relevant?

**Comment by mennodeij** [comment]
I saw this a while ago, but I have moved away from using catel:DataWindow and catel:Window, so I have no way to reproduce this now.
