### ISSUE TITLE
CTL-853: TaskCommand LostFocus

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#848]
Jira issue originally created by user mattias:

I bind a TaskCommand to a button. In the execute method I start a new Thread

If I set focus on this button with the keyboard and click the button with the space key the focus of the button is lost. The sourrounding usercontrol get the focus.

If I use a normal Command instead of the TaskCommand the focus is still on the button after the command is executed.

**Comment by GeertvanHorrik** [comment]
@MattiasEppler is this one still relevant?

**Comment by GeertvanHorrik** [comment]
[Wired.zip](https://github.com/Catel/Catel/files/1042192/Wired.zip)

**Comment by MattiasEppler** [comment]
Hi. Yes it is still relevant. But I have no idea how to solve it.

**Comment by GeertvanHorrik** [comment]
Since we have a repro, we will look into it.

**Comment by GeertvanHorrik** [comment]
It appears this also happens to regular commands. This is because the enabled state of the button (CanExecute becomes false) is forcing the focus to be removed.

This is a WPF behavior "issue". To fix this, you could introduce a behavior that checks whether a button as focus when the IsEnabled changes to false. If so, you can restore the focus afterwards, but not sure if a user wants this kind of forced behavior.

Closing this one as it doesn't seem to be a Catel issue.
