### ISSUE TITLE
CTL-855: ModelBase uses too much memory

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#850]
Jira issue originally created by user DanielKuehner:

I do not know how to tell you this, but this problem makes us thinking of dropping Catel.

Take a look at the attached picture. If you want I can give you the code to verify the stats.
What you see is that Catel does need too much memory ... really: *too* much.

With our newest feature we are having millions of instances (5-6 mio) and having them derived from Catel pushed the RAM to 20 GB and above and our customers had to stop working :-/
What we did as first step was to derive our massivly used class from ObservableObject which reduced our memory consumption to 4 GB. We could do this because we do not need any Catel "stuff" here.
As a second step we analyzed the memory consumption - you have seen the results. And for now: this is a no go!

Deriving vom ModelBase uses ten times more memory than deriving from object or DependencyObject. Using Catel properties uses another ten times more memory than DependencyProperty - if we are looking at the 2 mio instances.
So there are two problems: ModelBase and Catel properties. Whereas the properties are the worse.

What goes wrong with Catel? I do not know! Our next step would be to analyze Catel to identify where the memory is used. Did you knew this? Are you suprised? Have you thought about this?
Is there a chance Catel can get over this without loosing its major of functionality?

For now we are thinking of banning Catel from our model classes and keep Catel for the views and other stuff. In other words we have to write our own little MVVM framework and must hope that all things still do work.

**Comment by GeertvanHorrik** [comment]
@DanielKuehner we have been trimming down the ModelBase a lot. There is still some room for improvements but it should perform better and have a smaller memory footprint. If you want, you can try out the latest Catel v5 binaries from the MyGet feed (see docs for details). Beware of the breaking changes though ;-)

**Comment by GeertvanHorrik** [comment]
ModelBase now has 7 fields left. Memory consumption went down as visible in our benchmarks:

![image](https://user-images.githubusercontent.com/1246444/27492694-66f41dea-5847-11e7-809a-d4d79e8c053b.png)

**Comment by GeertvanHorrik** [comment]
Still trimming down the properties we believe can be removed from the ModelBase.

**Comment by GeertvanHorrik** [comment]
I've removed 5 or 6 more properties (that would result in a backing field variable). Will run the benchmarks this weekend for new numbers.

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/27507377-5d8218fc-58ce-11e7-9b74-991251d90c8b.png)

**Comment by GeertvanHorrik** [comment]
I think this issue can be closed, 43% less memory usage compared to 4.5,4, 30% faster construction time

**Comment by DanielKuehner** [comment]
@GeertvanHorrik great thing! I am looking forward to test this in my application :)
