### ISSUE TITLE
CTL-858: Improve Mixed mode in FastObservableCollection

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#853]
Jira issue originally created by user @geertvanhorrik:

Mixed mode should keep track of the following situation:

In a suspension scope:

1. 4 items get added (1,2,3,4)
2. 2 items that were added get removed (2,3)

The final state should be correct (including the indices).

**Comment by GeertvanHorrik** [comment]
Pinging @DanielKuehner , we will start working on this soon.

**Comment by DanielKuehner** [comment]
Do you have any updates on your problem or even an example for me?

**Comment by GeertvanHorrik** [comment]
Once I start working on this, I will create a failing unit test.

**Comment by DanielKuehner** [comment]
@GeertvanHorrik thanks for pinging. I am looking forward for this change as I have special cases to test with. But I don't have time at the moment.
