### ISSUE TITLE
CTL-876: A view model bound to a view via the ViewModelToViewConverter is not registered in the ViewManager

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#872]
Jira issue originally created by user @geertvanhorrik:

**Comment by alexfdezsauco** [comment]
This is working properly, not as described in the issue. The view is already registered in the ViewManager as well as the view model is registered in the ViewModelManager. So, we can close this one.

**Comment by GeertvanHorrik** [comment]
Nice to hear, thanks for verifying!
