### ISSUE TITLE
CTL-890: Serialization with json

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#888]
Jira issue originally created by user mattias:

Hi.

I try to switch my serialization from xml to json. I installed the package Catel.Serialization.Json.

But how to to change the SerializationMode. Its only possible to set SerializationMode.XML or SerializationMode.Binary.

I don't find any helpt so serialize with json in catel.

**Comment by GeertvanHorrik** [comment]
@MattiasEppler is this one still relevant?

**Comment by MattiasEppler** [comment]
Yes it is.

**Comment by GeertvanHorrik** [comment]
@MattiasEppler we are trying to figure out whether we need to make changes to this. Can you refresh our minds a bit and explain what changes need to be done? Thanks!
