### ISSUE TITLE
CTL-926: Convert PCL to NetStandard

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#927]
Jira issue originally created by user @geertvanhorrik:

**Comment by SimonCropp** [comment]
ETA?

**Comment by GeertvanHorrik** [comment]
Waiting for netstandard 2.0, which ETA is this fall. Is this for Fody integrations? Because i hope it can keep working with full .net as well.

Sent from my Windows 10 phone

**Comment by SimonCropp** [comment]
Was hoping to have the fody reference assemblies just target netstandard.

**Comment by GeertvanHorrik** [comment]
Ah, but that’s a separate sln, we can convert that one to .net standard in a heartbeat

Sent from my Windows 10 phone
