### ISSUE TITLE
CTL-930: DeferValidationUntilFirstSaveCall is not working any more

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#932]
Jira issue originally created by user mattias:

Hi.
I marked some properties with the required attribut in viewmodel. And set DeferValidationUntilFirstSaveCall = true;

If I create a new object I get immediately errors in view. I get an red border and the message "field is required" before I call save.

**Comment by MattiasEppler** [comment]
Do I understand correctly? Is the issue "DeferValidationUntilFirstSaveCall is not working any more" fixed in catel 5.0.0?

**Comment by GeertvanHorrik** [comment]
We didn't have a repro, so I closed the issue. Did I miss the repro?

**Comment by MattiasEppler** [comment]
Yes its correct. I do not create a repro. But I still have this problem in my project. So I create a repro and reopen the issue or create a new?

**Comment by GeertvanHorrik** [comment]
re-open  the ticket please with a repro.

**Comment by GeertvanHorrik** [comment]
btw did you have a chance looking into the PR?

**Comment by MattiasEppler** [comment]
Into which PR? Or do you mean if I interested to do a new PR?

**Comment by GeertvanHorrik** [comment]
This one: https://github.com/Catel/Catel/pull/111

**Comment by MattiasEppler** [comment]
Ok, what do I have to do? I do not understand. The PR is done? Why is the PR referenced to this Issue? Sorry I'm confused.

**Comment by GeertvanHorrik** [comment]
I was just asking for a status update. Will ask other questions in the PR.

**Comment by MattiasEppler** [comment]
Ok. Give comment there. But still not know why this issue is referenced there 
------------
This was referenced 14 days ago 
 CTL-1022: Json Serialization enum  #140   
 CTL-930: DeferValidationUntilFirstSaveCall is not working any more  #932 
------------

**Comment by GeertvanHorrik** [comment]
No specific reason, it's probably because I mentioned it 14 minutes ago.
