### ISSUE TITLE
CTL-949: TaskCommand binding to IsExecuting does not reflect the right state when using the Executing event

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#950]
Jira issue originally created by user mattias:

Hi.

I want to show a icon while the taskcommand is executing.
I try to bind the Visibility of the icon to TaskCommand.IsExecuting. Its not working. I think IsExecuting does not fire PropertyChanged Event.

Is there an other way?

**Comment by GeertvanHorrik** [comment]
@alexfdezsauco we might need to look into the Catel.Examples repository. As you can see in the Authentication example, the button does not get re-evaluated.

**Comment by GeertvanHorrik** [comment]
Pinging @MattiasEppler

**Comment by GeertvanHorrik** [comment]
The reason we have this code is that the *Executing* event allows for the user to cancel the execution of the command. But I don't see any harm in moving the creation of the CancellationTokenSource up.

**Comment by GeertvanHorrik** [comment]
Done.

**Comment by MattiasEppler** [comment]
Hi. Yes thats also my opinion.

**Comment by GeertvanHorrik** [comment]
Build - 5.0.0-beta.8 should be on NuGet in about 10 minutes, then you can test it.
