### ISSUE TITLE
CTL-951: Cache ToString(), ToUpper() and ToLower() calls

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#953]
Jira issue originally created by user @geertvanhorrik:

String modifications are expensive because:

1. It requires cpu
2. It creates a string in memory

Try to use ordinal compare instead of ToLower() / ToUpper(). If you really have no other choice, try to cache the ToString() results.

**Comment by alexfdezsauco** [comment]
Fixed. 

The  following changes will be available in the develop branch.

Details:

1) Updated `IsNavigationForView` method of `NavigationEventArgsExtensions` class in favor of `ContainsIgnoreCase` instead `ToLowerInvariant`
2) Cache `ToString` method result of `Size` class. The cache is invalidated if any property that affect the `ToString` method's result changed.
3) Cache `ToString` method result of `BufferPolicy`. `BufferPolicy` instances are inmutable.
4) Cache `ToString` method result of `TypeRequestPath`.  Modified `TypeRequestPath` class to make its instances "inmutables". 
5) Cache `ToString` method result of `InputGesture`.  The cache is invalidated if any property that affect the `ToString` method's result changed.
6) Cache `Convert` method result of `TextToUpperCaseConverter` via CacheStorage.
7) Cache `Convert` method result of `TextToLowerCaseConverter` via CacheStorage.

Also added some unit tests.

**Comment by GeertvanHorrik** [comment]
Done, closing.
