### ISSUE TITLE
CTL-989: Create modern logo for Catel

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#992]
Jira issue originally created by user @geertvanhorrik:

**Comment by IsmailHassani** [comment]
where does "catel" stands for? does it have a meaning?

**Comment by GeertvanHorrik** [comment]
Searching for a good name is really, really hard, but in 2010 we thought "CatenaLogic Enterprise Library" was a good one...

Mostly it's used as a name for dogs ;-)

**Comment by mpartipilo** [comment]
I like simple logos. What I try to portray with this one: 5 30 degree triangles forming a C, with some rounding to create an effect similar to a turtle shell. With the separation between the shapes you can squint-see Ms and Vs in relation to MVVM. The gray points are intended to make it look like a wrench.
![modern_logo 001](https://user-images.githubusercontent.com/467049/28071694-f5eab3e4-6650-11e7-97a2-a77cca4e83fa.png)

**Comment by GeertvanHorrik** [comment]
@mpartipilo wow, looks nice, did you make this yourself?

**Comment by mpartipilo** [comment]
@GeertvanHorrik I just put it together after some doodling. I couldn't get a dog or cat that looked good and could be related to the project. After 2 pages and almost giving up I thought of this one, fired up inkscape and voilá.

**Comment by alexfdezsauco** [comment]
Looks good, but what if just do a small variation like this one. 

![image](https://user-images.githubusercontent.com/1785664/28082966-f9f48a82-6641-11e7-9ea2-a2ce1e674f5b.png)

**Comment by mpartipilo** [comment]
@alexfdezsauco I like how it looks. I'll pick up this idea. I'll post it later.

**Comment by GeertvanHorrik** [comment]
It looks like a croissant now, but still like it ;-)

**Comment by mpartipilo** [comment]
Some more iterations
![catel_logo_2 svg](https://user-images.githubusercontent.com/467049/28119205-48b3cb9c-6714-11e7-89ca-ea1ee6e4d3ac.png)

**Comment by GeertvanHorrik** [comment]
I think I like the "crab" ones the most. I'm not a fan of the "disks" stacked on top of eachother. @alexfdezsauco , what are your thoughts?

**Comment by mkhomutov** [comment]
I like simple ones
and if you will rotate it, it will look like a creature with earth :) maybe a dog

![image](https://user-images.githubusercontent.com/1632214/28138655-3bb527e2-675a-11e7-986f-bae1b91c9953.png)

**Comment by mkhomutov** [comment]
it has not too many details. It is colourful and not too bright at the same time.
these triangles look like Mediators for guitar.

**Comment by mpartipilo** [comment]
Indeed! And swapping the green and blue it would look like a dog with
old-school 3d glasses

**Comment by alexfdezsauco** [comment]
The first "crap" is a good one, but the "creature with ears" is also good.

**Comment by GeertvanHorrik** [comment]
Also see #1607
