### ISSUE TITLE
CTL-996: CircularDependencyException should contains type request path in ToString result

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#999]
Jira issue originally created by user szogun1987:

This change make type request path visible in logs from production. On the other hand it should be detected in feature tests (or even smoke ones done by developer) and can increase log size. Please decide.

**Comment by GeertvanHorrik** [comment]
@szogun1987 Still interested in doing a PR? We are currently moving a lot of components and are almost done. Then it's best to start doing new PR's again (the Catel solution is a lot easier to maintain).

**Comment by szogun1987** [comment]
As I remember I have included it in another PR (related to multi-threading behavior improvements in IoC container). Please verify if it already behaves as described in 5.x

**Comment by GeertvanHorrik** [comment]
Yes, already fixed, thanks!
